//*                                                                             
//* -- SETUP FOR RUNTIME ENVIRONMENT "ACCT"                                     
//*    COMMENT: PRODUCTION VALUE FOR INDEXD -> PROD CA-DELIVER IS USED          
//*                                                                             
//  SET RTEGRP=ACCT,INDRTE=W.ACCT,INDGRND=W.QASE,W=W,INDPSF=W.ACCT              
//  SET IMS=IMF0,DB2SYS=D2F0,VX=VC,INDPLOG=W.ACCT,GRNDGRP=QASE                  
//  SET INDBAS=W.ACPT,INDUSRL=F1IMF0.IMS,INDRESL=SYS1.F1IM00.IMS                
//  SET WG01=W.ACCT,DBB=DLI,DBRC=Y,CPU=1,EMID70=NOBACKUP                        
//  SET BACKUPC=NOBACKUP,DEL2BKPC=DEL20,BACKUP7=NOBACKUP                        
//  SET INDEXD=F1DPVC,INDLIB2=W.QASE,INDLIB3=W.QASE                             
//*                                                                             
