//*                                                                             
//* -- SETUP FOR RUNTIME ENVIRONMENT "DEVE"                                     
//*    COMMENT: INDEXD IS A DUMMY VALUE SINCE WE DO NOT USE                     
//*             USE CA-DELIVER IN NJESG                                         
//*                                                                             
//  SET RTEGRP=DEVE,INDRTE=W.DEVE,INDGRND=W.PROD,W=W,INDPSF=W.DEVE              
//  SET IMS=IMP0,DB2SYS=D2B1,VX=SG,INDPLOG=W.DEVE,GRNDGRP=PROD                  
//  SET INDBAS=W.DEVE,INDUSRL=F1IMP0.IMS,INDRESL=SYS1.F1IM00.IMS                
//  SET WG01=W.DEVE,DBB=DLI,DBRC=Y,CPU=1,EMID70=NOBACKUP                        
//  SET BACKUPC=NOBACKUP,DEL2BKPC=DEL20,BACKUP7=NOBACKUP                        
//  SET NOBACKUP=NOBACKUP                                                       
//  SET ZCEEVER=&ZCEEDVER                                                       
//  SET INDEXD=F1DPSG,INDLIB2=W.IGRT,INDLIB3=W.ACPT                             
//  SET FROMDFLT='''FROM=NO.REPLY.DEVE@VOLVOCARS.COM'''                         
//*                                                                             
