//*                                                                             
//* -- SETUP FOR RUNTIME ENVIRONMENT "QASE PRODUCTION"                          
//*                                                                             
//  SET RTEGRP=QASE,INDRTE=W.QASE,INDGRND=W.QASE,W=W,INDPSF=W.QASE              
//  SET IMS=IMG0,DB2SYS=D2G0,VX=VC,INDPLOG=WG01.PGMLOG,GRNDGRP=QASE             
//  SET INDBAS=WG01.QASE,INDUSRL=F1IMG0.IMS,INDRESL=SYS1.F1IM00.IMS             
//  SET WG01=WG01,DBB=DBB,DBRC=Y,CPU=1,EMID70=EMID70                            
//  SET BACKUPC=BACKUPC,DEL2BKPC=DEL2BKPC,BACKUP7=BACKUP7                       
//  SET NOBACKUP=NOBACKUP                                                       
//  SET ZCEEVER=&ZCEEPVER                                                       
//  SET INDEXD=F1DPVC,INDLIB2=W.QASE,INDLIB3=W.QASE                             
//  SET FROMDFLT='''FROM=DCIDHELP@VOLVOCARS.COM'''                              
//*                                                                             
