000100*                  * CONVERTED BY VILMAII *                               
000200*                  * TO PURE COBOLCODE    *                               
000300     SKIP3                                                                
000400 ID DIVISION.                                                             
000500 PROGRAM-ID.         W0926000.                                            
000600*              PROGRAM CONVERTED BY                                       
000700*              COBOL CONVERSION AID PO 5785-ABJ                           
000800*              CONVERSION DATE 05/25/91 18:10:28.                         
000900*AUTHOR.             MARGARETA GABRIELSSON.                               
001000*DATE-WRITTEN.       MARS 1984.                                           
001100*    SKIP2                                                                
001200*REMARKS.                                                                 
001300*        PROGRAMMET LÄSER FIL FRÅN LV OCH SKRIVER UT R05 OCH              
001310*        SKAPAR R22 OCH R23. ÖVRIGT IGNORERAS.                            
001500     EJECT                                                                
001600 ENVIRONMENT DIVISION.                                                    
001700     SKIP2                                                                
001800 CONFIGURATION SECTION.                                                   
001900     SKIP2                                                                
002000 INPUT-OUTPUT SECTION.                                                    
002100 FILE-CONTROL.                                                            
002200     SKIP2                                                                
002300*                            *** INFIL                         ***        
002400     SELECT INFIL      ASSIGN TO UT-S-W09260D1.                           
002500     SKIP2                                                                
002600******************************** UTFIL                                    
002700*                                                                         
002900     SELECT W09261     ASSIGN TO UT-S-W09260D2.                           
003000     SKIP2                                                                
003100     EJECT                                                                
003200 DATA DIVISION.                                                           
003300 FILE SECTION.                                                            
003400     SKIP2                                                                
003500 FD  INFIL                                                                
003600     RECORDING V                                                          
003700     BLOCK 0                                                              
003800                          .                                               
003900 01  INPOST       PIC X(80).                                              
004000     SKIP3                                                                
004100 FD  W09261                                                               
004200     RECORDING V                                                          
004300     BLOCK 0                                                              
004400                          .                                               
004500 01  UTPOST       PIC X(80).                                              
004600     EJECT                                                                
004700 WORKING-STORAGE SECTION.                                                 
004710                                                                          
004800*    -- CHECKED BY WY2000                                                 
004900 77  INDENT-I PIC X(40) VALUE                                             
005000     'W0926000 91/05/25 TIME 12.59 VILMAII'.                              
005100***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
005200*                                                                         
005300     SKIP2                                                                
005400 01  KONSTANTER.                                                          
005500     05  JA              PIC X           VALUE 'J'.                       
005600     05  NEJ             PIC X           VALUE 'N'.                       
005700     SKIP2                                                                
005800 01  EOF-SWITCHAR.                                                        
005900     05  INFIL-EOF       PIC X           VALUE 'N'.                       
006000     SKIP2                                                                
006100 01  DYNAMISKA-SUBPROGRAM.                                                
006200     05  ABEND           PIC X(8)        VALUE 'ABEND   '.                
006300     05  POSTSUM         PIC X(8)        VALUE 'POSTSUM '.                
006400     SKIP2                                                                
006410 01  W-BESTNR            PIC 9(12).                                       
006420 01  FILLER REDEFINES W-BESTNR.                                           
006430     03  W-BESTPREF      PIC 9(3).                                        
006440     03  W-BESTLNR       PIC 9(6).                                        
006450     03  FILLER REDEFINES W-BESTLNR.                                      
006460         05  W-BESTLNR-POS1   PIC 9.                                      
006470         05  FILLER           PIC 9(5).                                   
006480     03  W-BESTSUFF      PIC 9(3).                                        
006490     SKIP2                                                                
006491 01  W-ARTNR             PIC 9(8).                                        
006492 01  W-DATUM-UTSKR       PIC 9(6).                                        
006493 01  W-LEVNUM            PIC 9(5).                                        
006494 01  W-ANT-BESTANN       PIC 9(7).                                        
006495 01  W-POSTTYP-UT        PIC X(3).                                        
006496     EJECT                                                                
006500*                        *** PARAMETRAR TILL POSTSUM           ***        
006600*01  -COPY W0005CCCC0  -PRE POSTSUM-                                      
006700*++INCLUDE W0005CCCC0                                                     
006800     03  REG-IN-TRANSID.                                                  
006900         05 REG-IN-FDNAMN        PIC X(6)  VALUE 'INFIL '.                
007000         05 REG-IN-DDNAMN        PIC X(8)  VALUE 'W09260D1'.              
007100         05 REG-IN-TRANSTYP      PIC X(4)  VALUE SPACE.                   
007200*                                                                         
007300     03  REG-UT-TRANSID.                                                  
007400         05 REG-UT-FDNAMN        PIC X(6)  VALUE 'W09261'.                
007500         05 REG-UT-DDNAMN        PIC X(8)  VALUE 'W09260D2'.              
007600         05 REG-UT-TRANSTYP      PIC X(4).                                
007700     EJECT                                                                
007800*                            *************************************        
007900*                            **  AREA FÖR W09261-POST           **        
008000*                            *************************************        
008100 01  IN-AREA.                                                             
008200     03  IDKTYP     PIC X(3).                                             
008300     03  FILLER     PIC X(81).                                            
008310 01  AREA -COPY T312R940 -PRE IN940- -RED IN-AREA.                        
008320 01  AREA -COPY T312R941 -PRE IN941- -RED IN-AREA.                        
008321     EJECT                                                                
008330******************************UTAREA                                      
008340 01 UT-AREA.                                                              
008350    03  FILLER      PIC X(80)  VALUE SPACE.                               
008360 01  AREA -PRE UTR2X- -COPY W212R22K -RED UT-AREA.                        
008400     EJECT                                                                
008500 PROCEDURE DIVISION.                                                      
008600     PERFORM A-INITIERING                                                 
008700     SKIP2                                                                
008800     PERFORM S01-LAS-INFIL                                                
008900     PERFORM UNTIL                                                        
009000      NOT ( INFIL-EOF = NEJ )                                             
009100       IF IDKTYP = 'R05'                                                  
009110         MOVE IN-AREA TO UT-AREA                                          
009200         PERFORM S02-SKRIV-W09261                                         
009210       ELSE                                                               
009220         IF IN940-PT = 940                                                
009230           PERFORM D-BESTAEM-POSTTYP-UT                                   
009240           PERFORM E-SKAPA-R22-ELLER-R23                                  
009250         ELSE                                                             
009260           IF IN940-PT = 941                                              
009270             PERFORM F-SKAPA-R22                                          
009280           END-IF                                                         
009290         END-IF                                                           
009300       END-IF                                                             
009400       PERFORM S01-LAS-INFIL                                              
009500     END-PERFORM                                                          
009600     SKIP2                                                                
009700     PERFORM C-AVSLUTNING                                                 
009800*                                                                         
009900     SKIP2                                                                
010000     MOVE ZERO TO RETURN-CODE                                             
010100     GOBACK                                                               
010200     CONTINUE.                                                            
010300     EJECT                                                                
010400 A-INITIERING SECTION.                                                    
010500     SKIP2                                                                
010510     MOVE 'W09260' TO POSTSUM-PROGNAMN                                    
010600     OPEN INPUT INFIL                                                     
010700     OPEN OUTPUT W09261                                                   
010800     CONTINUE.                                                            
010900     SKIP3                                                                
011000 C-AVSLUTNING SECTION.                                                    
011100     MOVE 'S' TO POSTSUM-OPKOD                                            
011300     CALL POSTSUM USING POSTSUM-PARM                                      
011400*                                                                         
011800     CLOSE INFIL W09261                                                   
011900     CONTINUE.                                                            
012000     EJECT                                                                
012010 D-BESTAEM-POSTTYP-UT SECTION.                                            
012020     MOVE IN940-BESTLNR TO W-BESTLNR                                      
012030     IF (W-BESTLNR-POS1 = 9) AND (IN940-BESTANT = 0)                      
012040       MOVE 'R23' TO W-POSTTYP-UT                                         
012050     ELSE                                                                 
012060       MOVE 'R22' TO W-POSTTYP-UT                                         
012070     END-IF                                                               
012080     .                                                                    
012090     EJECT                                                                
012091 E-SKAPA-R22-ELLER-R23 SECTION.                                           
012092     MOVE W-POSTTYP-UT TO UTR2X-IDPTYP                                    
012093     MOVE IN940-ARTNR TO      W-ARTNR                                     
012094     MOVE W-ARTNR     TO  UTR2X-IDARTNR                                   
012095                                                                          
012096     MOVE IN940-BESTPREF TO W-BESTPREF                                    
012097     MOVE IN940-BESTLNR TO  W-BESTLNR                                     
012098     MOVE IN940-BESTSUFF TO W-BESTSUFF                                    
012099     MOVE W-BESTNR     TO UTR2X-IDBEST                                    
012100                                                                          
012101     MOVE IN940-LEVNUM TO W-LEVNUM                                        
012102     MOVE W-LEVNUM TO     UTR2X-IDLEVNR-BEST                              
012103                                                                          
012104     MOVE IN940-DATUM-UTSKR TO W-DATUM-UTSKR                              
012105     MOVE W-DATUM-UTSKR TO UTR2X-TIBEST                                   
012106                                                                          
012107     MOVE IN940-BESTANT TO W-ANT-BESTANN                                  
012108     MOVE W-ANT-BESTANN TO UTR2X-KVBEST                                   
012109                                                                          
012110     MOVE '1' TO UTR2X-KDBEH-BEST                                         
012111     MOVE SPACE TO UTR2X-TENOT-BESTPRIS                                   
012112                                                                          
012113     PERFORM S02-SKRIV-W09261                                             
012114     .                                                                    
012115     EJECT                                                                
012116 F-SKAPA-R22 SECTION.                                                     
012117     MOVE 'R22' TO  UTR2X-IDPTYP                                          
012118                                                                          
012119     MOVE IN941-ARTNR TO     W-ARTNR                                      
012120     MOVE W-ARTNR     TO UTR2X-IDARTNR                                    
012121                                                                          
012122     MOVE IN941-BESTPREF TO  W-BESTPREF                                   
012123     MOVE IN941-BESTLNR  TO  W-BESTLNR                                    
012124     MOVE IN941-BESTSUFF TO  W-BESTSUFF                                   
012125     MOVE W-BESTNR       TO  UTR2X-IDBEST                                 
012126                                                                          
012127     MOVE IN941-LEVNUM   TO W-LEVNUM                                      
012128     MOVE W-LEVNUM       TO UTR2X-IDLEVNR-BEST                            
012129                                                                          
012130     MOVE IN941-DATUM-UTSKR TO W-DATUM-UTSKR                              
012131     MOVE W-DATUM-UTSKR  TO UTR2X-TIBEST                                  
012132                                                                          
012133     MOVE IN941-BESTANT TO  W-ANT-BESTANN                                 
012134     MOVE W-ANT-BESTANN TO  UTR2X-KVBEST                                  
012135                                                                          
012136     MOVE '5' TO UTR2X-KDBEH-BEST                                         
012137     MOVE SPACE TO UTR2X-TENOT-BESTPRIS                                   
012138     PERFORM S02-SKRIV-W09261                                             
012139     .                                                                    
012140     EJECT                                                                
012150 S01-LAS-INFIL SECTION.                                                   
012200     SKIP2                                                                
012300     READ INFIL INTO IN-AREA                                              
012400             AT END MOVE JA TO INFIL-EOF                                  
012500     END-READ                                                             
012600*                                                                         
012601     IF INFIL-EOF = NEJ                                                   
012610     IF IDKTYP = 'R05'                                                    
012700        MOVE IDKTYP         TO REG-IN-TRANSTYP                            
012701     ELSE                                                                 
012702        IF IN940-PT = 940                                                 
012703          MOVE '940' TO REG-IN-TRANSTYP                                   
012704        ELSE                                                              
012705          IF IN940-PT = 941                                               
012706             MOVE '941' TO REG-IN-TRANSTYP                                
012707          ELSE                                                            
012708             MOVE SPACE TO REG-IN-TRANSTYP                                
012709          END-IF                                                          
012710        END-IF                                                            
012711     END-IF                                                               
012720     MOVE REG-IN-TRANSID TO POSTSUM-TRANSID                               
012800     CALL POSTSUM USING POSTSUM-PARM                                      
012810     END-IF                                                               
012900     CONTINUE.                                                            
013000     SKIP3                                                                
013100 S02-SKRIV-W09261 SECTION.                                                
013200     SKIP2                                                                
013300     WRITE UTPOST FROM UT-AREA                                            
013400*                                                                         
013500     MOVE UTR2X-IDPTYP   TO REG-UT-TRANSTYP                               
013510     MOVE REG-UT-TRANSID TO POSTSUM-TRANSID                               
013600     CALL POSTSUM USING POSTSUM-PARM                                      
013700     CONTINUE.                                                            
