000100*                  * CONVERTED BY VILMAII *                               
000200*                  * TO PURE COBOLCODE    *                               
000300 ID DIVISION.                                                             
000400 PROGRAM-ID.     W1116000.                                                
000500*              PROGRAM CONVERTED BY                                       
000600*              COBOL CONVERSION AID PO 5785-ABJ                           
000700*              CONVERSION DATE 05/25/91 17:36:33.                         
000800*AUTHOR.         INGRID DANIELSSON.                                       
000900*DATE-WRITTEN.   MAJ 1979.                                                
001000*REMARKS.                                                                 
001100*        FUNCTION.                                                        
001200*            PROGRAMMET SKAPAR UNDERLAG FÖR ERSÄTTNINGSLISTA,             
001300*            OCH TAR BORT ERSÄTTNINGSINFORMATION PÅ WDD7 FÖR DE           
001400*            ARTIKLAR SOM BLIVIT DEFINITIVT ERSATTA UNDER VECKAN.         
001500*            DESSUTOM UPPDATERAS PRELIMINÄWDATUM FÖR DE ARTIKLAR          
001600*            SOM EJ HAR BLIVIT DEFINITIVA.                                
001700*        INDATA.                                                          
001800*            ARTIKELREGISTRET, WDK6.                                      
001900*            ERSÄTTNINGS-BASEN, WDD7.                                     
002000                                                                          
002100*        UTDATA.                                                          
002200                                                                          
002300     EJECT                                                                
002400 ENVIRONMENT DIVISION.                                                    
002500 INPUT-OUTPUT SECTION.                                                    
002600 FILE-CONTROL.                                                            
002700     SKIP2                                                                
002800 DATA DIVISION.                                                           
002900 FILE SECTION.                                                            
003000     SKIP2                                                                
003100 WORKING-STORAGE SECTION.                                                 
003200*    -COPY WY2000W2                                                       
003300     SKIP3                                                                
003400 77  INDENT-I PIC X(40) VALUE                                             
003500     'W1116000 91/05/25 TIME 13.06 VILMAII'.                              
003600***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
003700*                                                                         
003800 77  HOEGSTA-TIFINLV             PIC S9(5)   COMP-3.                      
003900 77  JA                          PIC X       VALUE 'J'.                   
004000 77  NEJ                         PIC X       VALUE 'N'.                   
004010 77  W-CHKP-RAKNARE              PIC S9(5)   VALUE +0    COMP-3.          
004020 77  W-CHKP-MAX                  PIC S9(5)   VALUE +800  COMP-3.          
004030 77  CHKP-ID                     PIC X(8)    VALUE 'W1116000'.            
004040 77  MSG-IO-AREA-LENGTH-1        PIC S9(9)   VALUE +32  COMP SYNC.        
004050 77  MSG-IO-AREA-1               PIC X(32)   VALUE SPACE.                 
004060 77  CHKP-AREA-1-LENGTH          PIC S9(9)   VALUE +32  COMP SYNC.        
004070 77  CHKP-AREA-1                 PIC X(32)   VALUE SPACE.                 
004100                                                                          
004200 01  SWITCHAR.                                                            
004300     03  ART-DEF-UNDER-VECKAN-SW    PIC X      VALUE 'N'.                 
004400         88  ART-DEF-UNDER-VECKAN              VALUE 'J'.                 
004500                                                                          
004600 01  RAKNARE.                                                             
004700     03  ANTAL-TILLK-ART   PIC S9(4) COMP SYNC VALUE +0.                  
004800         88  TILLK-ART-FINNS                   VALUE +1 THRU +100.        
004900                                                                          
005000 01  OMVANDLINGSFALT.                                                     
005100     03  W-KDERS                      PIC 99.                             
005200     03  FILLER REDEFINES W-KDERS.                                        
005300         05  FORSTA-SIFFRAN-PA-W-KDERS     PIC 9.                         
005400         05  ANDRA-SIFFRAN-PA-W-KDERS      PIC 9.                         
005500                                                                          
005600 01  INDEX-FALT.                                                          
005700     03  IX                  PIC S9(4) COMP SYNC  VALUE +0.               
005800     03  SEGM-IX             PIC S9(4) COMP SYNC  VALUE +0.               
005900     EJECT                                                                
006000 01  GENERELLA-SUBPGM.                                                    
006100     03  CBLTDLI             PIC X(8)    VALUE 'CBLTDLI'.                 
006200     03  FELLOG              PIC X(8)    VALUE 'FELLOG '.                 
006300     03  DATKORT             PIC X(8)    VALUE 'DATKORT'.                 
006400                                                                          
006500 01  FILLER                    PIC X(20)   VALUE ALL 'F'.                 
006600                                                                          
006700*01  AREA  -COPY WDK601    -PRE ARTC01-.                                  
006800     EJECT                                                                
006900 01  FILLER                    PIC X(20)   VALUE ALL 'J'.                 
007000                                                                          
007100*01  AREA  -COPY WDK611    -PRE ARTC11-.                                  
007200     EJECT                                                                
007300 01  FILLER                   PIC X(20)   VALUE ALL 'N'.                  
007400     SKIP2                                                                
007500*---------------->>>  O C C U R S   1 0 0  <<<-------------------         
007600 01  FILLER.                                                              
007700     03  WDD702-AREA                      OCCURS 100.                     
007800*      05  -COPY WDD702    -PRE WDD702-                                   
007900     EJECT                                                                
008000 01  FILLER                   PIC X(20)   VALUE ALL 'O'.                  
008100     SKIP2                                                                
008200*01  AREA  -COPY WDD704    -PRE WDD704-.                                  
008300     EJECT                                                                
008400 01  FILLER                   PIC X(20)   VALUE ALL 'P'.                  
008500     SKIP2                                                                
008600*01  WDK601-AREA  -COPY WDK601                                            
008700     EJECT                                                                
008800 01  FILLER                   PIC X(20)   VALUE ALL 'Q'.                  
008900     SKIP2                                                                
009000*01  WDK611-AREA  -COPY WDK611                                            
009100     EJECT                                                                
009200 01  NYCKLAR.                                                             
009300     03  W-IDARTNR-X.                                                     
009400         05  W-IDARTNR   PIC S9(9) COMP-3.                                
009500     03  W-IDARTNR-ING-X.                                                 
009600         05  W-IDARTNR-ING  PIC S9(9)  COMP-3.                            
009700     SKIP3                                                                
009800 01  GODK-STATUSKODER.                                                    
009900     03  GODK-STATUS     PIC XX                                           
010000         OCCURS 5 INDEXED BY STATUS-IX.                                   
010100     SKIP3                                                                
010200 01  STATUS-WS           PIC XX.                                          
010300     88  BASEN-SLUT              VALUE 'GB'.                              
010400     88  SEGMENT-FINNS           VALUE '  '.                              
010500     SKIP3                                                                
010600 01  SSA-ER.                                                              
010700     03  SSA1            PIC X(30).                                       
010800     03  SSA2            PIC X(30).                                       
010900     03  SSA3            PIC X(30).                                       
011000     EJECT                                                                
011100*01  -COPY W0003                                                          
011200     EJECT                                                                
011300 01  FILLER                  PIC X(20)   VALUE ALL 'P'.                   
011400     SKIP2                                                                
011500 01  DLI-IO-AREA             PIC X(1000).                                 
011600     EJECT                                                                
011700 LINKAGE SECTION.                                                         
011800     SKIP2                                                                
011900*01  -COPY W0009 -PRE MSG-                                                
012100     EJECT                                                                
012110*01  -COPY W0008 -PRE WDK6-.                                              
012120           05  ARTC-KONKAT-KEY     PIC X(20).                             
012130     EJECT                                                                
012200*01  -COPY W0008 -PRE WDD7-.                                              
012300           05  AC-KONKAT-KEY    PIC X(10).                                
012400     EJECT                                                                
012500*01  -COPY W0008 -PRE WDD71-.                                             
012600           05  AC-GN-KONKAT-KEY.                                          
012700               07 AC-GN-KONKAT-IDARTNR   PIC S9(9) COMP-3.                
012800     EJECT                                                                
012900 PROCEDURE DIVISION USING MSG-PCB WDK6-PCB WDD7-PCB WDD71-PCB.            
013000                                                                          
013100     ENTRY 'DLITCBL' USING MSG-PCB WDK6-PCB WDD7-PCB WDD71-PCB.           
013200                                                                          
013210     PERFORM A-INIT                                                       
013220                                                                          
013300*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*             
013400*    WDD7 LÄSES.                                            *             
013500*    INFORMATION HÄMTAS FRÅN WDK6                           *             
013600*    POSTER MED UNDERLAG TILL ERSÄTTNINGSLISTORNA SKAPAS    *             
013700*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*             
013800                                                                          
013900     PERFORM B-LAS-NASTA-WDD704-PA-ERSREG                                 
014000                                                                          
014100     PERFORM UNTIL                                                        
014200        BASEN-SLUT                                                        
014300       MOVE AC-GN-KONKAT-IDARTNR TO W-IDARTNR                             
014400       PERFORM D-LAS-RESTEN-PA-ERSREG                                     
014500       PERFORM E-LAS-SAMMA-ART-PA-ARTREG                                  
014600                                                                          
014700       IF WDD704-KDSTATUS-C1 = 0                                          
014800         MOVE JA TO ART-DEF-UNDER-VECKAN-SW                               
014900       END-IF                                                             
015000       MOVE    +0    TO HOEGSTA-TIFINLV                                   
015100       MOVE    +1    TO IX                                                
015200                                                                          
015300       PERFORM UNTIL                                                      
015400        NOT ( TILLK-ART-FINNS )                                           
015500         IF WDD702-FLTEXT (IX) = JA                                       
015600           CONTINUE                                                       
015700         ELSE                                                             
015800           PERFORM F-LAS-TILLK-ART-PA-ARTREG                              
015900           PERFORM G-KONTR-TILLK-ART                                      
016000         END-IF                                                           
016100          ADD      +1   TO IX                                             
016200          SUBTRACT +1 FROM ANTAL-TILLK-ART                                
016300       END-PERFORM                                                        
016400       PERFORM H-EV-UPPD-EL-DELETE-AV-ERSINF                              
016500                                                                          
016541                                                                          
016542                                                                          
016600       PERFORM B-LAS-NASTA-WDD704-PA-ERSREG                               
016610       IF W-CHKP-RAKNARE                       >  W-CHKP-MAX              
016620          PERFORM IMS-CHECKPOINT                                          
016630          MOVE ZERO                           TO W-CHKP-RAKNARE           
016640          MOVE AC-GN-KONKAT-IDARTNR TO W-IDARTNR                          
016641          PERFORM IMS-GU-WDD704                                           
016650       END-IF                                                             
016700       MOVE NEJ TO ART-DEF-UNDER-VECKAN-SW                                
016800     END-PERFORM                                                          
016900                                                                          
017000     MOVE  +0   TO RETURN-CODE                                            
017100     GOBACK                                                               
017200     .                                                                    
017300     EJECT                                                                
017310 A-INIT SECTION.                                                          
017320                                                                          
017330     PERFORM IMS-RESTART                                                  
017340                                                                          
017360     MOVE ZERO       TO W-CHKP-RAKNARE                                    
017380     .                                                                    
017390     EJECT                                                                
017400 B-LAS-NASTA-WDD704-PA-ERSREG SECTION.                                    
017500                                                                          
017600     PERFORM IMS-GHN-WDD704-MED-GN-PCB                                    
017700     IF SEGMENT-FINNS                                                     
017800       MOVE DLI-IO-AREA TO WDD704-AREA                                    
017900     END-IF                                                               
018000     .                                                                    
018100     EJECT                                                                
018200 D-LAS-RESTEN-PA-ERSREG SECTION.                                          
018300                                                                          
018400     PERFORM IMS-GHU-WDD701                                               
018500                                                                          
018600     MOVE +0 TO IX                                                        
018700     MOVE +0 TO ANTAL-TILLK-ART                                           
018800     PERFORM UNTIL                                                        
018900      NOT ( SEGMENT-FINNS AND IX < 100 )                                  
019000        ADD  +1   TO IX                                                   
019100       PERFORM IMS-GNP-WDD702                                             
019200       IF SEGMENT-FINNS                                                   
019300          MOVE DLI-IO-AREA TO WDD702-AREA (IX)                            
019400          ADD      +1      TO ANTAL-TILLK-ART                             
019500       ELSE                                                               
019600          MOVE   SPACE     TO WDD702-AREA (IX)                            
019700       END-IF                                                             
019800     END-PERFORM                                                          
019900     .                                                                    
020000     EJECT                                                                
020100 E-LAS-SAMMA-ART-PA-ARTREG SECTION.                                       
020200                                                                          
020300     PERFORM IMS-GHU-ARTC01                                               
020400     MOVE DLI-IO-AREA TO ARTC01-AREA                                      
020500                                                                          
020600     IF ARTC01-ART-KDERS-UTG > 0                                          
020700       MOVE ARTC01-ART-KDERS-UTG TO W-KDERS                               
020800     ELSE                                                                 
020900       PERFORM IMS-GNP-ARTC11                                             
021000       IF SEGMENT-FINNS                                                   
021100          MOVE DLI-IO-AREA TO ARTC11-AREA                                 
021200          MOVE ARTC11-CLAG-KDERS TO W-KDERS                               
021300       END-IF                                                             
021430     END-IF                                                               
021500     .                                                                    
021600     EJECT                                                                
021700 F-LAS-TILLK-ART-PA-ARTREG SECTION.                                       
021800                                                                          
021900     MOVE WDD702-IDARTNR-TILLK (IX) TO W-IDARTNR                          
022000                                                                          
022100     PERFORM IMS-GHU-ARTC01                                               
022200     MOVE DLI-IO-AREA  TO  WDK601-AREA                                    
022300                                                                          
022400     PERFORM IMS-GNP-ARTC11                                               
022500     IF SEGMENT-FINNS                                                     
022600        MOVE DLI-IO-AREA  TO WDK611-AREA                                  
022700     ELSE                                                                 
022800        MOVE   SPACE      TO WDK611-AREA                                  
022900     END-IF                                                               
023000     .                                                                    
023100     EJECT                                                                
023200 G-KONTR-TILLK-ART SECTION.                                               
023300                                                                          
023400     IF  FORSTA-SIFFRAN-PA-W-KDERS = 0                                    
023500       MOVE ART-TIFINLV   TO TMP1-YYWWD                                   
023600       MOVE HOEGSTA-TIFINLV       TO TMP2-YYWWD                           
023700       PERFORM WY2000P2                                                   
023800       IF TMP1-YYWWD > TMP2-YYWWD                                         
023900         MOVE ART-TIFINLV TO HOEGSTA-TIFINLV                              
024000       END-IF                                                             
024100     END-IF                                                               
024200***  IF WDK611-AREA = SPACE                                               
024300***    DISPLAY 'TILLK ARTIKEL ' ART-IDARTNR ' ÄR UTGÅNGEN'                
024400***  ELSE                                                                 
024500***    IF CLAG-KDERS > +20                                                
024600***      DISPLAY 'TILLK ARTIKEL ' ART-IDARTNR ' ÄR REDAN'                 
024700***      'DEFINITIVT ERSATT            '                                  
024800***      'ERSATT ARTIKEL ' ARTC01-ART-IDARTNR                             
024900***    END-IF                                                             
025000***  END-IF                                                               
025100     .                                                                    
025200     EJECT                                                                
025300 H-EV-UPPD-EL-DELETE-AV-ERSINF SECTION.                                   
025400                                                                          
025500     IF  W-KDERS = +01 OR +02 OR +04 OR +05                               
025600       IF  WDD704-KDSTATUS-C1 = +2 OR +3                                  
025700         IF HOEGSTA-TIFINLV NOT = WDD704-TIERSDAT-PREL-C1                 
025800           MOVE HOEGSTA-TIFINLV TO WDD704-TIERSDAT-PREL-C1                
025900           MOVE WDD704-AREA TO DLI-IO-AREA                                
026000           PERFORM IMS-REPLACE-WDD704-MED-GN-PCB                          
026100***        DISPLAY 'TIFINLV UPPDAT' W-IDARTNR                             
026200         END-IF                                                           
026300       END-IF                                                             
026400     END-IF                                                               
026500                                                                          
026600     IF ART-DEF-UNDER-VECKAN                                              
026700       IF W-KDERS = 29 OR 52                                              
026800         MOVE ARTC01-ART-IDARTNR TO W-IDARTNR                             
026900         PERFORM IMS-GHU-WDD701                                           
026910         IF SEGMENT-FINNS                                                 
026911            PERFORM IMS-DELETE-WDD701                                     
026920         END-IF                                                           
027100       ELSE                                                               
027110         IF SEGMENT-FINNS                                                 
027121            PERFORM IMS-DELETE-WDD704-MED-GN-PCB                          
027130         END-IF                                                           
027300       END-IF                                                             
027400     END-IF                                                               
027500     .                                                                    
027600     EJECT                                                                
027610 IMS-RESTART           SECTION.                                           
027620                                                                          
027630     MOVE SPACE TO MSG-IO-AREA-1                                          
027640     MOVE '  ' TO GODK-STATUSKODER                                        
027650     CALL CBLTDLI USING XRST MSG-PCB                                      
027660                        MSG-IO-AREA-LENGTH-1 MSG-IO-AREA-1                
027670                        CHKP-AREA-1-LENGTH CHKP-AREA-1                    
027680     MOVE MSG-STATUS-CODE TO STATUS-WS                                    
027690     PERFORM IMS-STATUSKONTROLL                                           
027691     .                                                                    
027692                                                                          
027693     SKIP3                                                                
027694 IMS-CHECKPOINT        SECTION.                                           
027695                                                                          
027696     MOVE CHKP-ID TO MSG-IO-AREA-1                                        
027697     MOVE '  XD' TO GODK-STATUSKODER                                      
027698     CALL CBLTDLI USING CHKP MSG-PCB                                      
027699                        MSG-IO-AREA-LENGTH-1 MSG-IO-AREA-1                
027700                        CHKP-AREA-1-LENGTH CHKP-AREA-1                    
027701     MOVE MSG-STATUS-CODE TO STATUS-WS                                    
027702     PERFORM IMS-STATUSKONTROLL                                           
027703     .                                                                    
027704     EJECT                                                                
027710 IMS-GHU-ARTC01 SECTION.                                                  
027800                                                                          
027900     STRING 'WDK601  (IDARTNR  =' W-IDARTNR-X ')'                         
028000             DELIMITED BY SIZE INTO SSA1                                  
028100     MOVE '  ' TO GODK-STATUSKODER                                        
028200     CALL CBLTDLI USING GHU WDK6-PCB DLI-IO-AREA SSA1                     
028300     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
028400     PERFORM IMS-STATUSKONTROLL                                           
028500     .                                                                    
028600     SKIP3                                                                
028700 IMS-GNP-ARTC11 SECTION.                                                  
028800                                                                          
028900     MOVE 'WDK611   ' TO SSA1                                             
029000     MOVE '  GE' TO GODK-STATUSKODER                                      
029100     CALL CBLTDLI USING GNP WDK6-PCB DLI-IO-AREA SSA1                     
029200     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
029300     PERFORM IMS-STATUSKONTROLL                                           
029400     .                                                                    
029500     EJECT                                                                
029600 IMS-GHU-WDD701 SECTION.                                                  
029700                                                                          
029800     STRING 'WDD701  (IDARTNR  =' W-IDARTNR-X ')'                         
029900                      DELIMITED BY SIZE INTO SSA1                         
030000     MOVE '  ' TO GODK-STATUSKODER                                        
030100     CALL CBLTDLI USING GHU WDD7-PCB DLI-IO-AREA SSA1                     
030200     MOVE WDD7-STATUS-CODE TO STATUS-WS                                   
030300     PERFORM IMS-STATUSKONTROLL                                           
030400     .                                                                    
030500     SKIP3                                                                
030600 IMS-GNP-WDD702 SECTION.                                                  
030700                                                                          
030800     MOVE 'WDD702   ' TO SSA1                                             
030900     MOVE '  GE' TO GODK-STATUSKODER                                      
031000     CALL CBLTDLI USING GNP WDD7-PCB DLI-IO-AREA SSA1                     
031100     MOVE WDD7-STATUS-CODE TO STATUS-WS                                   
031200     PERFORM IMS-STATUSKONTROLL                                           
031300     .                                                                    
031400     SKIP3                                                                
031500 IMS-DELETE-WDD701 SECTION.                                               
031600                                                                          
031700     MOVE '  ' TO GODK-STATUSKODER                                        
031800     CALL CBLTDLI USING DLET WDD7-PCB DLI-IO-AREA                         
031900     MOVE WDD7-STATUS-CODE TO STATUS-WS                                   
032000     PERFORM IMS-STATUSKONTROLL                                           
032010     ADD +1 TO W-CHKP-RAKNARE                                             
032100     .                                                                    
032200     EJECT                                                                
032210 IMS-GU-WDD704 SECTION.                                                   
032220                                                                          
032230     STRING 'WDD701  (IDARTNR  =' W-IDARTNR-X ')'                         
032240              DELIMITED BY SIZE INTO SSA1                                 
032241     MOVE 'WDD704  '  TO SSA2                                             
032250     MOVE '  ' TO GODK-STATUSKODER                                        
032260     CALL CBLTDLI USING GHU WDD7-PCB DLI-IO-AREA SSA1                     
032270     MOVE WDD7-STATUS-CODE TO STATUS-WS                                   
032280     PERFORM IMS-STATUSKONTROLL                                           
032290     .                                                                    
032291     SKIP3                                                                
032300 IMS-GHN-WDD704-MED-GN-PCB SECTION.                                       
032400                                                                          
032500     MOVE 'WDD704  '  TO SSA1                                             
032600     MOVE '  GB' TO GODK-STATUSKODER                                      
032700     CALL CBLTDLI USING GHN WDD71-PCB DLI-IO-AREA SSA1                    
032800     MOVE WDD71-STATUS-CODE TO STATUS-WS                                  
032900     PERFORM IMS-STATUSKONTROLL                                           
033000     .                                                                    
033100     SKIP3                                                                
033200 IMS-REPLACE-WDD704-MED-GN-PCB SECTION.                                   
033300                                                                          
033400     MOVE '  ' TO GODK-STATUSKODER                                        
033500     CALL CBLTDLI USING REPL WDD71-PCB DLI-IO-AREA                        
033600     MOVE WDD71-STATUS-CODE TO STATUS-WS                                  
033700     PERFORM IMS-STATUSKONTROLL                                           
033710     ADD +1 TO W-CHKP-RAKNARE                                             
033800     .                                                                    
033900     SKIP3                                                                
034000 IMS-DELETE-WDD704-MED-GN-PCB SECTION.                                    
034100                                                                          
034200     MOVE '  ' TO GODK-STATUSKODER                                        
034300     CALL CBLTDLI USING DLET WDD71-PCB DLI-IO-AREA                        
034400     MOVE WDD71-STATUS-CODE TO STATUS-WS                                  
034500     PERFORM IMS-STATUSKONTROLL                                           
034510     ADD +1 TO W-CHKP-RAKNARE                                             
034600     .                                                                    
034700     EJECT                                                                
034800 IMS-STATUSKONTROLL SECTION.                                              
034900                                                                          
035000     SET STATUS-IX TO 1                                                   
035100     SEARCH GODK-STATUS  AT END  CALL FELLOG                              
035200     WHEN GODK-STATUS (STATUS-IX) = STATUS-WS                             
035300     CONTINUE                                                             
035400     END-SEARCH                                                           
035500     .                                                                    
035600     EJECT                                                                
035700*    -COPY WY2000P2                                                       
