000100*                  * CONVERTED BY VILMAII *                               
000200*                  * TO PURE COBOLCODE    *                               
000300 ID DIVISION.                                                             
000400 PROGRAM-ID.    W1320400.                                                 
000500*              PROGRAM CONVERTED BY                                       
000600*              COBOL CONVERSION AID PO 5785-ABJ                           
000700*              CONVERSION DATE 05/25/91 17:56:25.                         
000800*DATE-WRITTEN.  FEBR  1977.                                               
000900*AUTHOR.        JAN PETTERSSON.                                           
001000*    REMARKS.                                                             
001100*        INDATA.                                                          
001200*            W13201 INNEHÅLLANDE VECKANS 972-RECORD                       
001300*           WDD1                                                          
001400*        UTDATA                                                           
001500*            W13203 UPPDATERAS MED IDBERED IDANSK KDPRODSL                
001600*        FUNKTION                                                         
001700*            LÄS W13201 OCH UPPDATERA                                     
001800     EJECT                                                                
001900 ENVIRONMENT DIVISION.                                                    
002000 INPUT-OUTPUT SECTION.                                                    
002100 FILE-CONTROL.                                                            
002200     SKIP2                                                                
002300     SELECT  W13201 ASSIGN TO UT-S-W13204D1.                              
002400     SELECT  W13203 ASSIGN TO UT-S-W13204D2.                              
002500     EJECT                                                                
002600 DATA DIVISION.                                                           
002700 FILE SECTION.                                                            
002800     SKIP2                                                                
002900 FD  W13201                                                               
003000     RECORDING F                                                          
003100     BLOCK CONTAINS 0 RECORDS                                             
003200                         .                                                
003300*01  POST-972  -COPY W224972  -L.                                         
003500     SKIP2                                                                
003600 FD  W13203                                                               
003700     RECORDING F                                                          
003800     BLOCK CONTAINS 0 RECORDS                                             
003900                        .                                                 
004000*01  UT-POST  -COPY W224972  -L.                                          
004200                                                                          
004300                                                                          
004400     EJECT                                                                
004500 WORKING-STORAGE SECTION.                                                 
004510                                                                          
004600*    -- CHECKED BY WY2000                                                 
004700 77  INDENT-I PIC X(40) VALUE                                             
004800     'W1320400 91/05/25 TIME 13.08 VILMAII'.                              
004900***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
005000*                                                                         
005100 77  FILSLUT                 PIC X(4)    VALUE SPACE.                     
005200     SKIP2                                                                
005300 01  KONSTANTER.                                                          
005400     03  SLUT                PIC X(4)    VALUE 'SLUT'.                    
005500     SKIP2                                                                
005600 01  SUBPROGRAM.                                                          
005700     03  CBLTDLI             PIC X(8)    VALUE 'CBLTDLI'.                 
005800     03  FELLOG              PIC X(8)    VALUE 'FELLOG '.                 
005900     SKIP2                                                                
006000*01  POST   -COPY W224972  -PRE W-                                        
006200     EJECT                                                                
006300******************************************************************        
006400*****            I M S  - A R E O R                          *****        
006500******************************************************************        
006600 01  FILLER                  PIC X(16)    VALUE 'IMS-AREOR'.              
006700     SKIP3                                                                
006800*    -COPY W0003                                                          
007000     SKIP3                                                                
007100 01  STATUSEN.                                                            
007200     03  STATUS-SW           PIC XX.                                      
007300         88  SEGMENT-FINNS           VALUE '  '.                          
007400         88  SEGMENT-SAKNAS          VALUE 'GE'.                          
007500     SKIP3                                                                
007600     SKIP3                                                                
007700 01  NYCKLAR.                                                             
007800     03  V-IDARTNR-X.                                                     
007900         05  V-IDARTNR       PIC S9(9) COMP-3    VALUE ZERO.              
008000     SKIP3                                                                
008100 01  SSA-ER.                                                              
008200     03  SSA1            PIC X(30).                                       
008300     03  SSA2            PIC X(30).                                       
008400     SKIP3                                                                
008500 01  FILLER.                                                              
008510 03  DLI-IO-AREA             PIC X(900)          VALUE SPACE.             
008600     SKIP3                                                                
008700*03  WLARTC01     -COPY WDK601    -RED DLI-IO-AREA.                       
008900     EJECT                                                                
009000*03  WLARTC11     -COPY WDK611    -RED DLI-IO-AREA.                       
009500     EJECT                                                                
009600 LINKAGE SECTION.                                                         
009700*01  -COPY W0008  -PRE ARTC-.                                             
009900       05 FILLER        PIC X.                                            
010000     EJECT                                                                
010100 PROCEDURE DIVISION USING ARTC-PCB.                                       
010200     ENTRY 'DLITCBL' USING ARTC-PCB                                       
010300     PERFORM A-INITIERING                                                 
010400     PERFORM S01-LES-W13201                                               
010500     PERFORM UNTIL                                                        
010600      NOT ( FILSLUT = SPACE )                                             
010700       MOVE W-IDARTNR TO V-IDARTNR                                        
010800       PERFORM IMS-GET-ARTIKELNR                                          
010900       IF SEGMENT-SAKNAS                                                  
011000         DISPLAY W-IDARTNR 'SAKNAS PÅ WDK6'                               
011100       ELSE                                                               
011200         MOVE ART-KDPRODSL TO W-KDPRODSL                                  
011300         PERFORM IMS-GET-BEREDARNR                                        
011400         IF SEGMENT-FINNS                                                 
011500           MOVE CLAG-IDBERED TO W-IDBERED                                 
011510           MOVE CLAG-IDANSK TO W-IDANSK                                   
011600         ELSE                                                             
011700           MOVE +99 TO W-IDBERED                                          
011710           MOVE +99 TO W-IDANSK                                           
011800         END-IF                                                           
012500         PERFORM S02-SKRIV-W13203                                         
012600       END-IF                                                             
012700       PERFORM S01-LES-W13201                                             
012800     END-PERFORM                                                          
012900     CLOSE W13201  W13203                                                 
013000     MOVE +0 TO RETURN-CODE                                               
013100     GOBACK                                                               
013200     CONTINUE.                                                            
013300     EJECT                                                                
013400 A-INITIERING     SECTION.                                                
013500******************************************************************        
013600*****      ÖPPNAR FILERNA                                   *****         
013700******************************************************************        
013800     OPEN INPUT W13201                                                    
013900          OUTPUT W13203                                                   
014000     CONTINUE.                                                            
014100     EJECT                                                                
014200 IMS-GET-ARTIKELNR SECTION.                                               
014300******************************************************************        
014400*****     LÄSER ARTIKELROTEN PÅ WDK6                        ******        
014500******************************************************************        
014600     STRING 'WLARTC01(IDARTNR  =' V-IDARTNR-X ')'                         
014700                       DELIMITED BY SIZE INTO SSA1                        
014800     CALL CBLTDLI USING GU ARTC-PCB DLI-IO-AREA SSA1                      
014900     IF  ARTC-STATUS-CODE = '  ' OR 'GE'                                  
015000       MOVE ARTC-STATUS-CODE TO STATUS-SW                                 
015100     ELSE                                                                 
015200       CALL FELLOG                                                        
015300     END-IF                                                               
015400     CONTINUE.                                                            
015500     SKIP3                                                                
015600 IMS-GET-BEREDARNR SECTION.                                               
015700******************************************************************        
015800*****     HÄMTAR BEREDARE/ANSKAFFARE FRÅN WDK6              ******        
015900******************************************************************        
016000     MOVE 'WLARTC11' TO SSA1                                              
016100     CALL CBLTDLI USING GNP ARTC-PCB DLI-IO-AREA SSA1                     
016200     IF ARTC-STATUS-CODE = '  ' OR 'GE'                                   
016300       MOVE ARTC-STATUS-CODE TO STATUS-SW                                 
016400     ELSE                                                                 
016500       CALL FELLOG                                                        
016600     END-IF                                                               
016700     CONTINUE.                                                            
018100     EJECT                                                                
018200 S01-LES-W13201      SECTION.                                             
018300******************************************************************        
018400*****       LÄSER INPUT FILEN                               ******        
018500******************************************************************        
018600     READ W13201 INTO W-POST                                              
018700                 AT END MOVE SLUT TO FILSLUT                              
018800     END-READ                                                             
018900     CONTINUE.                                                            
019000     EJECT                                                                
019100 S02-SKRIV-W13203 SECTION.                                                
019200*****************************************************************         
019300*****     SKRIVER W13203 EFTER KOMPLETTERING MED IDBERED,  ******         
019400*****     IDANSK OCH KDPRODSL                              ******         
019500*****************************************************************         
019600     WRITE UT-POST FROM W-POST                                            
019700     CONTINUE.                                                            
