000100 ID DIVISION.                                                             
000200 PROGRAM-ID.                 W2213000.                                    
000300*AUTHOR.                     IDK,GÖTEBORG.                                
000400*DATE-WRITTEN.               JANUARI  1979.                               
000500                                                                          
000600*REMARKS.                                                                 
000700                                                                          
000800*    FUNKTION.                                                            
000900*        PROGRAMMMET TÖMMER HÄNDELSEREGISTRET XXJB (WDG3),                
001000*        DVS LÄSER OCH DELETAR XXJB11 M.A.P KOD 2204                      
001100                                                                          
001200*    SUBPROGRAM.                                                          
001300*        W2213010    SUBPROGRAM SOM SKÖTER SAMTLIGA IMS-CALL              
001400*                    MOT HÄNDELSEREGISTRET.                               
001410* CHANGE LOG:                                                             
001420* 2015-04-22   E'TRACKER 10130993                                         
001430*              REDUCE NUMBER OF DELIVERY SCHEDULES                        
001440*                                                                         
001500     EJECT                                                                
001600 ENVIRONMENT DIVISION.                                                    
001700 INPUT-OUTPUT SECTION.                                                    
001800 FILE-CONTROL.                                                            
001900     SKIP2                                                                
002000*--------------------------------------- TRANSAKTIONER                    
002100     SELECT W22131            ASSIGN UT-S-W22130D1.                       
002200*                                                                         
002300*--------------------------------------- SORTERINGSFIL                    
002400*                                                                         
002500     SELECT SRT-FILE          ASSIGN UT-S-W22130DS.                       
002600     EJECT                                                                
002700 DATA DIVISION.                                                           
002800 FILE SECTION.                                                            
002900     SKIP2                                                                
003000 FD  W22131                                                               
003100     RECORDING F                                                          
003200     BLOCK 0.                                                             
003300                                                                          
003400*01  POST -COPY W2212204C0 -PRE U31- -L.                                  
003500     SKIP3                                                                
003600 SD  SRT-FILE.                                                            
003700                                                                          
003800*01  POST  -COPY W2212204C0  -PRE SRT-                                    
003900     EJECT                                                                
004000 WORKING-STORAGE SECTION.                                                 
004100                                                                          
004200*    -- CHECKED BY WY2000                                                 
004300 77  INDENT-I PIC X(40) VALUE                                             
004400     'W2213000 91/05/25 TIME 12.46 VILMAII'.                              
004500***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
004600*                                                                         
004700     SKIP3                                                                
004800 01  W.                                                                   
004900     05  W-IDARTNR               PIC S9(9)           COMP-3.              
005000     05  W-KDLPORS               PIC S9(3)           COMP-3.              
005100     SKIP1                                                                
005200 01  RKOD                    PIC S9(4)               COMP SYNC.           
005300     SKIP2                                                                
005400 01  SWITCHAR.                                                            
005500     05  SW-SRT-FILE-EOF     PIC X       VALUE 'N'.                       
005600                                                                          
005700 01  KONSTANTER.                                                          
005800     05  JA                  PIC X       VALUE 'J'.                       
005900     05  NEJ                 PIC X       VALUE 'N'.                       
006000     05  PROGRAM-NAMN        PIC X(6)    VALUE 'W22130'.                  
006100     05  LAES-ROT            PIC S9(3)   VALUE +101  COMP-3.              
006200     05  LAES-DELETE-SEGM2   PIC S9(3)   VALUE +102  COMP-3.              
006300     SKIP2                                                                
006400 01  DYNAMISKA-SUBPROGRAM.                                                
006500     05  POSTSUM             PIC X(8)    VALUE 'POSTSUM '.                
006600     05  ABEND               PIC X(8)    VALUE 'ABEND   '.                
006700     05  W2213010            PIC X(8)    VALUE 'W2213010'.                
006800     EJECT                                                                
006900*--------------------------------------- PARAMETRAR TILL POSTSUM          
007000*                                                                         
007100*01  -COPY W0005  -PRE POSTSUM-                                           
007200     EJECT                                                                
007300*--------------------------------------- AREA FÖR W22131-POST             
007400*                                                                         
007500                                                                          
007600*01  AREA -COPY W2212204C0 -PRE U31-                                      
007700     EJECT                                                                
007800*--------------------------------------- LÄNKAREA FÖR CALL MOT            
007900*                                        HÄNDELSEREGISTRET                
008000                                                                          
008100*01   -COPY W221L301C0 -PRE IMSWDG3-                                      
008200     EJECT                                                                
008300 LINKAGE SECTION.                                                         
008400     SKIP2                                                                
008500*01  -COPY W0008  -PRE  XXJB-                                             
008600     05  FILLER             PIC X.                                        
008700     EJECT                                                                
008800 PROCEDURE DIVISION USING XXJB-PCB.                                       
008900     ENTRY 'DLITCBL' USING XXJB-PCB.                                      
009000     SKIP2                                                                
009100     PERFORM A-INITIERING                                                 
009200     SKIP1                                                                
009300     SORT SRT-FILE                                                        
009400          ASCENDING SRT-IDARTNR                                           
009500                    SRT-KDLPORS                                           
009600          INPUT PROCEDURE B-LAES-WDG3                                     
009700          OUTPUT PROCEDURE C-SKRIV-UTFIL                                  
009800     SKIP1                                                                
009900     IF  SORT-RETURN > ZERO                                               
010000       DISPLAY '*** W22130, FEL I SORTERING'                              
010100       MOVE +20 TO RKOD                                                   
010200       CALL ABEND USING RKOD                                              
010300     ELSE                                                                 
010400       SKIP1                                                              
010500       PERFORM Z-AVSLUTNING                                               
010600       MOVE ZERO TO RETURN-CODE                                           
010700       GOBACK                                                             
010800     END-IF                                                               
010900     CONTINUE.                                                            
011000     EJECT                                                                
011100******************************************************************        
011200*                                                                *        
011300*    INITIERING                                                  *        
011400*    ÖPPNA ALLA FILER                                            *        
011500*                                                                *        
011600******************************************************************        
011700                                                                          
011800 A-INITIERING SECTION.                                                    
011900                                                                          
012000     OPEN OUTPUT W22131                                                   
012100     SKIP1                                                                
012200     MOVE ZERO TO W-IDARTNR                                               
012300                  W-KDLPORS                                               
012400     SKIP1                                                                
012500     MOVE PROGRAM-NAMN TO POSTSUM-PROGNAMN                                
012600     CONTINUE.                                                            
012700     EJECT                                                                
012800 B-LAES-WDG3 SECTION.                                                     
012900**************************************************************            
013000*    HÄMTAR POSTER FRÅN WDG3                                 *            
013100**************************************************************            
013200     SKIP2                                                                
013300     MOVE LAES-ROT TO IMSWDG3-KDCALL                                      
013400     MOVE '2203' TO IMSWDG3-IDHTYP                                        
013500     CALL W2213010 USING IMSWDG3-W221L301 XXJB-PCB                        
013600     SKIP1                                                                
013700     IF  IMSWDG3-ANROP-OK                                                 
013800       MOVE LAES-DELETE-SEGM2 TO IMSWDG3-KDCALL                           
013900       CALL W2213010 USING IMSWDG3-W221L301 XXJB-PCB                      
014000       SKIP1                                                              
014100       PERFORM UNTIL                                                      
014200        NOT ( IMSWDG3-ANROP-OK )                                          
014300        IF IMSWDG3-IDARTNR NUMERIC                                        
014400         MOVE IMSWDG3-IDHTYP TO SRT-IDHTYP                                
014500         MOVE IMSWDG3-IDARTNR TO SRT-IDARTNR                              
014900         MOVE IMSWDG3-KDLPORS TO SRT-KDLPORS                              
015100         RELEASE SRT-POST                                                 
015200        END-IF                                                            
015300         CALL W2213010 USING IMSWDG3-W221L301 XXJB-PCB                    
015400       END-PERFORM                                                        
015500     END-IF                                                               
015600     CONTINUE.                                                            
015700     EJECT                                                                
015800******************************************************************        
015900*                                                                *        
016000*    TAR BORT DUBLETTER OCH SKRIVER UTFIL                        *        
016100*                                                                *        
016200******************************************************************        
016300                                                                          
016400 C-SKRIV-UTFIL SECTION.                                                   
016500     SKIP2                                                                
016600     PERFORM CA-LAES-SRT-FILE                                             
016700     SKIP1                                                                
016800     PERFORM UNTIL                                                        
016900      NOT ( SW-SRT-FILE-EOF = NEJ )                                       
017000       IF  W-IDARTNR NOT = U31-IDARTNR                                    
017100       OR  W-KDLPORS NOT = U31-KDLPORS                                    
017200         MOVE U31-IDARTNR TO W-IDARTNR                                    
017300         MOVE U31-KDLPORS TO W-KDLPORS                                    
017400         WRITE U31-POST FROM U31-AREA                                     
017500         MOVE 'W22131' TO POSTSUM-FDNAMN                                  
017600         MOVE 'W22130D1' TO POSTSUM-DDNAMN2                               
017700         MOVE '2204' TO POSTSUM-TRANSTYP                                  
017800         CALL POSTSUM USING POSTSUM-PARM                                  
017900       END-IF                                                             
018000       PERFORM CA-LAES-SRT-FILE                                           
018100     END-PERFORM                                                          
018200     CONTINUE.                                                            
018300     EJECT                                                                
018400 CA-LAES-SRT-FILE SECTION.                                                
018500****************************************************************          
018600*    LÄSER POSTER PÅ SORTERINGSFILEN                           *          
018700****************************************************************          
018800     SKIP2                                                                
018900     RETURN SRT-FILE INTO U31-AREA                                        
019000       AT END MOVE JA TO SW-SRT-FILE-EOF                                  
019100     END-RETURN                                                           
019200     CONTINUE.                                                            
019300     SKIP3                                                                
019400******************************************************************        
019500*                                                                *        
019600*    AVSLUTNING                                                  *        
019700*    STÄNG ALLA FILER                                            *        
019800*    SKRIV UT POSTSUMS RÄKNEVERK                                 *        
019900*                                                                *        
020000******************************************************************        
020100                                                                          
020200 Z-AVSLUTNING SECTION.                                                    
020300                                                                          
020400     CLOSE W22131                                                         
020500                                                                          
020600     MOVE 'S' TO POSTSUM-OPKOD                                            
020700     CALL POSTSUM USING POSTSUM-PARM                                      
020800     CONTINUE.                                                            
