000100 ID DIVISION.                                                             
000200 PROGRAM-ID.                 W2214610.                                    
000300*AUTHOR.                     IDK INGVAR CARLSSON.                         
000400*DATE-WRITTEN.               FEBRUARI 1979.                               
000500*    SKIP2                                                                
000600*    REMARKS.                                                             
000700*                                                                         
000800*    FUNKTION.                                                            
000900*                                                                         
001000*        PROGRAMMET ÄR ETT SUBPROGRAM TILL W2214600.                      
001100*        SUBPROGRAMMET SKÖTER OM SAMTLIGA IMS-CALL MOT:                   
001200*                                                                         
001300*           ARTIKELREGISTRET                     (LOGISKT WLARTC)         
001700*           CROSS-INDEXREGISTRET                 WDF5                     
002000*           LEVERANSPLANEREGISTRET-                                       
002100*               -SATSSTRUKTUREN                  (LOGISKT WLINLB)         
002200*           ARTIKELREGISTRET                     (LOGISKT WLARTM)         
002210*           ARTIKEL BENÄMNING                    (LOGISKT WLBENA)         
002300*           CLAGERREGISTER                       WDB6                     
002310*           ARTIKELINFO SLAGER                   WDK7                     
002400*    ÄNDRAD FUNKTION:                                                     
002500*        ETRACKER 4820410. DO NOT INCLUDE OVERSTOCK AT MICRO-LDC          
002600*        TILLKOMMER WDB601-LÄSNING.                                       
002700*    SKIP3                                                                
002800 ENVIRONMENT DIVISION.                                                    
002900     SKIP3                                                                
003000 DATA DIVISION.                                                           
003100     EJECT                                                                
003200 WORKING-STORAGE SECTION.                                                 
003300*    -COPY WY2000W1                                                       
003400     SKIP3                                                                
003500*    -COPY WY2000W9                                                       
003600     SKIP3                                                                
003700 77  INDENT-I PIC X(40) VALUE                                             
003800     'W2214610 91/05/25 TIME 10.20 VILMAII'.                              
003900***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
004000*                                                                         
004100     SKIP2                                                                
004200 01  RKOD                    PIC S9(4)  VALUE +0     COMP SYNC.           
004210*    -COPY WWDCKONS                                                       
004300                                                                          
004400 01  FELTEXT.                                                             
004500     03  FILLER              PIC X(8)    VALUE 'FELTEXT'.                 
004600     03  FELTEXT-STR         PIC X(72)   VALUE SPACE.                     
004700                                                                          
004800 77  WS-DAGENS-AAMMDD        PIC 9(7)  VALUE ZERO.                        
004900 77  SW-TRAEFF               PIC X(1)   VALUE SPACE.                      
005000 77  W-SUTPO-TOT             PIC S9(7)  VALUE ZERO   COMP-3.              
005100 01  ARB-SDC.                                                             
005200     03  W-TILLG-SDC         PIC S9(7)               COMP-3.              
005300     03  W-OVERLAGER-SDC     PIC S9(7)               COMP-3.              
005400     03  WS-FLOVRLAGBER      PIC X     VALUE SPACE.                       
005500     03  WS-DCS-KDDC         PIC XX    VALUE SPACE.                       
006000 01  ARBETSAREOR.                                                         
006100     03  DAGENS-AAVV         PIC 9(4)     VALUE ZERO.                     
006200     03  FILLER REDEFINES DAGENS-AAVV.                                    
006300         05  DAGENS-AA       PIC 9(2).                                    
006400         05  DAGENS-VV       PIC 9(2).                                    
006500     03  TIFINLV-AAVVD       PIC 9(5)     VALUE ZERO.                     
006600     03  FILLER REDEFINES TIFINLV-AAVVD.                                  
006700         05  TIFINLV-AA      PIC 9(2).                                    
006800         05  TIFINLV-VV      PIC 9(2).                                    
006900         05  FILLER          PIC 9(1).                                    
007000     03  VECKO-DIFF          PIC S9(3)    COMP-3.                         
007100     03  WS-KVOI-PROG        PIC S9(9)    COMP-3.                         
007200     03  WS-KVOI-DC          PIC S9(9)    COMP-3.                         
007300     03  WS-KVOI-DIV         PIC S9(9)    COMP-3.                         
007400     03  WS-KVOI-SATS        PIC S9(9)    COMP-3.                         
007500     03  W-START-TIAA        PIC S9(3)    COMP-3.                         
007600     03  WS-AAPP             PIC 9(4)    VALUE ZERO.                      
007700     03  FILLER REDEFINES    WS-AAPP.                                     
007800         05 WS-AA            PIC 9(2).                                    
007900         05 WS-PP            PIC 9(2).                                    
008000     03  IX-PP               PIC S9(9)               COMP SYNC.           
008100 01  WS-TIAAAAPP             PIC 9(6).                                    
008200 01  FILLER REDEFINES WS-TIAAAAPP.                                        
008300     03  FILLER                  PIC  9(2).                               
008400     03  WS-TIAAPP               PIC  9(4).                               
008500     03  WS-TIAAPP-RED           REDEFINES WS-TIAAPP.                     
008600         05 WS-TIAAPP-AAR        PIC  99.                                 
008700         05 WS-TIAAPP-PERIOD     PIC 99.                                  
008800 01  FILLER REDEFINES WS-TIAAAAPP.                                        
008900     03  WS-TIAAAA               PIC 9(4).                                
009000     03  FILLER                  PIC 99.                                  
009100       EJECT                                                              
009200                                                                          
009300 01  WS-TISEKEL-AA.                                                       
009400     03  WS-DAGENS-SEKEL     PIC 99.                                      
009500     03  WS-DAGENS-AA        PIC 99.                                      
009600 01  FILLER REDEFINES WS-TISEKEL-AA.                                      
009700     03  WS-DAGENS-TIAAAA    PIC 9(4).                                    
009800 01  WS-INLAST-TIAAAA        PIC 9(4).                                    
009900 01  FILLER  REDEFINES WS-INLAST-TIAAAA.                                  
010000     03  FILLER              PIC 9(2).                                    
010100     03  WS-INLAST-AA        PIC 9(2).                                    
010200 01  DAGENS-PERIOD           PIC 99.                                      
010300                                                                          
010400 01  SENASTE-AAR-PERIOD-X.                                                
010500   03  SENASTE-TIAAPP-AAR    PIC 99.                                      
010600   03  SENASTE-TIAAPP-PERIOD PIC 99.                                      
010700 01  SENASTE-AAR-PERIOD REDEFINES SENASTE-AAR-PERIOD-X PIC 9(4).          
012000*--------------------------------------- NYCKLAR                          
012600 01  W-IDARTNR-X.                                                         
012700     05  W-IDARTNR           PIC S9(9)               COMP-3.              
013710 01  W-WDD901KY-X.                                                        
013720     05  W-IDARTNR-D9        PIC S9(9)               COMP-3.              
013730     05  W-IDDC-D9           PIC X(2).                                    
013800 01  W-IDLEVNR-X.                                                         
013900     05  W-IDLEVNR           PIC X(5).                                    
014200 01  W-KDERS-0-X.                                                         
014300     05  W-KDERS-0           PIC S9(3)   VALUE ZERO  COMP-3.              
014400 01  W-IDSKYLT-X.                                                         
014500     05  W-IDSKYLT           PIC  X(3)   VALUE 'S  '.                     
015600                                                                          
015700     SKIP3                                                                
015800*--------------------------------------- INDEXFÄLT                        
015900 01  INDEXFALT.                                                           
016000     05  IX                  PIC S9(9)               COMP SYNC.           
016100     05  IXCL                PIC S9(9)               COMP SYNC.           
016300     05  IXDO                PIC S9(9)               COMP SYNC.           
016700     SKIP3                                                                
016800*--------------------------------------- SWITCHAR                         
016900 01  SWITCHAR.                                                            
017000     05  SW-INLB01-FINNS     PIC X       VALUE 'N'.                       
017600     SKIP3                                                                
017700*--------------------------------------- KONSTANTER                       
017800 01  KONSTANTER.                                                          
017900     05  JA                  PIC X       VALUE 'J'.                       
018000     05  NEJ                 PIC X       VALUE 'N'.                       
018100     05  LAS-ALLMAN-INFO     PIC S9(3)   VALUE +461  COMP-3.              
018200     05  LAS-BESTREST        PIC S9(3)   VALUE +469  COMP-3.              
019000     05  LAS-LEV-INFO        PIC S9(3)   VALUE +470  COMP-3.              
019100     05  LAS-TPO-ORDER       PIC S9(3)   VALUE +471  COMP-3.              
019400     05  LAES-WDB6-DC-INFO   PIC S9(3)   VALUE +475  COMP-3.              
019500     SKIP3                                                                
019600*--------------------------------------- DYNAMISKA SUBPROGRAM             
019700 01  DYNAMISKA-SUBPROGRAM.                                                
019800     05  WDATKONV            PIC X(8)    VALUE 'WDATKONV'.                
019900     05  CBLTDLI             PIC X(8)    VALUE 'CBLTDLI'.                 
020000     05  FELLOG              PIC X(8)    VALUE 'FELLOG '.                 
020100     05  ABEND               PIC X(8)    VALUE 'ABEND  '.                 
020110     03  WINTSOR             PIC X(8)    VALUE 'WINTSOR'.                 
020200     EJECT                                                                
020300*01      -COPY WDATAREA.                                                  
020400     EJECT                                                                
020500 01  PERIODINDELNING.                                                     
020600     03  PERIOD-TAB          OCCURS 12.                                   
020700         05  PER-NR          PIC 9(2).                                    
020800         05  PER-VECKA-FOM   PIC 9(2).                                    
020900         05  PER-VECKA-TOM   PIC 9(2).                                    
021000         05  PER-ANT-VECKOR  PIC 9(2).                                    
021100     EJECT                                                                
021200                                                                          
021300 01  FILLER              PIC X(16)   VALUE 'IDDC-TABELL'.                 
021400*- - - - - - - - - - - - - TABELL MED ALLA IDDC PÅ WDB601                 
021410*- - - - - - - - - - - - - OCCURS-MAX SÄTTS TILL VERKLIGT ANTAL           
021420*- - - - - - - - - - - - - I N- SEKTIONEN.                                
021421 01  IDDC-INDEX-WS.                                                       
021430     03 DC-MAX           PIC S9(3)   VALUE +100 COMP SYNC.                
021440                                                                          
021460     03 DCS-TRAEFF       PIC X       VALUE 'J'.                           
021470                                                                          
021500 01  IDDC-TABELL.                                                         
021700     03 DC-TAB  OCCURS 1 TO 100 DEPENDING ON DC-MAX                       
021800                INDEXED BY DCIX.                                          
021900        05 T-DCS.                                                         
022000          07 T-DCS-IDDC           PIC X(2).                               
022010          07 T-DCS-KDDC           PIC X(2).                               
022020          07 T-DCS-FLOVRLAGBER    PIC X.                                  
022100                                                                          
022101                                                                          
022102 01  FILLER              PIC X(16)   VALUE 'DC-TABELL-SORT'.              
022110*    --- PARAMETRAR TILL SUBPROGRAM WINTSOR                               
022120 01  TABENTRY-PARM.                                                       
022130     03  STEGLANGD               PIC S9(9) COMP.                          
022140     03  ANTAL                   PIC S9(9) COMP.                          
022150     03  NYCKELLANGD             PIC S9(9) COMP  VALUE 9.                 
022160                                                                          
022300                                                                          
022400                                                                          
022500 01  IMS-WS.                                                              
022600     05  FILLER              PIC X(8)    VALUE 'IMS-WS'.                  
022700     SKIP2                                                                
022800*--------------------------------------- STATUSKOD FRÅN IMS               
022900     05  STATUS-WS           PIC X(2).                                    
023000       88  SEGMENT-FINNS                 VALUE '  '.                      
023100       88  SEGMENT-SAKNAS                VALUE 'GE'.                      
023110       88  SEGMENT-SLUT                  VALUE 'GB'.                      
023200     SKIP2                                                                
023300     05  SSA1                PIC X(128).                                  
023400     05  SSA2                PIC X(32).                                   
023500     05  SSA3                PIC X(32).                                   
023600     05  SSA4                PIC X(32).                                   
023700     SKIP2                                                                
023800     05  GODK-STATUSKODER.                                                
023900         10  GODK-STATUS     OCCURS 10                                    
024000                             INDEXED BY STATUS-IX                         
024100                             PIC X(2).                                    
024200     EJECT                                                                
024300*01  -COPY W0003                                                          
024400     EJECT                                                                
024500 01  DLI-IO-AREA-01          PIC X(110)  VALUE SPACE.                     
024600     SKIP2                                                                
024700*01  WLARTC01  -COPY WDK601  -RED DLI-IO-AREA-01                          
024800     EJECT                                                                
024900 01  DLI-IO-AREA-11          PIC X(900)  VALUE SPACE.                     
025000     SKIP2                                                                
025100*01  WLARTC11  -COPY WDK611  -RED DLI-IO-AREA-11                          
025200     EJECT                                                                
025300 01  DLI-IO-AREA             PIC X(2500)  VALUE SPACE.                    
025400     SKIP2                                                                
025700*01  WLARTC25  -COPY WDK625  -RED DLI-IO-AREA                             
025800     EJECT                                                                
025900*01  WLINLB11  -COPY WDD902  -PRE BALEV-   -RED DLI-IO-AREA               
026000     EJECT                                                                
026300*01  WLINLB22  -COPY WDD904  -PRE BAOMSP-  -RED DLI-IO-AREA               
026400     EJECT                                                                
026500*01  WLINLB23  -COPY WDD905  -PRE BAAVROP- -RED DLI-IO-AREA               
026600     EJECT                                                                
028100*01  WDF501    -COPY WDF501  -RED DLI-IO-AREA                             
028200     EJECT                                                                
028300*01  WDF502    -COPY WDF502  -RED DLI-IO-AREA                             
028400     EJECT                                                                
029300*01  WLBENA11  -COPY WDD311  -PRE  BENA11- -RED DLI-IO-AREA               
029400     EJECT                                                                
029500*01  WDK701 -COPY WDK701     -RED DLI-IO-AREA                             
029600     EJECT                                                                
029700*01  WDK711 -COPY WDK711     -RED DLI-IO-AREA                             
029800     EJECT                                                                
029900 01  DLI-IO-AREA2            PIC X(200)  VALUE SPACE.                     
030000*01  WLARTM01  -COPY WDK901  -PRE  ARTM-   -RED DLI-IO-AREA2              
030100     EJECT                                                                
030200*01  WLARTM11  -COPY WDK911  -PRE  ARTM-   -RED DLI-IO-AREA2              
030300     EJECT                                                                
031100                                                                          
031200 01  FILLER               PIC X(16)   VALUE 'WDB601 AREA'.                
031300 01   DLI-IO-AREA-B601.                                                   
031400*     03  -COPY WDB601                                                    
031500                                                                          
031600 LINKAGE SECTION.                                                         
031700 01  LINK-AREA               PIC X(600).                                  
031800     SKIP2                                                                
031900*01  AREA  -COPY W221L461    -PRE LINK1-   -RED LINK-AREA                 
032000     EJECT                                                                
032100*01  AREA  -COPY W221L469C0  -PRE LINK9-  -RED LINK-AREA                  
032200     EJECT                                                                
033700*01  AREA  -COPY W221L470C0  -PRE LINK10- -RED LINK-AREA                  
033800     EJECT                                                                
033900*01  AREA  -COPY W221L471C0  -PRE LINK11- -RED LINK-AREA                  
034000     EJECT                                                                
036000*01  -COPY   W0008  -PRE WDF5-                                            
036100     05  FILLER                          PIC X.                           
036200     EJECT                                                                
036600*01  -COPY   W0008  -PRE WLARTC2-                                         
036700     05  FILLER                          PIC X.                           
036800     EJECT                                                                
036900*01  -COPY   W0008  -PRE WLINLB-                                          
037000     05  FILLER                          PIC X.                           
037100     EJECT                                                                
037500*01  -COPY   W0008  -PRE WLBENA-                                          
037600     05  FILLER                          PIC X.                           
037700     EJECT                                                                
037800*01  -COPY   W0008  -PRE WLARTM-                                          
037900     05  FILLER                          PIC X.                           
038000     EJECT                                                                
038400*01  -COPY   W0008  -PRE WDK7-                                            
038500     05  FILLER                          PIC X.                           
038600     EJECT                                                                
038700*01  -COPY   W0008  -PRE WDB6-                                            
038800     05  FILLER                          PIC X.                           
038900     EJECT                                                                
039000 PROCEDURE DIVISION USING LINK-AREA                                       
039200              WDF5-PCB WLARTC2-PCB                                        
039300              WLINLB-PCB WLBENA-PCB WLARTM-PCB                            
039400              WDK7-PCB   WDB6-PCB.                                        
039500                                                                          
039800     EVALUATE LINK1-KDCALL                                                
039900     WHEN LAS-ALLMAN-INFO                                                 
040000       PERFORM A-LAS-ALLMAN-INFO                                          
040100     WHEN LAS-BESTREST                                                    
040200       PERFORM C-LAS-BESTREST                                             
041700     WHEN LAS-LEV-INFO                                                    
041800       PERFORM J-LAS-LEV-INFO                                             
041900     WHEN LAS-TPO-ORDER                                                   
042000       PERFORM K-LAS-TPO-ORDER                                            
042500     WHEN LAES-WDB6-DC-INFO                                               
042600       PERFORM N-LAES-WDB6-DC-INFO                                        
042700     WHEN OTHER                                                           
042800       MOVE NEJ TO LINK1-FLJANEJ-ANROP                                    
042900     END-EVALUATE                                                         
043000     MOVE ZERO TO RETURN-CODE                                             
043100     GOBACK                                                               
043200     .                                                                    
043300     EJECT                                                                
047700******************************************************************        
047800*                                                                *        
047900*    HÄMTAR INFORMATION FRÅN ARTREG                              *        
048000*    OM ARTIKELN SAKNAS SÄTTS FLJANEJ-ANROP TILL NEJ             *        
048100*    POSITIONERAR SIG PÅ LEVERANSPLANREG                         *        
048200*                                                                *        
048300******************************************************************        
048400                                                                          
048500 A-LAS-ALLMAN-INFO SECTION.                                               
048600                                                                          
048700     MOVE LINK1-IDARTNR TO W-IDARTNR                                      
048710                           W-IDARTNR-D9                                   
048720     MOVE WC-CDC-SE     TO W-IDDC-D9                                      
048800     MOVE LOW-VALUE     TO LINK1-IOAREA                                   
048900     MOVE NEJ           TO LINK1-FLJANEJ-ANROP                            
049000                                                                          
049100     PERFORM IMS-GET-INLB01                                               
049200     IF SEGMENT-FINNS                                                     
049300        MOVE JA         TO SW-INLB01-FINNS                                
049400     ELSE                                                                 
049500        MOVE NEJ        TO SW-INLB01-FINNS                                
049600     END-IF                                                               
049700                                                                          
049800     PERFORM IMS-GET-ARTC2-ART                                            
049900                                                                          
050000     IF SEGMENT-FINNS                                                     
050100       MOVE JA          TO LINK1-FLJANEJ-ANROP                            
050200       PERFORM AA-INITIERA-LINK1-AREA                                     
050300       PERFORM AB-LAS-INFO-ARTC                                           
050400       PERFORM AC-LAS-INFO-WDK7                                           
050500       PERFORM AD-LAS-INFO-AK                                             
050600       PERFORM AE-LAS-BENA11-BSEQ                                         
050700     END-IF                                                               
050800     CONTINUE.                                                            
050900     EJECT                                                                
051000******************************************************************        
051100*                                                                *        
051200*    INITIERA LINK1 AREA                                         *        
051300*                                                                *        
051400******************************************************************        
051500                                                                          
051600 AA-INITIERA-LINK1-AREA SECTION.                                          
051700                                                                          
051800     MOVE SPACE TO LINK1-IOAREA                                           
051900     MOVE 1 TO IXCL                                                       
052000     PERFORM UNTIL IXCL > 2                                               
052100                                                                          
052500       MOVE ZERO          TO LINK1-KVLS   (IXCL)                          
052600                             LINK1-KVRESS (IXCL)                          
052700                             LINK1-KVAKS  (IXCL)                          
052800                             LINK1-KVROS  (IXCL)                          
055200       MOVE ZERO          TO LINK1-KDERS  (IXCL)                          
055500       ADD +1             TO IXCL                                         
055600     END-PERFORM                                                          
056800     CONTINUE.                                                            
056900     EJECT                                                                
057000******************************************************************        
057100*                                                                *        
057200*    LAS INFO BA                                                 *        
057300*    HÄMTA INFORMATION FRÅN ARTIKELREGISTRET, LEVERANSPLANE-     *        
057400*    REGISTRET OCH CROSSINDEXREGISTRET                           *        
057500*                                                                *        
057600******************************************************************        
057700                                                                          
057800 AB-LAS-INFO-ARTC SECTION.                                                
057900                                                                          
058000*--------------------------------------- ARTIKEL-INFO                     
058300     MOVE ART-IDLEVNR  TO LINK1-IDLEVNR                                   
058700                                                                          
058800*--------------------------------------- BEREDN.-PROD.ENHETER             
058900     PERFORM IMS-GET-ARTC2-CLAG                                           
059000     IF SEGMENT-FINNS                                                     
059700       MOVE CLAG-IDANSK         TO LINK1-IDANSK                           
064400                                                                          
064500*--------------------------------------- MATERIALFÖRSÖRJNINGS-INFO        
064600*                                        CLAGERBEROENDE                   
068400       PERFORM IMS-GET-NOT-F                                              
068500       PERFORM UNTIL                                                      
068600        NOT ( SEGMENT-FINNS AND NOT-KDNOTTYP NOT > 2 )                    
068700         MOVE NOT-TEARTNOT      TO LINK1-TEARTNOT (NOT-KDNOTTYP)          
068800         PERFORM IMS-GET-NOT                                              
068900       END-PERFORM                                                        
069200                                                                          
070500*--------------------------------------- GEMENSAM-INFO                    
070600*                                        CLAGERBEROENDE                   
070610       MOVE +1                TO IXCL                                     
070700       MOVE CLAG-KVLS         TO LINK1-KVLS   (IXCL)                      
070800       MOVE CLAG-KVRESS       TO LINK1-KVRESS (IXCL)                      
070900       MOVE CLAG-KVAKS-CDC    TO LINK1-KVAKS  (IXCL)                      
071000       ADD  CLAG-KVAKS-PAV    TO LINK1-KVAKS  (IXCL)                      
071100       ADD  CLAG-KVAKS-T      TO LINK1-KVAKS  (IXCL)                      
071200       MOVE CLAG-KVROS        TO LINK1-KVROS  (IXCL)                      
071600       MOVE CLAG-KDERS        TO LINK1-KDERS  (IXCL)                      
071700     END-IF                                                               
071800     CONTINUE.                                                            
071900     EJECT                                                                
072000******************************************************************        
072100*                                                                *        
072200*    LAS INFO WDK7.   BERÄKNAR ÖVERLAGER PÅ SDC                  *        
072300*    HÄMTAR INFORMATION FRÅN SDC-REGISTRET                       *        
072400*                                                                *        
072500******************************************************************        
072600                                                                          
072700 AC-LAS-INFO-WDK7 SECTION.                                                
072800                                                                          
072900     MOVE ZERO              TO                                            
073000                                 W-TILLG-SDC                              
073100                                 W-OVERLAGER-SDC                          
073200                                                                          
073300     PERFORM IMS-GET-WDK701-SDC                                           
073400                                                                          
073500     IF SEGMENT-FINNS                                                     
073600        PERFORM IMS-GNP-WDK711-SDC                                        
073700        PERFORM UNTIL SEGMENT-SAKNAS                                      
073800           MOVE ZERO           TO   W-TILLG-SDC                           
073900           ADD SLAG-KVLS       TO   W-TILLG-SDC                           
074000           ADD SLAG-KVBEART    TO   W-TILLG-SDC                           
074100           ADD SLAG-KVAKS-SDC  TO   W-TILLG-SDC                           
074200           ADD SLAG-KVAKS-PAV  TO   W-TILLG-SDC                           
074300           SUBTRACT SLAG-KVOKS-BULK FROM W-TILLG-SDC                      
074400           SUBTRACT SLAG-KVOKS-DAG  FROM W-TILLG-SDC                      
074800           SET DCIX TO +1                                                 
074900           SEARCH DC-TAB                                                  
074910              AT END                                                      
074920                 MOVE NEJ TO DCS-TRAEFF                                   
074930              WHEN T-DCS-IDDC (DCIX) = SLAG-IDDC                          
074940                 MOVE JA    TO DCS-TRAEFF                                 
074950                 CONTINUE                                                 
075300           END-SEARCH                                                     
075400                                                                          
075500           IF T-DCS-KDDC(DCIX)(1:1) = 'N'                                 
075600*             --- HOPPA ÖVER NDC-LAGER (POS 1 = N)                        
075700              CONTINUE                                                    
075800           ELSE                                                           
075900*            -- KOLLA SDC-LAGER (POS 1 = S)                               
076000             IF T-DCS-KDDC(DCIX)(1:1) = 'S'                               
076100*              -- KOLLA OM ÖVERLAGERBERÄKNING PÅ SDC SKA GÖRAS            
076200               IF T-DCS-FLOVRLAGBER(DCIX) = NEJ                           
076300                 CONTINUE                                                 
076400               ELSE                                                       
076500                 IF SLAG-KVREFOVL < W-TILLG-SDC                           
076600                   COMPUTE W-OVERLAGER-SDC = W-OVERLAGER-SDC              
076700                                       + W-TILLG-SDC                      
076800                                       - SLAG-KVREFOVL                    
076900                 END-IF                                                   
077000               END-IF                                                     
077010             ELSE                                                         
077020*              -- SDC ÄR EJ REGISTRERAT PÅ WDB6. HOPPA !                  
077030*              -- Detta borde egentligen aldrig inträffa'                 
077040               DISPLAY 'IDDC ' SLAG-IDDC ' EJ REG PÅ WDB6'                
077050               CONTINUE                                                   
077100             END-IF                                                       
077200           END-IF                                                         
077300           MOVE LINK1-TIAAVV-AKT TO DAGENS-AAVV                           
077400           MOVE ART-TIFINLV      TO TIFINLV-AAVVD                         
077500           MOVE DAGENS-AA        TO TMP1-YY                               
077600           MOVE TIFINLV-AA       TO TMP2-YY                               
077700           PERFORM WY2000P9                                               
077800           COMPUTE VECKO-DIFF = (TMP1-YY - TMP2-YY) * 52                  
077900                              + DAGENS-VV - TIFINLV-VV                    
078000           IF VECKO-DIFF < 52                                             
078100              MOVE ZERO TO W-OVERLAGER-SDC                                
078200           END-IF                                                         
078300           PERFORM IMS-GNP-WDK711-SDC                                     
078400        END-PERFORM                                                       
078500     END-IF                                                               
078600                                                                          
078700     MOVE W-OVERLAGER-SDC  TO LINK1-KVLS (2)                              
078800     .                                                                    
078900     EJECT                                                                
079000******************************************************************        
079100*                                                                *        
079200*    LAS INFO AK                                                 *        
079300*    HÄMTAR INFORMATION FRÅN CROSS-INDEXREGISTRET                *        
079400*                                                                *        
079500******************************************************************        
079600                                                                          
079700 AD-LAS-INFO-AK SECTION.                                                  
079800                                                                          
079900     IF LINK1-IDLEVNR = '3416' OR '4730' OR 'LAT6A' OR 'LJVZA'            
080000       MOVE '3322' TO W-IDLEVNR                                           
080100     ELSE                                                                 
080200       MOVE LINK1-IDLEVNR TO W-IDLEVNR                                    
080300     END-IF                                                               
080400     PERFORM IMS-GET-WDF502                                               
080500     MOVE LINK1-IDLEVNR TO W-IDLEVNR                                      
080600                                                                          
080700     IF  SEGMENT-FINNS                                                    
080800       MOVE XLEV-BELEVART TO LINK1-BELEV                                  
080900     END-IF                                                               
081000     CONTINUE.                                                            
081100     EJECT                                                                
081200 AE-LAS-BENA11-BSEQ SECTION.                                              
081300                                                                          
081400     MOVE 'GB ' TO W-IDSKYLT                                              
081500     PERFORM IMS-GET-BENA11-BSEQ                                          
081600     MOVE BENA11-TEXT-BEART   TO LINK1-BEART-GB                           
081700     MOVE 'S  ' TO W-IDSKYLT                                              
081800     PERFORM IMS-GET-BENA11-BSEQ                                          
081900     MOVE BENA11-TEXT-BEART   TO LINK1-BEART-SVE                          
082000     CONTINUE.                                                            
082100                                                                          
082200     EJECT                                                                
082300******************************************************************        
082400*                                                                *        
082500*    LAS BESTREST                                                *        
082600*    LÄSER LEVERANTÖRSINFORMATION PÅ LEVERANSPLANEREGISTRET      *        
082700*                                                                *        
082800******************************************************************        
082900                                                                          
083000 C-LAS-BESTREST SECTION.                                                  
083100                                                                          
083200     MOVE LOW-VALUE TO LINK9-IOAREA                                       
083300     MOVE NEJ TO LINK9-FLJANEJ-ANROP                                      
083400     MOVE LINK9-IDARTNR TO W-IDARTNR                                      
083500                                                                          
083600     IF SW-INLB01-FINNS = JA                                              
083700        PERFORM IMS-GET-BALEV                                             
083800        IF SEGMENT-FINNS                                                  
083900          MOVE BALEV-IDLEVNR TO LINK9-IDLEVNR                             
084100          MOVE BALEV-TILEVPL TO LINK9-TILEVPL                             
084200          MOVE JA TO LINK9-FLJANEJ-ANROP                                  
084300        END-IF                                                            
084400     END-IF                                                               
084500     CONTINUE.                                                            
084600     EJECT                                                                
128300 J-LAS-LEV-INFO SECTION.                                                  
128400                                                                          
128500     MOVE LINK10-IDARTNR              TO W-IDARTNR                        
128600     MOVE LINK10-IDLEVNR              TO W-IDLEVNR                        
128700                                                                          
128900*--------------------------------------- EXTRALEVERANSINFO                
129000     IF SW-INLB01-FINNS = JA                                              
130300        PERFORM IMS-GET-BAOMSP                                            
130400                                                                          
130500        IF SEGMENT-FINNS                                                  
130800          MOVE BAOMSP-KDLPORS-TAB (1) TO LINK10-KDLPORS-TAB (1)           
130900          MOVE BAOMSP-KDLPORS-TAB (2) TO LINK10-KDLPORS-TAB (2)           
131000          MOVE BAOMSP-KDLPORS-TAB (3) TO LINK10-KDLPORS-TAB (3)           
131200        ELSE                                                              
131400          MOVE ZERO                   TO LINK10-KDLPORS-TAB (1)           
131500                                         LINK10-KDLPORS-TAB (2)           
131600                                         LINK10-KDLPORS-TAB (3)           
131800        END-IF                                                            
131900     ELSE                                                                 
132400        MOVE ZERO TO LINK10-KDLPORS-TAB (1)                               
132500                     LINK10-KDLPORS-TAB (2)                               
132600                     LINK10-KDLPORS-TAB (3)                               
132800     END-IF                                                               
132900     CONTINUE.                                                            
133000     EJECT                                                                
133100 K-LAS-TPO-ORDER SECTION.                                                 
133200                                                                          
133300     MOVE ZERO                       TO LINK11-SUTPO-TOT(1)               
133400                                        LINK11-SUTPO-TOT(2)               
133500                                        LINK11-KVOKS-DAG (1)              
133600                                        LINK11-KVOKS-DAG (2)              
133700                                        LINK11-KVOKS-BULK (1)             
133800                                        LINK11-KVOKS-BULK (2)             
133900                                        LINK11-KVOKS-VOR (1)              
134000                                        LINK11-KVOKS-VOR (2)              
134100     MOVE NEJ                        TO LINK11-FLJANEJ-ANROP              
134300                                                                          
134310     MOVE LINK11-IDARTNR             TO W-IDARTNR                         
134400     PERFORM IMS-GET-TPO-ORDER-01                                         
134500                                                                          
134600     IF SEGMENT-FINNS                                                     
134700       MOVE ARTM-ART-SUTPO-TOT       TO LINK11-SUTPO-TOT (1)              
134900       MOVE ARTM-ART-KVOKS-DAG       TO LINK11-KVOKS-DAG (1)              
135100       MOVE ARTM-ART-KVOKS-BULK      TO LINK11-KVOKS-BULK (1)             
135300       MOVE ARTM-ART-KVOKS-VOR       TO LINK11-KVOKS-VOR (1)              
135400                                                                          
135500       MOVE JA                       TO LINK11-FLJANEJ-ANROP              
135600       MOVE +1                       TO IXDO                              
135700                                                                          
135800       PERFORM IMS-GET-TPO-ORDER-11                                       
135900                                                                          
136000       PERFORM UNTIL                                                      
136100        NOT ( SEGMENT-FINNS AND IXDO < 8 )                                
136200         MOVE ARTM-ANT-DABEHOV (3:4) TO LINK11-TIBEHOV (IXDO)             
136300         ADD ARTM-ANT-SUTPO-PB                                            
136400             ARTM-ANT-SUTPO-EJPB                                          
136500                                 TO LINK11-SUTPO-TOT-VECKA (IXDO)         
136600         ADD +1                  TO IXDO                                  
136700                                                                          
136800         PERFORM IMS-GET-TPO-ORDER-11                                     
136900       END-PERFORM                                                        
137000     END-IF                                                               
137100     CONTINUE.                                                            
137200     EJECT                                                                
142000 N-LAES-WDB6-DC-INFO SECTION.                                             
142100******************************************************************        
142200*                                                                *        
142300*    LAS IDDC-BASEN WDB6 OCH SKAPA EN TABELL MED DATA            *        
142400*    FÖR ATT SLIPPA LÄSA WDB6 FÖR VARJE ARTIKEL PÅ INFILEN.      *        
142500*    ( LÖNAR SIG OM FILEN HAR FLER POSTER ÄN WDB601 )            *        
142600*                                                                *        
142700******************************************************************        
142800     SET DCIX TO +1                                                       
142900     PERFORM IMS-GN-WDB601                                                
143000                                                                          
143100     PERFORM UNTIL SEGMENT-SLUT                                           
143200       IF DCIX <= DC-MAX                                                  
143210         Move DCS-IDDC To T-DCS-IDDC(DCIX)                                
143220         Move DCS-KDDC To T-DCS-KDDC(DCIX)                                
143230         Move DCS-FLOVRLAGBER To T-DCS-FLOVRLAGBER(DCIX)                  
143250                                                                          
143400         SET DCIX UP BY +1                                                
143600         PERFORM IMS-GN-WDB601                                            
143700       ELSE                                                               
143900           MOVE 35 TO RKOD                                                
144000           MOVE 'DC-TABELL SLUT. ÖKA DC-MAX' TO FELTEXT-STR               
144100*          -- OBS. DETTA ÄR FÖRSTA CALL MOT W2214610                      
144200*          -- INGEN ARTIKEL I W2214600 ÄR ÄNNU PROCESSAD                  
144300           DISPLAY FELTEXT                                                
144400           CALL ABEND USING RKOD                                          
144500       END-IF                                                             
144600     END-PERFORM                                                          
144700                                                                          
145000*    --- SÄTTER TAKET PÅ TABELLEN                                         
145100     SET DCIX  DOWN BY +1                                                 
145200     SET DC-MAX TO DCIX                                                   
145410                                                                          
145500*    --- SORTERA TABELLEN PÅ IDDC, FÖR ATT SEARCH SKA FUNKA               
145501     MOVE DC-MAX                  TO ANTAL                                
145502     MOVE LENGTH OF T-DCS(1)      TO STEGLANGD                            
145503     MOVE LENGTH OF T-DCS-IDDC(1) TO NYCKELLANGD                          
145506                                                                          
145507     CALL WINTSOR USING IDDC-TABELL  STEGLANGD  ANTAL                     
145508                  T-DCS-IDDC(1) NYCKELLANGD                               
145510     .                                                                    
145800     EJECT                                                                
146000                                                                          
146100******************************************************************        
146200*                                                                *        
146300*    I M S   S E K T I O N E R                                   *        
146400*                                                                *        
146500******************************************************************        
146600     SKIP3                                                                
146700 IMS-GET-ARTC2-ART SECTION.                                               
146800                                                                          
146900     STRING 'WLARTC01(IDARTNR  =' W-IDARTNR-X '&KDERS    ='               
147000         W-KDERS-0-X ')'                                                  
147100         DELIMITED BY SIZE INTO SSA1                                      
147200     MOVE '  GE' TO GODK-STATUSKODER                                      
147300     CALL CBLTDLI USING GU WLARTC2-PCB DLI-IO-AREA-01 SSA1                
147400     MOVE WLARTC2-STATUS-CODE TO STATUS-WS                                
147500     PERFORM IMS-STATUSKONTROLL                                           
147600     CONTINUE.                                                            
147700     SKIP3                                                                
147800 IMS-GET-ARTC2-CLAG SECTION.                                              
147900                                                                          
148000     MOVE 'WLARTC11' TO SSA1                                              
148100     MOVE '  GE' TO GODK-STATUSKODER                                      
148200     CALL CBLTDLI USING GNP WLARTC2-PCB DLI-IO-AREA-11 SSA1               
148300     MOVE WLARTC2-STATUS-CODE TO STATUS-WS                                
148400     PERFORM IMS-STATUSKONTROLL                                           
148500     CONTINUE.                                                            
148600     SKIP3                                                                
149800 IMS-GET-NOT-F SECTION.                                                   
149900                                                                          
150000     MOVE 'WLARTC11*F' TO SSA1                                            
150100     MOVE 'WLARTC25' TO SSA2                                              
150200     MOVE '  GE' TO GODK-STATUSKODER                                      
150300     CALL CBLTDLI USING GNP WLARTC2-PCB DLI-IO-AREA SSA1 SSA2             
150400     MOVE WLARTC2-STATUS-CODE TO STATUS-WS                                
150500     PERFORM IMS-STATUSKONTROLL                                           
150600     CONTINUE.                                                            
150700     SKIP3                                                                
150800 IMS-GET-NOT SECTION.                                                     
150900                                                                          
151000     MOVE 'WLARTC25' TO SSA1                                              
151100     MOVE '  GE' TO GODK-STATUSKODER                                      
151200     CALL CBLTDLI USING GNP WLARTC2-PCB DLI-IO-AREA SSA1                  
151300     MOVE WLARTC2-STATUS-CODE TO STATUS-WS                                
151400     PERFORM IMS-STATUSKONTROLL                                           
151500     CONTINUE.                                                            
151600     EJECT                                                                
151700 IMS-GET-INLB01 SECTION.                                                  
151800                                                                          
151900     STRING 'WLINLB01(WDD901KY =' W-WDD901KY-X ')'                        
152000         DELIMITED BY SIZE INTO SSA1                                      
152100     MOVE '  GE' TO GODK-STATUSKODER                                      
152200     CALL CBLTDLI USING GU WLINLB-PCB DLI-IO-AREA SSA1                    
152300     MOVE WLINLB-STATUS-CODE TO STATUS-WS                                 
152400     PERFORM IMS-STATUSKONTROLL                                           
152500     CONTINUE.                                                            
152600     SKIP3                                                                
152700 IMS-GET-BALEV SECTION.                                                   
152800                                                                          
152900     MOVE 'WLINLB11' TO SSA1                                              
153000     MOVE '  GE' TO GODK-STATUSKODER                                      
153100     CALL CBLTDLI USING GNP WLINLB-PCB DLI-IO-AREA SSA1                   
153200     MOVE WLINLB-STATUS-CODE TO STATUS-WS                                 
153300     PERFORM IMS-STATUSKONTROLL                                           
153400     CONTINUE.                                                            
153500     SKIP3                                                                
154800 IMS-GET-BAOMSP SECTION.                                                  
154900                                                                          
155000     STRING 'WLINLB11(IDLEVNR  =' W-IDLEVNR-X ')'                         
155100             DELIMITED BY SIZE INTO SSA1                                  
155200     MOVE 'WLINLB22' TO SSA2                                              
155300     MOVE '  GE' TO GODK-STATUSKODER                                      
155400     CALL CBLTDLI USING GNP WLINLB-PCB DLI-IO-AREA                        
155500     SSA1 SSA2                                                            
155600     MOVE WLINLB-STATUS-CODE TO STATUS-WS                                 
155700     PERFORM IMS-STATUSKONTROLL                                           
155800     CONTINUE.                                                            
155900     SKIP3                                                                
156000 IMS-GET-BAAVROP SECTION.                                                 
156100                                                                          
156200     STRING 'WLINLB11(IDLEVNR  =' W-IDLEVNR-X ')'                         
156300             DELIMITED BY SIZE INTO SSA1                                  
156400     MOVE 'WLINLB23' TO SSA2                                              
156500     MOVE '  GE' TO GODK-STATUSKODER                                      
156600     CALL CBLTDLI USING GNP WLINLB-PCB DLI-IO-AREA                        
156700     SSA1 SSA2                                                            
156800     MOVE WLINLB-STATUS-CODE TO STATUS-WS                                 
156900     PERFORM IMS-STATUSKONTROLL                                           
157000     CONTINUE.                                                            
157100     EJECT                                                                
161100 IMS-GET-BENA11-BSEQ SECTION.                                             
161200                                                                          
161300     STRING 'WLBENA01(WDD3BSEQ =' W-IDARTNR-X ')'                         
161400             DELIMITED BY SIZE INTO SSA1                                  
161500     STRING 'WLBENA11(IDSKYLT  =' W-IDSKYLT-X ')'                         
161600             DELIMITED BY SIZE INTO SSA2                                  
161700     MOVE '  ' TO GODK-STATUSKODER                                        
161800     CALL CBLTDLI USING GU WLBENA-PCB DLI-IO-AREA SSA1 SSA2               
161900     MOVE WLBENA-STATUS-CODE TO STATUS-WS                                 
162000     PERFORM IMS-STATUSKONTROLL                                           
162100     CONTINUE.                                                            
162200     EJECT                                                                
167700 IMS-GET-WDF502 SECTION.                                                  
167800                                                                          
167900     STRING 'WDF501  (IDARTNR  =' W-IDARTNR-X ')'                         
168000             DELIMITED BY SIZE INTO SSA1                                  
168100     STRING 'WDF502  *L(IDLEVNR  =' W-IDLEVNR-X ')'                       
168200             DELIMITED BY SIZE INTO SSA2                                  
168300     MOVE '  GE' TO GODK-STATUSKODER                                      
168400     CALL CBLTDLI USING GU WDF5-PCB DLI-IO-AREA SSA1 SSA2                 
168500     MOVE WDF5-STATUS-CODE TO STATUS-WS                                   
168600     PERFORM IMS-STATUSKONTROLL                                           
168700     CONTINUE.                                                            
168800     EJECT                                                                
170800 IMS-GET-TPO-ORDER-01 SECTION.                                            
170900                                                                          
171000     STRING 'WLARTM01(IDARTNR  =' W-IDARTNR-X ')'                         
171100     DELIMITED BY SIZE INTO SSA1                                          
171200     MOVE '  GE' TO GODK-STATUSKODER                                      
171300     CALL CBLTDLI USING GU WLARTM-PCB DLI-IO-AREA2 SSA1                   
171400     MOVE WLARTM-STATUS-CODE TO STATUS-WS                                 
171500     PERFORM IMS-STATUSKONTROLL                                           
171600     CONTINUE.                                                            
171700     SKIP3                                                                
171800 IMS-GET-TPO-ORDER-11 SECTION.                                            
171900                                                                          
172000     MOVE 'WLARTM11 ' TO SSA1                                             
172100     MOVE '  GE' TO GODK-STATUSKODER                                      
172200     CALL CBLTDLI USING GNP WLARTM-PCB DLI-IO-AREA2 SSA1                  
172300     MOVE WLARTM-STATUS-CODE TO STATUS-WS                                 
172400     PERFORM IMS-STATUSKONTROLL                                           
172500     CONTINUE.                                                            
172600     EJECT                                                                
177000 IMS-GET-WDK701-SDC    SECTION.                                           
177100                                                                          
177200     STRING 'WDK701  (IDARTNR  =' W-IDARTNR-X ')'                         
177300          DELIMITED BY SIZE INTO SSA1                                     
177400     MOVE '  GE' TO GODK-STATUSKODER                                      
177500     CALL CBLTDLI USING GU WDK7-PCB DLI-IO-AREA SSA1                      
177600     MOVE WDK7-STATUS-CODE TO STATUS-WS                                   
177700     PERFORM IMS-STATUSKONTROLL                                           
177800     .                                                                    
177900     SKIP2                                                                
178000 IMS-GNP-WDK711-SDC    SECTION.                                           
178100                                                                          
178200     MOVE 'WDK711    '   TO SSA1                                          
178300     MOVE '  GE' TO GODK-STATUSKODER                                      
178400     CALL CBLTDLI USING GNP WDK7-PCB DLI-IO-AREA SSA1                     
178500     MOVE WDK7-STATUS-CODE TO STATUS-WS                                   
178600     PERFORM IMS-STATUSKONTROLL                                           
178700     .                                                                    
178800     EJECT                                                                
178900 IMS-GN-WDB601    SECTION.                                                
179000     STRING 'WDB601   '                                                   
179100          DELIMITED BY SIZE INTO SSA1                                     
179200     MOVE '  GB' TO GODK-STATUSKODER                                      
179300     CALL CBLTDLI USING GN WDB6-PCB  DLI-IO-AREA-B601 SSA1                
179400     MOVE WDB6-STATUS-CODE    TO STATUS-WS                                
179500     PERFORM IMS-STATUSKONTROLL                                           
179600     .                                                                    
179700     EJECT                                                                
181000                                                                          
181100 IMS-STATUSKONTROLL SECTION.                                              
181200                                                                          
181300     SET STATUS-IX TO 1                                                   
181400     SEARCH GODK-STATUS                                                   
181500         AT END CALL FELLOG                                               
181600               WHEN GODK-STATUS (STATUS-IX) = STATUS-WS                   
181700     CONTINUE                                                             
181800     END-SEARCH                                                           
181900     .                                                                    
182000     EJECT                                                                
182100*    -COPY WY2000P9                                                       
182200     EJECT                                                                
182300*    -COPY WY2000P1                                                       
