000100 ID DIVISION.                                                             
000200 PROGRAM-ID.                 W2217400.                                    
000300*AUTHOR.                     MONICA BERGSTRÖM.                            
000400*DATE-WRITTEN.               NOV  1980.                                   
000500*                                                                         
000600*REMARKS.                                                                 
000700                                                                          
000800*    FUNKTION.                                                            
000900*        PROGRAMMMET UTFÖR REGISTERUPPDATERING PÅ ARTIKELREG/             
001000*        LEVERANSPLAN I SAMBAND MED ÖVERLÄGGNING AV LAGERSALDO            
001100*        PÅ BYTESOBJEKT SOM BESTÄLLNINGSREST PÅ 5001-, 5002-              
001200*        ELLER 5003- ARTIKELNUMMER.                                       
001300                                                                          
001400*    SUBPROGRAM.                                                          
001500*        W2217410    SUBPROGRAM SOM SKÖTER SAMTLIGA IMS-CALL              
001600*                    MOT ARTIKELREGISTRET OCH LEVERANSPLANE-              
001700*                    REGISTRET.                                           
001800     EJECT                                                                
001900 ENVIRONMENT DIVISION.                                                    
002000                                                                          
002100 INPUT-OUTPUT SECTION.                                                    
002200 FILE-CONTROL.                                                            
002300                                                                          
002400*----------------------------------------- ÖVERLÄGGNING AV                
002500*                                          BESTÄLLNINGSREST               
002600                                                                          
002700     SELECT W22173 ASSIGN UT-S-W22174D1.                                  
002800     EJECT                                                                
002900 DATA DIVISION.                                                           
003000 FILE SECTION.                                                            
003100                                                                          
003200 FD  W22173                                                               
003300     RECORDING F                                                          
003400     BLOCK 0                                                              
003500                          .                                               
003600                                                                          
003700*01  POST -COPY W221721.                                                  
003800     EJECT                                                                
003900 WORKING-STORAGE SECTION.                                                 
004000                                                                          
004100*    -- CHECKED BY WY2000                                                 
004200 77  INDENT-I PIC X(40) VALUE                                             
004300     'W2217400 91/05/25 TIME 12.50 VILMAII'.                              
004400***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
004500*                                                                         
004600 77  IDPGM                       PIC X(8)    VALUE 'W2217400'.            
004700 77  CURRENT-SECTION             PIC X(30)  VALUE SPACE.                  
004800 77  DBS-SECTION                 PIC X(30)  VALUE SPACE.                  
004900 01  CHKP-VAR.                                                            
005000     03 CHKP-MSG-IO-AREA-LENGTH  PIC S9(9)   VALUE +32 COMP SYNC.         
005100     03 CHKP-MSG-IO-AREA         PIC X(32)   VALUE SPACE.                 
005200     03 CHKP-AREA-LENGTH         PIC S9(9)   VALUE +32 COMP SYNC.         
005300     03 CHKP-AREA                PIC X(32)   VALUE SPACE.                 
005400     03 CHKP-ANT                 PIC S9(3)   VALUE +0   COMP-3.           
005500     03 CHKP-MAX                 PIC S9(3)   VALUE +900 COMP-3.           
005600 01  W-KVPOST-IN                 PIC S9(9)  VALUE ZERO COMP SYNC.         
005700                                                                          
005800*01  -COPY WWDCKONS                                                       
005900*--------------------------------------- KONSTANTER                       
006000 01  KONSTANTER.                                                          
006100     05  JA                  PIC X       VALUE 'J'.                       
006200     05  NEJ                 PIC X       VALUE 'N'.                       
006300                                                                          
006400 77  W22173-EOF-SW               PIC X       VALUE 'N'.                   
006500     88  END-OF-W22173                       VALUE 'Y'.                   
006600*--------------------------------------- NYCKLAR                          
006700 01  W-IDARTNR-X.                                                         
006800     05  W-IDARTNR           PIC S9(9)               COMP-3.              
006900 01  W-WDD901KY-X.                                                        
007000     05  W-IDARTNR-D9        PIC S9(9)               COMP-3.              
007100     05  W-IDDC-D9           PIC X(2).                                    
007200 01  W-IDLEVNR-X.                                                         
007300     05  W-IDLEVNR           PIC X(5).                                    
007400 01  W-WDGXKEY-4579-X.                                                    
007500     05  W-IDHTYP-4579       PIC X(4)    VALUE '4579'.                    
007600     05  W-IDPGM             PIC X(8)    VALUE 'W2217400'.                
007700     05  FILLER              PIC X(18)   VALUE LOW-VALUE.                 
007800                                                                          
007900 77  RKOD-ABEND                  PIC S9(4)   COMP VALUE +0.               
008000 77  RKOD-ABEND-NO-DUMP          PIC S9(4)   COMP VALUE +16.              
008100 77  RKOD-ABEND-WITH-DUMP        PIC S9(4)   COMP VALUE +1000.            
008200                                                                          
008300 01  ERROR-TEXT.                                                          
008400     03  FILLER                  PIC X(8)    VALUE 'ERR-TEXT'.            
008500     03  ERROR-TEXT-STR          PIC X(72)   VALUE SPACE.                 
008600     EJECT                                                                
008700*--------------------------------------- DYNAMISKA SUBPROGRAM             
008800 01  DYNAMISKA-SUBPROGRAM.                                                
008900     05    CBLTDLI           PIC X(8)    VALUE 'CBLTDLI '.                
009000     05    FELLOG            PIC X(8)    VALUE 'FELLOG  '.                
009100     05    ABEND             PIC X(8)    VALUE 'ABEND'.                   
009200     03    POSTSUM           PIC X(8)    VALUE 'POSTSUM'.                 
009300     EJECT                                                                
009400*    --- PARAMETRAR TILL POSTSUM                                          
009500*                                                                         
009600*01  -COPY W0005   -PRE  POSTSUM-                                         
009700     EJECT                                                                
009800*--------------------------------------- AREA FÖR IN-POST                 
009900                                                                          
010000*01  AREA -COPY W221721 -PRE IN- .                                        
010100     EJECT                                                                
010200*--------------------------------------- ARBETSAREOR TILL                 
010300*                                        IMS-SEKTIONERNA                  
010400 01      IMS-WS.                                                          
010500     05  FILLER              PIC X(8)    VALUE 'IMS-WS  '.                
010600                                                                          
010700*--------------------------------------- STATUSKOD FRÅN IMS               
010800     05  STATUS-WS           PIC XX.                                      
010900         88  SEGMENT-FINNS               VALUE '  '.                      
011000         88  SEGMENT-SAKNAS              VALUE 'GE'.                      
011100         88  IMS-NOT-OK                  VALUE 'XD'.                      
011200                                                                          
011300     05  SSA1                PIC X(128).                                  
011400     05  SSA2                PIC X(128).                                  
011500     05  SSA3                PIC X(128).                                  
011600                                                                          
011700     05  GOOD-STATUSCODES.                                                
011800         10  GOOD-STATUS OCCURS 10 INDEXED BY STATUS-IX PIC XX.           
011900                                                                          
012000*01      -COPY W0003                                                      
012100     EJECT                                                                
012200 01  FILLER                  PIC X(16) VALUE 'DLI-IO-WDK601'.             
012300 01  DLI-IO-WDK601.                                                       
012400*    03  -COPY WDK601                                                     
012500     EJECT                                                                
012600 01  FILLER                  PIC X(16) VALUE 'DLI-IO-WDD901'.             
012700 01  DLI-IO-WDD901.                                                       
012800*    03  -COPY WDD901 -PRE LEVART-                                        
012900     EJECT                                                                
013000 01  FILLER                  PIC X(16) VALUE 'DLI-IO-WDD902'.             
013100 01  DLI-IO-WDD902.                                                       
013200*    03  -COPY WDD902 -PRE LEV-                                           
013300     EJECT                                                                
013400*-ÅTERSTARTSREGISTER WDR4                                                 
013500 01  FILLER         PIC X(16) VALUE 'DLI-IO-WDGX4580'.                    
013600 01  DLI-IO-WDGX4580.                                                     
013700*    03  -COPY WDGX4580                                                   
013800     EJECT                                                                
013900 LINKAGE SECTION.                                                         
014000                                                                          
014100*01  -COPY W0009 -PRE MSG-                                                
014200                                                                          
014300*01  -COPY W0008 -PRE WDK6-                                               
014400     05 FILLER               PIC X.                                       
014500     EJECT                                                                
014600*01  -COPY W0008 -PRE WDD9-                                               
014700     05 FILLER               PIC X.                                       
014800     EJECT                                                                
014900*01  -COPY W0008 -PRE WDR4-                                               
015000     05 FILLER               PIC X.                                       
015100     EJECT                                                                
015200 PROCEDURE DIVISION  USING MSG-PCB WDK6-PCB WDD9-PCB WDR4-PCB.            
015300     ENTRY 'DLITCBL' USING MSG-PCB WDK6-PCB WDD9-PCB WDR4-PCB.            
015400                                                                          
015500     PERFORM A-INIT                                                       
015600                                                                          
015700     PERFORM IMS-LAS-ATERSTART                                            
015800     IF 4580-KVPOST > +0                                                  
015900        PERFORM B-LAES-FRAM-TILL-CHKPOINT                                 
016000     ELSE                                                                 
016100      PERFORM S01-READ-W22173                                             
016200     END-IF                                                               
016300                                                                          
016400     PERFORM UNTIL END-OF-W22173                                          
016500       PERFORM C-UPPDAT-BEST-REST                                         
016600                                                                          
016700       IF CHKP-ANT > CHKP-MAX                                             
016800         PERFORM X-TAKE-CHECKPOINT                                        
016900       END-IF                                                             
017000                                                                          
017100       PERFORM S01-READ-W22173                                            
017200     END-PERFORM                                                          
017300                                                                          
017400     PERFORM Z-FINISH                                                     
017500                                                                          
017600     MOVE ZERO TO RETURN-CODE                                             
017700     GOBACK                                                               
017800     .                                                                    
017900     EJECT                                                                
018000******************************************************************        
018100*                                                                *        
018200*    INITIERING                                                  *        
018300*    ÖPPNA FILER                                                 *        
018400*                                                                *        
018500******************************************************************        
018600                                                                          
018700 A-INIT SECTION.                                                          
018800                                                                          
018900     PERFORM IMS-RESTART                                                  
019000                                                                          
019100     OPEN INPUT W22173                                                    
019200     .                                                                    
019300     EJECT                                                                
019400 B-LAES-FRAM-TILL-CHKPOINT SECTION.                                       
019500     MOVE 'B-LAES-FRAM-TILL-CHKPOINT'  TO CURRENT-SECTION                 
019600                                                                          
019700     PERFORM S01-READ-W22173                                              
019800     PERFORM UNTIL END-OF-W22173 OR                                       
019900                   W-KVPOST-IN = 4580-KVPOST                              
020000        PERFORM S01-READ-W22173                                           
020100     END-PERFORM                                                          
020200                                                                          
020300     IF END-OF-W22173                                                     
020400        MOVE 'INPUTFIL EOF = JA, VID ÅTERSTART'                           
020500                      TO ERROR-TEXT                                       
020600        CALL ABEND USING RKOD-ABEND-NO-DUMP                               
020700     END-IF                                                               
020800     .                                                                    
020900     EJECT                                                                
021000 C-UPPDAT-BEST-REST SECTION.                                              
021100     MOVE 'C-UPPDAT-BEST-REST        ' TO CURRENT-SECTION                 
021200                                                                          
021300     MOVE IN-721-IDARTNR         TO W-IDARTNR                             
021400     PERFORM IMS-GU-WDK601                                                
021500     IF SEGMENT-FINNS                                                     
021600       IF ART-KDERS-UTG = +0                                              
021700                                                                          
021800         MOVE IN-721-IDARTNR     TO W-IDARTNR-D9                          
021900         MOVE WC-CDC-SE          TO W-IDDC-D9                             
022000         PERFORM IMS-GU-WDD901                                            
022100         IF SEGMENT-FINNS                                                 
022200           MOVE IN-721-IDLEVNR   TO W-IDLEVNR                             
022300           PERFORM IMS-GHNP-WDD902                                        
022400           IF SEGMENT-FINNS                                               
022500             MOVE +0             TO LEV-KVBR                              
022600             PERFORM IMS-REPLACE-WDD902                                   
022700           ELSE                                                           
022800             MOVE IN-721-IDLEVNR TO LEV-IDLEVNR                           
022900             MOVE +0             TO LEV-KVBR                              
023000             MOVE +0             TO LEV-TILEVPL                           
023100             PERFORM IMS-ISRT-WDD902                                      
023200           END-IF                                                         
023300         ELSE                                                             
023400           MOVE IN-721-IDARTNR   TO LEVART-IDARTNR                        
023500           MOVE WC-CDC-SE        TO LEVART-IDDC                           
023600           PERFORM IMS-ISRT-WDD901                                        
023700                                                                          
023800           MOVE IN-721-IDLEVNR   TO LEV-IDLEVNR                           
023900           MOVE +0               TO LEV-KVBR                              
024000           MOVE +0               TO LEV-TILEVPL                           
024100           PERFORM IMS-ISRT-WDD902                                        
024200         END-IF                                                           
024300         ADD  +1                 TO CHKP-ANT                              
024400       END-IF                                                             
024500     ELSE                                                                 
024600       DISPLAY 'GB ' IN-721-IDARTNR ' ' IN-721-IDLEVNR ' '                
024700                      IN-721-KVBR                                         
024800     END-IF                                                               
024900     .                                                                    
025000     EJECT                                                                
025100                                                                          
025200 Z-FINISH SECTION.                                                        
025300                                                                          
025400     CLOSE W22173                                                         
025500*    NOLLA ÅTERSTARTINFORMATIONEN                                         
025600     PERFORM IMS-LAS-ATERSTART                                            
025700     MOVE +0                TO 4580-KVPOST                                
025800     ACCEPT 4580-TIUPPDAT FROM DATE                                       
025900     ACCEPT 4580-TIUPPTID FROM TIME                                       
026000                                                                          
026100     PERFORM IMS-REPL-ATERSTART                                           
026200     .                                                                    
026300******************************************************************        
026400*                                                                *        
026500*    LAS W22173 MED BESTÄLLNINGSRESTER                           *        
026600*                                                                *        
026700******************************************************************        
026800                                                                          
026900 S01-READ-W22173 SECTION.                                                 
027000                                                                          
027100     READ W22173 INTO IN-AREA                                             
027200     AT END                                                               
027300        SET END-OF-W22173 TO TRUE                                         
027400                                                                          
027500     NOT AT END                                                           
027600        MOVE 'W22173'   TO POSTSUM-FDNAMN                                 
027700        MOVE 'W22174D1' TO POSTSUM-DDNAMN2                                
027800        MOVE SPACE      TO POSTSUM-TRANSTYP                               
027900        CALL POSTSUM USING POSTSUM-PARM                                   
028000                                                                          
028100        ADD +1              TO W-KVPOST-IN                                
028200                                                                          
028300     END-READ                                                             
028400     .                                                                    
028500     EJECT                                                                
028600 X-TAKE-CHECKPOINT   SECTION.                                             
028700                                                                          
028800*    UPPDATERA ÅTERSTARTREGISTRET                                         
028900     PERFORM IMS-LAS-ATERSTART                                            
029000                                                                          
029100     MOVE W-KVPOST-IN       TO 4580-KVPOST                                
029200     ACCEPT 4580-TIUPPDAT FROM DATE                                       
029300     ACCEPT 4580-TIUPPTID FROM TIME                                       
029400                                                                          
029500     PERFORM IMS-REPL-ATERSTART                                           
029600                                                                          
029700* --- AT CHECKPOINT YOU LOSE GN-POSITION IN THE BASE                      
029800* --- SAVE DATABASE KEYS IF NECESSARY                                     
029900     PERFORM IMS-CHECKPOINT                                               
030000     MOVE ZERO TO CHKP-ANT                                                
030100* --- REREAD DATABASE IF NECESSARY                                        
030200     .                                                                    
030300     EJECT                                                                
030400* --- IMS SECTIONS  ---                                                   
030500                                                                          
030600     EJECT                                                                
030700 IMS-GU-WDK601 SECTION.                                                   
030800     MOVE 'IMS-GU-WDK601      ' TO DBS-SECTION                            
030900                                                                          
031000     STRING 'WDK601  (IDARTNR  =' W-IDARTNR-X ')'                         
031100            DELIMITED BY SIZE INTO SSA1                                   
031200     MOVE '  GE'           TO GOOD-STATUSCODES                            
031300     CALL CBLTDLI       USING GU  WDK6-PCB DLI-IO-WDK601 SSA1             
031400     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
031500     PERFORM IMS-STATUSCHECK                                              
031600     .                                                                    
031700                                                                          
031800 IMS-GU-WDD901 SECTION.                                                   
031900     MOVE 'IMS-GU-WDD901       ' TO DBS-SECTION                           
032000                                                                          
032100     STRING 'WDD901  (WDD901KY =' W-WDD901KY-X ')'                        
032200            DELIMITED BY SIZE INTO SSA1                                   
032300     MOVE '  GE'           TO GOOD-STATUSCODES                            
032400     CALL CBLTDLI       USING GU WDD9-PCB DLI-IO-WDD901 SSA1              
032500     MOVE WDD9-STATUS-CODE TO STATUS-WS                                   
032600     PERFORM IMS-STATUSCHECK                                              
032700     .                                                                    
032800                                                                          
032900 IMS-GHNP-WDD902 SECTION.                                                 
033000     MOVE 'IMS-GHNP-WDD902       ' TO DBS-SECTION                         
033100                                                                          
033200     STRING 'WDD902  (IDLEVNR  =' W-IDLEVNR-X ')'                         
033300            DELIMITED BY SIZE INTO SSA1                                   
033400     MOVE '  GE'           TO GOOD-STATUSCODES                            
033500     CALL CBLTDLI       USING GHNP WDD9-PCB DLI-IO-WDD902 SSA1            
033600     MOVE WDD9-STATUS-CODE TO STATUS-WS                                   
033700     PERFORM IMS-STATUSCHECK                                              
033800     .                                                                    
033900                                                                          
034000 IMS-ISRT-WDD902 SECTION.                                                 
034100     MOVE 'IMS-ISRT-WDD902    ' TO DBS-SECTION                            
034200                                                                          
034300     STRING 'WDD901  (WDD901KY =' W-WDD901KY-X ')'                        
034400            DELIMITED BY SIZE INTO SSA1                                   
034500     MOVE 'WDD902   '      TO SSA2                                        
034600     MOVE '  ' TO GOOD-STATUSCODES                                        
034700     CALL CBLTDLI       USING ISRT WDD9-PCB DLI-IO-WDD902 SSA1            
034800                                                          SSA2            
034900     MOVE WDD9-STATUS-CODE TO STATUS-WS                                   
035000     PERFORM IMS-STATUSCHECK                                              
035100     .                                                                    
035200                                                                          
035300 IMS-ISRT-WDD901 SECTION.                                                 
035400     MOVE 'IMS-ISRT-WDD901    ' TO DBS-SECTION                            
035500                                                                          
035600     MOVE 'WDD901 ' TO SSA1                                               
035700     MOVE '  '             TO GOOD-STATUSCODES                            
035800     CALL CBLTDLI       USING ISRT WDD9-PCB DLI-IO-WDD901 SSA1            
035900     MOVE WDD9-STATUS-CODE TO STATUS-WS                                   
036000     PERFORM IMS-STATUSCHECK                                              
036100     .                                                                    
036200                                                                          
036300 IMS-REPLACE-WDD902 SECTION.                                              
036400     MOVE 'IMS-REPLACE-WDD902   ' TO DBS-SECTION                          
036600                                                                          
036700     MOVE '  '             TO GOOD-STATUSCODES                            
036800     CALL CBLTDLI       USING REPL WDD9-PCB  DLI-IO-WDD902                
036900     MOVE WDD9-STATUS-CODE TO STATUS-WS                                   
037000     PERFORM IMS-STATUSCHECK                                              
037100     .                                                                    
037200     EJECT                                                                
037300 IMS-LAS-ATERSTART SECTION.                                               
037400     MOVE 'IMS-LAS-ATERSTART    ' TO DBS-SECTION                          
037500                                                                          
037600     STRING 'WDR401  (WDGXKEY  =' W-WDGXKEY-4579-X ')'                    
037700                    DELIMITED BY SIZE INTO SSA1                           
037800     MOVE 'WDR470 '        TO SSA2                                        
037900     MOVE '  GE'           TO GOOD-STATUSCODES                            
038000     CALL CBLTDLI USING GHU WDR4-PCB DLI-IO-WDGX4580 SSA1 SSA2            
038100     MOVE WDR4-STATUS-CODE TO STATUS-WS                                   
038200     PERFORM IMS-STATUSCHECK                                              
038300     .                                                                    
038400                                                                          
038500 IMS-REPL-ATERSTART SECTION.                                              
038600     MOVE 'IMS-REPL-ATERSTART   ' TO DBS-SECTION                          
038700                                                                          
038800     MOVE '  '             TO GOOD-STATUSCODES                            
038900     CALL CBLTDLI USING REPL WDR4-PCB DLI-IO-WDGX4580                     
039000     MOVE WDR4-STATUS-CODE TO STATUS-WS                                   
039100     PERFORM IMS-STATUSCHECK                                              
039200     .                                                                    
039300                                                                          
039400     EJECT                                                                
039500 IMS-RESTART SECTION.                                                     
039600     MOVE 'IMS-RESTART          ' TO DBS-SECTION                          
039700                                                                          
039800     MOVE SPACE           TO CHKP-MSG-IO-AREA                             
039900     MOVE '  '            TO GOOD-STATUSCODES                             
040000     CALL CBLTDLI USING XRST MSG-PCB                                      
040100                        CHKP-MSG-IO-AREA-LENGTH CHKP-MSG-IO-AREA          
040200                        CHKP-AREA-LENGTH CHKP-AREA                        
040300     MOVE MSG-STATUS-CODE TO STATUS-WS                                    
040400     PERFORM IMS-STATUSCHECK                                              
040500     .                                                                    
040600                                                                          
040700 IMS-CHECKPOINT SECTION.                                                  
040800     MOVE 'IMS-CHECKPOINT       ' TO DBS-SECTION                          
040900                                                                          
041000     MOVE SPACE           TO CHKP-MSG-IO-AREA                             
041100     MOVE '  XD'          TO GOOD-STATUSCODES                             
041200     CALL CBLTDLI USING CHKP MSG-PCB                                      
041300                        CHKP-MSG-IO-AREA-LENGTH CHKP-MSG-IO-AREA          
041400                        CHKP-AREA-LENGTH CHKP-AREA                        
041500     MOVE MSG-STATUS-CODE TO STATUS-WS                                    
041600     PERFORM IMS-STATUSCHECK                                              
041700                                                                          
041800     IF IMS-NOT-OK                                                        
041900       MOVE 'IMS CONTROL REGION IS NOT ACCESSIBLE'                        
042000                                TO ERROR-TEXT-STR                         
042100       DISPLAY ERROR-TEXT                                                 
042200       CALL FELLOG                                                        
042300     END-IF                                                               
042400     .                                                                    
042500     EJECT                                                                
042600 IMS-STATUSCHECK SECTION.                                                 
042700                                                                          
042800     SET STATUS-IX TO 1                                                   
042900     SEARCH GOOD-STATUS                                                   
043000       AT END                                                             
043100         STRING ' FELAKTIG STATUSKOD FRÅN IMS: ' STATUS-WS                
043200           DELIMITED BY SIZE INTO ERROR-TEXT                              
043300         DISPLAY ERROR-TEXT                                               
043400         CALL FELLOG                                                      
043500       WHEN GOOD-STATUS (STATUS-IX) = STATUS-WS                           
043600         CONTINUE                                                         
043700     END-SEARCH                                                           
043800     .                                                                    
