000100*                  * CONVERTED BY VILMAII *                               
000200*                  * TO PURE COBOLCODE    *                               
000300 ID DIVISION.                                                             
000400 PROGRAM-ID.                 W2217410.                                    
000500*              PROGRAM CONVERTED BY                                       
000600*              COBOL CONVERSION AID PO 5785-ABJ                           
000700*              CONVERSION DATE 05/25/91 19:29:46.                         
000800*AUTHOR.                     MONICA BERGSTRÖM.                            
000900*DATE-WRITTEN.               NOV  1980.                                   
001000*    SKIP3                                                                
001100*REMARKS.                                                                 
001200                                                                          
001300*    FUNKTION.                                                            
001400*        PROGRAMMET ÄR ETT SUBPROGRAM TILL W2217400                       
001500*        SOM SKÖTER OM SAMTLIGA IMS-CALL ÅT DETSAMMA MOT                  
001600*        ARTIKELREG                  (LOGISKT WLARTC).                    
001700*        LEVERANSPLANEREG            (LOGISKT WLINLB).                    
001800     SKIP3                                                                
001900 ENVIRONMENT DIVISION.                                                    
002000     SKIP3                                                                
002100 DATA DIVISION.                                                           
002200     EJECT                                                                
002300 WORKING-STORAGE SECTION.                                                 
002400                                                                          
002500*    -- CHECKED BY WY2000                                                 
002600 77  INDENT-I PIC X(40) VALUE                                             
002700     'W2217410 91/05/25 TIME 12.50 VILMAII'.                              
002800***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
002900*                                                                         
003000*01  -COPY WWDCKONS                                                       
003100     SKIP3                                                                
003200 77  RKOD                    PIC S9(4)   VALUE +0    COMP SYNC.           
003300*--------------------------------------- KONSTANTER                       
003400 01  KONSTANTER.                                                          
003500     05  JA                  PIC X       VALUE 'J'.                       
003600     05  NEJ                 PIC X       VALUE 'N'.                       
003700     05  UPPDAT-BEST-REST    PIC S9(3)   VALUE +101  COMP-3.              
003800     SKIP3                                                                
003900*--------------------------------------- NYCKLAR                          
004000 01  W-IDARTNR-X.                                                         
004100     05  W-IDARTNR           PIC S9(9)               COMP-3.              
004200 01  W-WDD901KY-X.                                                        
004300     05  W-IDARTNR-D9        PIC S9(9)               COMP-3.              
004400     05  W-IDDC-D9           PIC X(2).                                    
004500 01  W-IDLEVNR-X.                                                         
004600     05  W-IDLEVNR           PIC X(5).                                    
004700     SKIP3                                                                
004800*--------------------------------------- GENERELLA SUBRUTINER             
004900 01      SUBPROGRAM.                                                      
005000     05    CBLTDLI           PIC X(8)    VALUE 'CBLTDLI '.                
005100     05    FELLOG            PIC X(8)    VALUE 'FELLOG  '.                
005200     05    ABEND             PIC X(8)    VALUE 'ABEND'.                   
005300     EJECT                                                                
005400*--------------------------------------- ARBETSAREOR TILL                 
005500*                                        IMS-SEKTIONERNA                  
005600 01      IMS-WS.                                                          
005700     05  FILLER              PIC X(8)    VALUE 'IMS-WS  '.                
005800     SKIP3                                                                
005900*--------------------------------------- STATUSKOD FRÅN IMS               
006000     05  STATUS-WS           PIC XX.                                      
006100         88  SEGMENT-FINNS               VALUE '  '.                      
006200         88  SEGMENT-SAKNAS              VALUE 'GE'.                      
006300     SKIP3                                                                
006400     05  SSA1                PIC X(40).                                   
006500     05  SSA2                PIC X(40).                                   
006600     05  SSA3                PIC X(40).                                   
006700     SKIP3                                                                
006800     05  GODK-STATUSKODER.                                                
006900         10  GODK-STATUS OCCURS 10 INDEXED BY STATUS-IX PIC XX.           
007000     SKIP3                                                                
007100*01      -COPY W0003                                                      
007200     EJECT                                                                
007300 01  DLI-IO-AREA             PIC X(110)  VALUE SPACE.                     
007400     SKIP3                                                                
007500*01  WLARTC01 -COPY WDK601 -RED DLI-IO-AREA.                              
007600     EJECT                                                                
007700 01  WLINLB01 -COPY WDD901 -PRE LEVART-  -RED DLI-IO-AREA.                
007800     EJECT                                                                
007900*01  WLINLB11 -COPY WDD902 -PRE LEV- -RED DLI-IO-AREA.                    
008000     EJECT                                                                
008100 LINKAGE SECTION.                                                         
008200                                                                          
008300 01  LINK-AREA               PIC X(40).                                   
008400     SKIP3                                                                
008500*01  AREA -COPY W221L741 -RED LINK-AREA -PRE LINK1-                       
008600     EJECT                                                                
008700*01  -COPY W0008     -PRE ARTC-.                                          
008800      05  FILLER             PIC X.                                       
008900     EJECT                                                                
009000*01  -COPY W0008     -PRE INLB-.                                          
009100      05  FILLER             PIC X.                                       
009200     EJECT                                                                
009300 PROCEDURE DIVISION USING LINK-AREA ARTC-PCB INLB-PCB.                    
009400     ENTRY 'DLITCBL' USING LINK-AREA ARTC-PCB INLB-PCB.                   
009500     SKIP3                                                                
009600     EVALUATE LINK1-KDCALL                                                
009700     WHEN UPPDAT-BEST-REST                                                
009800       PERFORM A-UPPDAT-BEST-REST                                         
009900     WHEN OTHER                                                           
010000       MOVE 30  TO RKOD                                                   
010100       DISPLAY '*** W2217410 CALLVÄRDE FELAKTIGT ***'                     
010200       CALL ABEND USING RKOD                                              
010300     END-EVALUATE                                                         
010400     MOVE ZERO TO RETURN-CODE                                             
010500     GOBACK                                                               
010600     CONTINUE.                                                            
010700     EJECT                                                                
010800 A-UPPDAT-BEST-REST SECTION.                                              
010900     SKIP3                                                                
011000     MOVE LINK1-IDARTNR TO W-IDARTNR                                      
011100                           W-IDARTNR-D9                                   
011110     MOVE WC-CDC-SE     TO W-IDDC-D9                                      
011200     MOVE LINK1-IDLEVNR TO W-IDLEVNR                                      
011300     SKIP1                                                                
011400     PERFORM IMS-GET-ARTIKEL                                              
011500     IF SEGMENT-FINNS                                                     
011600       IF ART-KDERS-UTG = +0                                              
011700         SKIP1                                                            
011800         PERFORM IMS-GET-ROT-LP                                           
011900         IF SEGMENT-FINNS                                                 
012000           PERFORM IMS-GET-LEV-LP                                         
012100           IF SEGMENT-FINNS                                               
012200             MOVE LINK1-KVBR TO LEV-KVBR                                  
012300             PERFORM IMS-REPLACE-INLB                                     
012400           ELSE                                                           
012500             MOVE LINK1-IDLEVNR TO LEV-IDLEVNR                            
012600             MOVE LINK1-KVBR TO LEV-KVBR                                  
012700             MOVE LINK1-TILEVPL TO LEV-TILEVPL                            
012800             PERFORM IMS-NYUPPL-LEV-LP                                    
012900           END-IF                                                         
013000         ELSE                                                             
013100           MOVE LINK1-IDARTNR TO LEVART-IDARTNR                           
013110           MOVE WC-CDC-SE     TO LEVART-IDDC                              
013200           PERFORM IMS-NYUPPL-ROT-LP                                      
013300           SKIP1                                                          
013400           MOVE LINK1-IDLEVNR TO LEV-IDLEVNR                              
013500           MOVE LINK1-KVBR TO LEV-KVBR                                    
013600           MOVE LINK1-TILEVPL TO LEV-TILEVPL                              
013700           PERFORM IMS-NYUPPL-LEV-LP                                      
013800         END-IF                                                           
013900       END-IF                                                             
014000     ELSE                                                                 
014100       DISPLAY 'GB ' LINK1-IDARTNR ' ' LINK1-IDLEVNR ' '                  
014200       LINK1-KVBR                                                         
014300     END-IF                                                               
014400     CONTINUE.                                                            
014500     EJECT                                                                
014600******************************************************************        
014700*                                                                *        
014800*    I M S   S E K T I O N E R                                   *        
014900*                                                                *        
015000******************************************************************        
015100     SKIP3                                                                
015200 IMS-GET-ARTIKEL SECTION.                                                 
015300                                                                          
015400     STRING 'WLARTC01(IDARTNR  =' W-IDARTNR-X ')'                         
015500            DELIMITED BY SIZE INTO SSA1                                   
015600     MOVE '  GE' TO GODK-STATUSKODER                                      
015700     CALL CBLTDLI USING GU  ARTC-PCB DLI-IO-AREA SSA1                     
015800     MOVE ARTC-STATUS-CODE TO STATUS-WS                                   
015900     PERFORM IMS-STATUSKONTROLL                                           
016000     CONTINUE.                                                            
016100     SKIP3                                                                
016200 IMS-GET-ROT-LP SECTION.                                                  
016300                                                                          
016400     STRING 'WLINLB01(WDD901KY =' W-WDD901KY-X ')'                        
016500            DELIMITED BY SIZE INTO SSA1                                   
016600     MOVE '  GE' TO GODK-STATUSKODER                                      
016700     CALL CBLTDLI USING GU INLB-PCB DLI-IO-AREA SSA1                      
016800     MOVE INLB-STATUS-CODE TO STATUS-WS                                   
016900     PERFORM IMS-STATUSKONTROLL                                           
017000     CONTINUE.                                                            
017100     SKIP3                                                                
017200 IMS-GET-LEV-LP SECTION.                                                  
017300                                                                          
017400     STRING 'WLINLB11(IDLEVNR  =' W-IDLEVNR-X ')'                         
017500            DELIMITED BY SIZE INTO SSA1                                   
017600     MOVE '  GE' TO GODK-STATUSKODER                                      
017700     CALL CBLTDLI USING GHNP INLB-PCB DLI-IO-AREA SSA1                    
017800     MOVE INLB-STATUS-CODE TO STATUS-WS                                   
017900     PERFORM IMS-STATUSKONTROLL                                           
018000     CONTINUE.                                                            
018100     SKIP3                                                                
018200 IMS-NYUPPL-LEV-LP SECTION.                                               
018300                                                                          
018400     STRING 'WLINLB01(WDD901KY =' W-WDD901KY-X ')'                        
018500            DELIMITED BY SIZE INTO SSA1                                   
018600     MOVE 'WLINLB11 ' TO SSA2                                             
018700     MOVE '  ' TO GODK-STATUSKODER                                        
018800     CALL CBLTDLI USING ISRT INLB-PCB DLI-IO-AREA SSA1 SSA2               
018900     MOVE INLB-STATUS-CODE TO STATUS-WS                                   
019000     PERFORM IMS-STATUSKONTROLL                                           
019100     CONTINUE.                                                            
019200     SKIP3                                                                
019300 IMS-NYUPPL-ROT-LP SECTION.                                               
019400                                                                          
019500     MOVE 'WLINLB01 ' TO SSA1                                             
019600     MOVE '  ' TO GODK-STATUSKODER                                        
019700     CALL CBLTDLI USING ISRT INLB-PCB DLI-IO-AREA SSA1                    
019800     MOVE INLB-STATUS-CODE TO STATUS-WS                                   
019900     PERFORM IMS-STATUSKONTROLL                                           
020000     CONTINUE.                                                            
020100     SKIP3                                                                
020200 IMS-REPLACE-INLB SECTION.                                                
020300                                                                          
020400     MOVE '  '   TO GODK-STATUSKODER                                      
020500     CALL CBLTDLI USING REPL INLB-PCB DLI-IO-AREA                         
020600     MOVE INLB-STATUS-CODE TO STATUS-WS                                   
020700     PERFORM IMS-STATUSKONTROLL                                           
020800     CONTINUE.                                                            
020900     EJECT                                                                
021000 IMS-STATUSKONTROLL SECTION.                                              
021100                                                                          
021200     SET STATUS-IX TO 1                                                   
021300     SEARCH GODK-STATUS AT END CALL FELLOG                                
021400     WHEN GODK-STATUS (STATUS-IX) = STATUS-WS                             
021500     CONTINUE                                                             
021600     END-SEARCH                                                           
021700     CONTINUE                                                             
021800            CONTINUE.                                                     
021900 IMS-EXIT. EXIT.                                                          
022000     CONTINUE.                                                            
