000100 ID DIVISION.                                                             
000200 PROGRAM-ID.     W2222000.                                                
000300*AUTHOR.         JAN CARLSSON, DATA LOGIC AB GÖTEBORG                     
000400*DATE-WRITTEN.   NOVEMBER 1978.                                           
000500*                                                                         
000600*REMARKS.                                                                 
000700*    FUNKTION.                                                            
000800*                PROGRAMMET UPPDATERAR PROGNOSER MED HJÄLP                
000900*                AV TIDIGARE REGISTRERADE PB-JUSTERINGAR.                 
001000*    SUBPROGRAM.                                                          
001100*                DATKORT     SUBPROGRAM FÖR AKTUELL DATUM.                
001200                                                                          
001300*                ABEND                                                    
001400                                                                          
001500     EJECT                                                                
001600 ENVIRONMENT DIVISION.                                                    
001700                                                                          
001800 INPUT-OUTPUT SECTION.                                                    
001900                                                                          
002000 FILE-CONTROL.                                                            
002100     EJECT                                                                
002200 DATA DIVISION.                                                           
002300                                                                          
002400 FILE SECTION.                                                            
002500                                                                          
002600 WORKING-STORAGE SECTION.                                                 
002700*    -COPY WY2000W3                                                       
002800                                                                          
002900 77  INDENT-I PIC X(40) VALUE                                             
003000     'W2222000 91/05/25 TIME 12.51 VILMAII'.                              
003100***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
003200*                                                                         
003300 77  IDPGM                       PIC X(8)    VALUE 'W2222200'.            
003400 77  DBS-SECTION                 PIC X(30).                               
003500 77  CURRENT-SECTION             PIC X(30)   VALUE SPACE.                 
003600                                                                          
004500 77  YES                         PIC X       VALUE 'J'.                   
004600 77  NOO                         PIC X       VALUE 'N'.                   
004700                                                                          
004800 01  WORK-AREA.                                                           
005400                                                                          
005500     03  WS-KVPB-HIST            PIC S9(6)V9(1) COMP-3.                   
005600     03  WS-KVPB-SEP             PIC S9(6)V9(1) COMP-3.                   
005700     03  WS-JUST-PBJUST OCCURS 2.                                         
005800         05 WS-JUST-KVPB-JUST    PIC S9(6)V9(1) COMP-3.                   
005900         05 WS-JUST-TIPBJUST     PIC S9(5)      COMP-3.                   
006000     03  WS-JUST-CENTR-PBJUST.                                            
006100         05  WS-JUST-REPBJUST    PIC S9V9(2)    COMP-3.                   
006200         05  WS-JUST-TIPBJUST-CENTR PIC S9(5)   COMP-3.                   
006300 01  ERROR-TEXT.                                                          
006400     03  FILLER                  PIC X(8)    VALUE 'ERR-TEXT'.            
006500     03  ERROR-TEXT-STR          PIC X(72)   VALUE SPACE.                 
006600     EJECT                                                                
006800                                                                          
006900 01  FILLER-1.                                                            
007000     05  W-AAR                   PIC 999.                                 
007100     05  W-VECKA                 PIC 99.                                  
007200 01  W-KORVECKA REDEFINES FILLER-1 PIC 9(5).                              
007300                                                                          
007400 01  FILLER-2.                                                            
007500     05  W-AAR2                  PIC 99.                                  
007600     05  W-VECKA2                PIC 99.                                  
007700     05  W-DAG2                  PIC 9.                                   
007800 01  W-AAVVD REDEFINES FILLER-2  PIC 9(5).                                
007900 01  W-AAAAMMDD-AKT              PIC 9(8) VALUE ZERO.                     
008000                                                                          
008100 01  RKOD                        PIC S9(4)   VALUE +0  COMP SYNC.         
008300                                                                          
008400 01  KONSTANTER.                                                          
008500     03  JA                      PIC X       VALUE 'J'.                   
008600     03  NEJ                     PIC X       VALUE 'N'.                   
008700                                                                          
008800 01  GENERAL-SUBPROGRAMS.                                                 
008900     03  CBLTDLI                 PIC X(8)    VALUE 'CBLTDLI '.            
009000     03  FELLOG                  PIC X(8)    VALUE 'FELLOG  '.            
009100     03  DATKORT                 PIC X(8)    VALUE 'DATKORT '.            
009200                                                                          
009300 01  PROGRAM-NAMN                PIC X(6)    VALUE 'W22220'.              
009400 01  DATUMKORT-ID                PIC X(6)    VALUE 'WDATUM'.              
009500*01  -COPY   WDATKORT                                                     
009600     EJECT                                                                
009700 01  FILLER                      PIC X(16)   VALUE 'IMS-WS'.              
009800                                                                          
009900 01  KEYS-TILL-DLI.                                                       
010000     03  W-WDGX2207-X.                                                    
010100         05  W-IDHTYP            PIC X(04)   VALUE '2207'.                
010200         05  FILLER              PIC X(26)   VALUE LOW-VALUE.             
010300     03  W-IDARTNR-X.                                                     
010400         05  W-IDARTNR           PIC S9(9)   COMP-3.                      
010500     03  W-KDERS-0-X.                                                     
010600         05  W-KDERS-0           PIC S9(3)   COMP-3  VALUE ZERO.          
010700     03  W-WDG3KEY.                                                       
010800         05  W-IDHTYP            PIC X(4)    VALUE '2202'.                
010900         05  W-LOW-VALUE         PIC X(26)   VALUE LOW-VALUE.             
011000                                                                          
011100*    --- STATUS-KOD FRÅN IMS                                              
011200 01  STATUS-WS                   PIC XX.                                  
011300     88  SEGMENT-FOUND                       VALUE '  '.                  
011400     88  SEGMENT-FOUND-EXISTS                VALUE 'II'.                  
011500     88  SEGMENT-MISSING                     VALUE 'GE'.                  
011600     88  SEGMENT-NOMORE                      VALUE 'GB'.                  
011700     88  IMS-NOT-OK                          VALUE 'XD'.                  
011800                                                                          
011900 01  GOOD-STATUSCODES.                                                    
012000     03  GOOD-STATUS OCCURS 5 INDEXED BY STATUS-IX PIC XX.                
012100                                                                          
012200 01  SSA1                        PIC X(128).                              
012300 01  SSA2                        PIC X(128).                              
012400                                                                          
012500*    --- IMS FUNCTION CODES                                               
012600*01  -COPY W0003                                                          
012700     EJECT                                                                
012800                                                                          
012900     SKIP3                                                                
013000*01  -COPY WDK626     -PRE JMF-.                                          
013100     EJECT                                                                
013200                                                                          
013300*    ---  DLI INPUT-OUTPUT AREA                                           
013400 01  FILLER         PIC X(16) VALUE 'DLI-IO-WDK601'.                      
013500 01  DLI-IO-WDK601.                                                       
013600*    03  -COPY WDK601                                                     
013700     EJECT                                                                
013800 01  FILLER         PIC X(16) VALUE 'DLI-IO-WDK611'.                      
013900 01  DLI-IO-WDK611.                                                       
014000*    03  -COPY WDK611                                                     
014100     EJECT                                                                
014200 01  FILLER         PIC X(16) VALUE 'DLI-IO-WDK626'.                      
014300 01  DLI-IO-WDK626.                                                       
014400*    03  -COPY WDK626                                                     
014500     EJECT                                                                
014600 01  FILLER         PIC X(16) VALUE 'DLI-IO-WDG301'.                      
014700 01  DLI-IO-WDG301.                                                       
014800*    03  -COPY WDG301   -PRE 2207-                                        
014900     EJECT                                                                
015000 01  FILLER         PIC X(16) VALUE 'DLI-IO-WDGX2207'.                    
015100 01  DLI-IO-WDGX2207.                                                     
015200*    03  -COPY WDGX2207 -PRE 2207-                                        
015300     EJECT                                                                
015400 01  FILLER         PIC X(16) VALUE 'DLI-IO-WDG32202'.                    
015500 01  DLI-IO-WDG32202.                                                     
015600*    03  HANDELSE -COPY WDG32202  -PRE 2202-                              
015700     EJECT                                                                
015800 LINKAGE SECTION.                                                         
015901*01  -COPY W0009   -PRE MSG-                                              
016000                                                                          
016100*01  -COPY W0008 -PRE WDK6-                                               
016200     05  FILLER                  PIC X(32).                               
016300     EJECT                                                                
016400*01  -COPY W0008 -PRE 2207-                                               
016500     05  FILLER                  PIC X(32).                               
016600     EJECT                                                                
016700*01  -COPY W0008 -PRE 2202-                                               
016800     05  FILLER                  PIC X(32).                               
016900     EJECT                                                                
017301 PROCEDURE DIVISION  USING MSG-PCB  WDK6-PCB 2207-PCB 2202-PCB.           
017400                                                                          
017501     ENTRY 'DLITCBL' USING MSG-PCB  WDK6-PCB 2207-PCB 2202-PCB.           
017600                                                                          
017700     PERFORM A-INIT                                                       
017800                                                                          
017900     PERFORM IMS-GU-WLXXAD01                                              
018000                                                                          
018100     IF SEGMENT-FOUND                                                     
018200        PERFORM IMS-GHNP-WLXXAD11                                         
018300     END-IF                                                               
018400                                                                          
018500     PERFORM S01-NOLLSTALL-JMFWDK626                                      
018600                                                                          
018700     PERFORM UNTIL SEGMENT-MISSING                                        
018800                                                                          
018900       MOVE 2207-TIPBJUST             TO TMP1-YYWW                        
019000       MOVE W-KORVECKA                TO TMP2-YYWW                        
019100       PERFORM WY2000P3                                                   
019200       IF TMP1-YYWW <= TMP2-YYWW                                          
019400         PERFORM C-LAS-UPD-PROGNOSDATA-I-ARTREG                           
019410         PERFORM B-BORTTAG-AV-HANDELSE-2207                               
019500       END-IF                                                             
019600                                                                          
020100       PERFORM IMS-GHNP-WLXXAD11                                          
020200                                                                          
020300     END-PERFORM                                                          
020400                                                                          
020500     MOVE ZERO TO RETURN-CODE                                             
020600                                                                          
020700     GOBACK                                                               
020800     CONTINUE.                                                            
020900     EJECT                                                                
021000 A-INIT       SECTION.                                                    
021100     MOVE 'A-INIT                   ' TO CURRENT-SECTION                  
021300                                                                          
021600     CALL DATKORT USING PROGRAM-NAMN DATUMKORT-ID DATUMKORT               
021700     MOVE D-AAR                       TO W-AAR                            
021800     MOVE K-VECKA                     TO W-VECKA                          
021900     MOVE D-AAR                       TO W-AAR2                           
022000     MOVE K-VECKA                     TO W-VECKA2                         
022100     MOVE 6                           TO W-DAG2                           
022200                                                                          
022300     MOVE FUNCTION CURRENT-DATE (1:8) TO W-AAAAMMDD-AKT                   
022400     .                                                                    
022500     EJECT                                                                
022600 B-BORTTAG-AV-HANDELSE-2207 SECTION.                                      
022700     MOVE 'B-BORTTAG-AV-HANDELSE-2207' TO CURRENT-SECTION                 
022900****************************************************                      
023000*    HÄR SKER BORTTAG AV UNDERSEGMENTET W222AB02    *                     
023100****************************************************                      
023200     PERFORM IMS-DLET-WDGX2207                                            
023300     .                                                                    
023400     EJECT                                                                
023500 C-LAS-UPD-PROGNOSDATA-I-ARTREG SECTION.                                  
023600     MOVE 'C-LAS-UPD-PROGNOSDATA-I-ARTREG' TO CURRENT-SECTION             
023800                                                                          
023900     MOVE 2207-IDARTNR              TO W-IDARTNR                          
024000     PERFORM IMS-GU-WDK601                                                
024100     IF SEGMENT-FOUND                                                     
024200       PERFORM IMS-GHNP-WDK611                                            
024300       IF SEGMENT-FOUND                                                   
025200                                                                          
025300         PERFORM IMS-GHNP-WDK626                                          
025400                                                                          
025500         IF SEGMENT-FOUND                                                 
025600           MOVE JUST-PBJUST (1)     TO WS-JUST-PBJUST (1)                 
025700           MOVE JUST-PBJUST (2)     TO WS-JUST-PBJUST (2)                 
025800           MOVE JUST-CENTR-PBJUST   TO WS-JUST-CENTR-PBJUST               
025900           PERFORM CA-UPD-PROGNOSDATA-I-ARTREG                            
026000         END-IF                                                           
026100       END-IF                                                             
026200     END-IF                                                               
026300                                                                          
026500     .                                                                    
026600     EJECT                                                                
026700 CA-UPD-PROGNOSDATA-I-ARTREG SECTION.                                     
026800     MOVE 'CA-UPD-PROGNOSDATA-I-ARTREG' TO CURRENT-SECTION                
027000                                                                          
027100     MOVE JUST-TIPBJUST(1)       TO TMP1-YYWW                             
027200     MOVE W-KORVECKA             TO TMP2-YYWW                             
027300     PERFORM WY2000P3                                                     
027400     IF TMP1-YYWW       > 0 AND                                           
027500        TMP1-YYWW   NOT > TMP2-YYWW                                       
027600       MOVE JUST-KVPB-JUST (1)   TO WS-KVPB-HIST                          
027700       MOVE JUST-KVPB-JUST (1)   TO WS-KVPB-SEP                           
027800                                                                          
027900       MOVE JUST-PBJUST    (2)   TO WS-JUST-PBJUST(1)                     
028000       MOVE ZERO                 TO WS-JUST-KVPB-JUST (2)                 
028100       MOVE ZERO                 TO WS-JUST-TIPBJUST (2)                  
028200       PERFORM CAA-UPPDATERA-WDK6                                         
028300     ELSE                                                                 
028400       MOVE JUST-TIPBJUST(2)     TO TMP1-YYWW                             
028500       MOVE W-KORVECKA           TO TMP2-YYWW                             
028600       PERFORM WY2000P3                                                   
028700       IF TMP1-YYWW       > 0 AND                                         
028800          TMP1-YYWW   NOT > TMP2-YYWW                                     
028900         MOVE JUST-KVPB-JUST(2)  TO WS-KVPB-HIST                          
029000         MOVE JUST-KVPB-JUST(2)  TO WS-KVPB-SEP                           
029100         MOVE ZERO               TO WS-JUST-KVPB-JUST (2)                 
029200         MOVE ZERO               TO WS-JUST-TIPBJUST (2)                  
029300         PERFORM CAA-UPPDATERA-WDK6                                       
029400       ELSE                                                               
029500         MOVE JUST-TIPBJUST-CENTR TO TMP1-YYWW                            
029600         MOVE W-KORVECKA         TO TMP2-YYWW                             
029700         PERFORM WY2000P3                                                 
029800         IF TMP1-YYWW      > 0 AND                                        
029900            TMP1-YYWW  NOT > TMP2-YYWW                                    
030000           COMPUTE WS-KVPB-SEP ROUNDED =                                  
030100                   JUST-REPBJUST * WS-KVPB-SEP                            
030200           MOVE WS-KVPB-SEP      TO WS-KVPB-HIST                          
030300           MOVE ZERO             TO WS-JUST-REPBJUST                      
030400           MOVE ZERO             TO WS-JUST-TIPBJUST-CENTR                
030500           PERFORM CAA-UPPDATERA-WDK6                                     
030600         END-IF                                                           
030700       END-IF                                                             
030800     END-IF                                                               
030900     .                                                                    
031000     EJECT                                                                
031100 CAA-UPPDATERA-WDK6 SECTION.                                              
031200     MOVE 'CAA-UPPDATERA-WDK6       ' TO CURRENT-SECTION                  
032200                                                                          
032300     IF ART-IDLEVNR = '1002 '                                             
032400       PERFORM CAAA-SKAPA-HANDELSE-POST                                   
032500     END-IF                                                               
032600                                                                          
032700     PERFORM IMS-GU-WDK601                                                
032800     IF SEGMENT-FOUND                                                     
032900       PERFORM IMS-GHNP-WDK611                                            
033000       IF SEGMENT-FOUND                                                   
033100         MOVE WS-KVPB-SEP           TO CLAG-KVPB-SEP                      
033200         IF WS-KVPB-SEP > 1                                               
033300           MOVE WS-KVPB-SEP         TO CLAG-KVPB-VESL                     
033400         END-IF                                                           
033500         MOVE W-AAVVD               TO CLAG-TIPBDAT                       
033600         MOVE +0                    TO CLAG-RVPROFEL                      
033700         MOVE +0                    TO CLAG-RVPROURS                      
033800         MOVE +0                    TO CLAG-KVUTJFEL                      
033900         MOVE WS-KVPB-HIST          TO CLAG-KVPB-HIST                     
034000         PERFORM IMS-REPL-WDK611                                          
034100                                                                          
034200         PERFORM IMS-GHNP-WDK626                                          
034300         IF SEGMENT-FOUND                                                 
034400           MOVE WS-JUST-PBJUST (1)  TO JUST-PBJUST (1)                    
034500           MOVE WS-JUST-PBJUST (2)  TO JUST-PBJUST (2)                    
034600           MOVE WS-JUST-CENTR-PBJUST TO JUST-CENTR-PBJUST                 
034700           IF JUST-WDK626 = JMF-JUST-WDK626                               
034800             PERFORM IMS-DLET-TREND-SASONG-JUST                           
034900           ELSE                                                           
035000             PERFORM IMS-REPL-TREND-SASONG-JUST                           
035100           END-IF                                                         
035200         END-IF                                                           
035300       END-IF                                                             
035400     END-IF                                                               
035500     .                                                                    
035600     EJECT                                                                
035700 CAAA-SKAPA-HANDELSE-POST SECTION.                                        
035800     MOVE 'CAAA-SKAPA-HANDELSE-POST   ' TO CURRENT-SECTION                
036000                                                                          
036200     MOVE ART-IDARTNR               TO 2202-IDARTNR-SATS                  
036300     MOVE +1                        TO 2202-KDCLAGER                      
036400     MOVE CLAG-KVPB-SEP             TO 2202-KVPB-SEP-GAMMAL               
036500     MOVE WS-KVPB-SEP               TO 2202-KVPB-SEP-NY                   
036600     PERFORM IMS-ISRT-R2202                                               
036700     .                                                                    
036800     EJECT                                                                
036900 S01-NOLLSTALL-JMFWDK626 SECTION.                                         
037000     MOVE 'S01-NOLLSTALL-JMFWDK626    ' TO CURRENT-SECTION                
037200                                                                          
037300     MOVE +0                        TO JMF-JUST-REPBJUST                  
037400                                       JMF-JUST-TIPBJUST-CENTR            
037500     MOVE +0                        TO JMF-JUST-KVPB-JUST(1)              
037600                                       JMF-JUST-KVPB-JUST(2)              
037700     MOVE +0                        TO JMF-JUST-TIPBJUST (1)              
037800                                       JMF-JUST-TIPBJUST (2)              
037810     MOVE ZERO                      TO JMF-JUST-DAMANSEA                  
037820                                       JMF-JUST-DASPSEA                   
037900     MOVE +1                        TO JMF-JUST-RESEASON (1)              
038000                                       JMF-JUST-RESEASON (2)              
038100     MOVE +1                        TO JMF-JUST-RESEASON (3)              
038200                                       JMF-JUST-RESEASON (4)              
038300     MOVE +1                        TO JMF-JUST-RESEASON (5)              
038400                                       JMF-JUST-RESEASON (6)              
038500     MOVE +1                        TO JMF-JUST-RESEASON (7)              
038600                                       JMF-JUST-RESEASON (8)              
038700     MOVE +1                        TO JMF-JUST-RESEASON (9)              
038800                                       JMF-JUST-RESEASON (10)             
038900     MOVE +1                        TO JMF-JUST-RESEASON (11)             
039000                                       JMF-JUST-RESEASON (12)             
039100     .                                                                    
039200     EJECT                                                                
041200 IMS-GU-WDK601 SECTION.                                                   
041400     MOVE 'IMS-GU-WDK601              ' TO DBS-SECTION                    
041500                                                                          
041600     STRING 'WDK601  (IDARTNR  =' W-IDARTNR-X                             
041700                    '&KDERS    ='  W-KDERS-0-X  ')'                       
041800     DELIMITED BY SIZE   INTO SSA1                                        
041900     MOVE '  GE'           TO GOOD-STATUSCODES                            
042000     CALL CBLTDLI       USING GU WDK6-PCB DLI-IO-WDK601 SSA1              
042100     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
042200     PERFORM IMS-STATUSCHECK                                              
042300     .                                                                    
042400                                                                          
042500 IMS-GHNP-WDK611 SECTION.                                                 
042700     MOVE 'IMS-GHNP-WDK611            ' TO DBS-SECTION                    
042800                                                                          
042900     MOVE 'WDK611   '      TO SSA2                                        
043000     MOVE '  '             TO GOOD-STATUSCODES                            
043100     CALL CBLTDLI       USING GHNP WDK6-PCB DLI-IO-WDK611 SSA2            
043200     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
043300     PERFORM IMS-STATUSCHECK                                              
043400     .                                                                    
043500                                                                          
043600 IMS-GHNP-WDK626 SECTION.                                                 
043800     MOVE 'IMS-GHNP-WDK626            ' TO DBS-SECTION                    
043900                                                                          
044000     MOVE 'WDK611   '      TO SSA1                                        
044100     MOVE 'WDK626   '      TO SSA2                                        
044200     MOVE '  GE'           TO GOOD-STATUSCODES                            
044300     CALL CBLTDLI       USING GHNP WDK6-PCB DLI-IO-WDK626                 
044400                                              SSA1 SSA2                   
044500     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
044600     PERFORM IMS-STATUSCHECK                                              
044700     .                                                                    
044800     EJECT                                                                
044900                                                                          
045000 IMS-DLET-TREND-SASONG-JUST SECTION.                                      
045201     MOVE 'IMS-DLET-TREND-SASONG-JUST ' TO DBS-SECTION                    
045301                                                                          
045401     MOVE '  '             TO GOOD-STATUSCODES                            
045501     CALL CBLTDLI       USING DLET WDK6-PCB DLI-IO-WDK626                 
045601     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
045701     PERFORM IMS-STATUSCHECK                                              
045900     .                                                                    
046000                                                                          
046100 IMS-REPL-TREND-SASONG-JUST SECTION.                                      
046301     MOVE 'IMS-REPL-TREND-SASONG-JUST ' TO DBS-SECTION                    
046401                                                                          
046501     MOVE '  '             TO GOOD-STATUSCODES                            
046601     CALL CBLTDLI       USING REPL WDK6-PCB DLI-IO-WDK626                 
046701     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
046801     PERFORM IMS-STATUSCHECK                                              
047000     .                                                                    
047100                                                                          
047200 IMS-REPL-WDK611 SECTION.                                                 
047401     MOVE 'IMS-REPL-WDK611            ' TO DBS-SECTION                    
047501                                                                          
047601     MOVE '  '             TO GOOD-STATUSCODES                            
047701     CALL CBLTDLI       USING REPL WDK6-PCB DLI-IO-WDK611                 
047801     MOVE WDK6-STATUS-CODE TO STATUS-WS                                   
047901     PERFORM IMS-STATUSCHECK                                              
048100     .                                                                    
048200     EJECT                                                                
048300 IMS-GU-WLXXAD01    SECTION.                                              
048500     MOVE 'IMS-GU-WLXXAD01            ' TO DBS-SECTION                    
048600                                                                          
048700     STRING 'WLXXAD01(WDG3KEY  =' W-WDGX2207-X ')'                        
048800     DELIMITED BY SIZE   INTO SSA1                                        
048900     MOVE '  GE'           TO GOOD-STATUSCODES                            
049000     CALL CBLTDLI       USING GU 2207-PCB DLI-IO-WDG301 SSA1              
049100                                                                          
049200     MOVE 2207-STATUS-CODE TO STATUS-WS                                   
049300     PERFORM IMS-STATUSCHECK                                              
049400     .                                                                    
049500                                                                          
049600 IMS-GHNP-WLXXAD11        SECTION.                                        
049800     MOVE 'IMS-GHNP-WLXXAD11          ' TO DBS-SECTION                    
049900                                                                          
050000     MOVE 'WLXXAD11 '      TO SSA1                                        
050100     MOVE '  GE'           TO GOOD-STATUSCODES                            
050200     CALL CBLTDLI       USING GHNP 2207-PCB DLI-IO-WDGX2207 SSA1          
050300     MOVE 2207-STATUS-CODE TO STATUS-WS                                   
050400     PERFORM IMS-STATUSCHECK                                              
050500     .                                                                    
050600                                                                          
050700 IMS-DLET-WDGX2207      SECTION.                                          
050901     MOVE 'IMS-DLET-WDGX2207          ' TO DBS-SECTION                    
051001                                                                          
051101     MOVE '  '             TO GOOD-STATUSCODES                            
051201     CALL CBLTDLI       USING DLET 2207-PCB DLI-IO-WDGX2207               
051301     MOVE 2207-STATUS-CODE TO STATUS-WS                                   
051401     PERFORM IMS-STATUSCHECK                                              
051600     .                                                                    
051700     EJECT                                                                
051800 IMS-ISRT-R2202 SECTION.                                                  
052000     MOVE 'IMS-ISRT-R2202             ' TO DBS-SECTION                    
052100                                                                          
052201     STRING 'WLXXCK01(WDG3KEY  =' W-WDG3KEY ')'                           
052301             DELIMITED BY SIZE INTO SSA1                                  
052401     MOVE 'WLXXCK11'       TO SSA2                                        
052501     MOVE '  '             TO GOOD-STATUSCODES                            
052601     CALL CBLTDLI       USING ISRT 2202-PCB DLI-IO-WDG32202               
052701                                               SSA1 SSA2                  
052801     MOVE 2202-STATUS-CODE TO STATUS-WS                                   
052901     PERFORM IMS-STATUSCHECK                                              
053100     .                                                                    
053200                                                                          
056400 IMS-STATUSCHECK SECTION.                                                 
056500                                                                          
056600     SET STATUS-IX TO 1                                                   
056700     SEARCH GOOD-STATUS                                                   
056800       AT END                                                             
056900         STRING ' FELAKTIG STATUSKOD FRÅN IMS: ' STATUS-WS                
057000           DELIMITED BY SIZE INTO ERROR-TEXT                              
057100         DISPLAY ERROR-TEXT                                               
057200         CALL FELLOG                                                      
057300       WHEN GOOD-STATUS (STATUS-IX) = STATUS-WS                           
057400         CONTINUE                                                         
057500     END-SEARCH                                                           
057600     .                                                                    
057700*    -COPY WY2000P3                                                       
