000100*                  * CONVERTED BY VILMAII *                               
000200*                  * TO PURE COBOLCODE    *                               
000300 IDENTIFICATION DIVISION.                                                 
000400 PROGRAM-ID.     W2223000.                                                
000500*              PROGRAM CONVERTED BY                                       
000600*              COBOL CONVERSION AID PO 5785-ABJ                           
000700*              CONVERSION DATE 05/25/91 19:36:54.                         
000800*AUTHOR.         B SWANBERG DATA LOGIC AB.                                
000900*DATE-WRITTEN.   NOVEMBER 1978.                                           
001000*REMARKS.                                                                 
001100*        FUNKTION:                                                        
001200*            PROGRAMMET LÄSER FILEN W23265 INNEHÅLLANDE UPPGIFTER         
001300*            FRÅN ORDERINGÅNGSREGISTRET  (WDL8)                           
001400*            RESP POST KOMPLETTERAS MED RANDOMISERINGSNYCKELN             
001500*            FÖR WDK6 SAMT SORTERAS STIGANDE PÅ DENNA SAMT                
001600*            ARTNR.                                                       
001700*        SUBPROGRAM                                                       
001800*            W015RAND    GER RANDOMISERINGSNYCKELN TILL WDK6              
001900*                        FÖR ARTIKELNR                                    
002000*            RETURKODER                                                   
002100*            U0020       SORTERINGSFEL                                    
002200 ENVIRONMENT DIVISION.                                                    
002300*                                                                         
002400 INPUT-OUTPUT SECTION.                                                    
002500 FILE-CONTROL.                                                            
002600*                            *** EXTRAKT FRÅN ORDERINGÅNGSREG ***         
002700*                            *** INPUT                        ***         
002800     SELECT W23265 ASSIGN UT-S-W22230D1.                                  
002900*                            *** SORTERAD EXTRAKT FRÅN        ***         
003000*                            *** ORDERINGÅNGSREGISTRET       /***         
003100*                            ***OUTPUT                        ***         
003200     SELECT W22231 ASSIGN UT-S-W22230D2.                                  
003300*                            *** SORTERINGSFIL                ***         
003400*                            *** I-O                          ***         
003500     SELECT SORTFIL ASSIGN UT-S-W22230DS.                                 
003600 DATA DIVISION.                                                           
003700*                                                                         
003800 FILE SECTION.                                                            
003900*                                                                         
004000 FD  W23265                                                               
004100     RECORDING F                                                          
004200     BLOCK 0.                                                             
004300*01  POST -COPY W23265  -L.                                               
004500*                                                                         
004600 FD  W22231                                                               
004700     RECORDING F                                                          
004800     BLOCK 0.                                                             
004900*01  POST  -COPY W22231  -PRE W22231- -L.                                 
005100 SD  SORTFIL                                                              
005200                .                                                         
005300*01  POST  -COPY W22231  -PRE SORT-.                                      
005500     EJECT                                                                
005600 WORKING-STORAGE SECTION.                                                 
005610                                                                          
005700*    -- CHECKED BY WY2000                                                 
005800 77  INDENT-I PIC X(40) VALUE                                             
005900     'W2223000 91/05/25 TIME 12.51 VILMAII'.                              
006000***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
006100*                                                                         
006200*                                                                         
006300*                                                                         
006400 01  RKOD                    PIC S9(4)           COMP SYNC.               
006500*                                                                         
006600 01  KONSTANTER.                                                          
006700     03  JA                  PIC X       VALUE 'J'.                       
006800     03  NEJ                 PIC X       VALUE 'N'.                       
006900*                                                                         
007000 01  EOF-SWITCHAR.                                                        
007100     03  EOF-W23265          PIC X       VALUE 'N'.                       
007200*                                                                         
007300 01  SUBPROGRAM.                                                          
007400     03  ABEND               PIC X(8)    VALUE 'ABEND   '.                
007500     03  W015RAND            PIC X(8)    VALUE 'W015RAND'.                
007600     03  POSTSUM             PIC X(8)    VALUE 'POSTSUM '.                
007700 01  WDK6                    PIC X(8)    VALUE 'WDK6'.                    
007800*                                                                         
007900 01  W015RAND-IDARTNR        PIC S9(9)           COMP-3.                  
008000*                                                                         
008100 01  W015RAND-RANDKEY        PIC X(4).                                    
008200     EJECT                                                                
008300*                                                                         
008400*    -COPY W0005      -PRE POSTSUM-                                       
008600     EJECT                                                                
008700*                                                                         
008800*    ARBETS-AREA INPUT                                                    
008900*                                                                         
009000*01  AREA -COPY W23265  -PRE I01282-.                                     
009200     EJECT                                                                
009300*                                                                         
009400*    ARBETS-AREA SORTERING                                                
009500*                                                                         
009600*01  AREA -COPY W22231  -PRE W-.                                          
009800     EJECT                                                                
009900 PROCEDURE DIVISION.                                                      
010000*                                                                         
010100*                                                                         
010200*                                                                         
010300     SORT SORTFIL ASCENDING SORT-RANDKEY SORT-IDARTNR                     
010400     INPUT PROCEDURE A-SKAPA-POST                                         
010500     GIVING W22231                                                        
010600*                                                                         
010700     IF SORT-RETURN NOT = ZERO                                            
010800       MOVE 20 TO RKOD                                                    
010900       CALL ABEND USING RKOD                                              
011000     END-IF                                                               
011100     CLOSE W23265                                                         
011200*                                                                         
011300     MOVE 'S' TO POSTSUM-OPKOD                                            
011400     CALL POSTSUM USING POSTSUM-PARM                                      
011500     GOBACK                                                               
011600     CONTINUE.                                                            
011700     EJECT                                                                
011800 A-SKAPA-POST SECTION.                                                    
011900*                                                                         
012000*                                                                         
012100     PERFORM AA-HOUSEKEEPING                                              
012200*                                                                         
012300     PERFORM S01-LAS-POST                                                 
012400*                                                                         
012500     PERFORM UNTIL                                                        
012600      NOT ( EOF-W23265 = NEJ )                                            
012700       MOVE I01282-IDARTNR       TO W-IDARTNR                             
012800       MOVE I01282-TIAAPP        TO W-TIAAPP                              
012900       MOVE I01282-KVOI-PROG     TO W-KVOI-PROG                           
013100       MOVE I01282-KVOI-SATS     TO W-KVOI-SATS                           
013230       MOVE I01282-KVOI-REFILL   TO W-KVOI-REFILL                         
013300       MOVE I01282-IDARTNR       TO W015RAND-IDARTNR                      
013400*                                                                         
013500       CALL W015RAND USING W015RAND-IDARTNR                               
013600                            W015RAND-RANDKEY WDK6                         
013700*                                                                         
013800       MOVE W015RAND-RANDKEY TO W-RANDKEY                                 
013900       MOVE '289'            TO W-IDPTYP                                  
014000*                                                                         
014100       RELEASE SORT-POST FROM W-AREA                                      
014200*                                                                         
014300       PERFORM S01-LAS-POST                                               
014400     END-PERFORM                                                          
014500     CONTINUE.                                                            
014600     EJECT                                                                
014700 AA-HOUSEKEEPING SECTION.                                                 
014800*                                                                         
014900*                                                                         
015000     OPEN INPUT W23265                                                    
015100*                                                                         
015200     MOVE 'W22230'   TO POSTSUM-PROGNAMN                                  
015300     MOVE 'W22230D1' TO POSTSUM-DDNAMN2                                   
015400     MOVE 'W23265'   TO POSTSUM-FDNAMN                                    
015500     CONTINUE.                                                            
015600     EJECT                                                                
015700 S01-LAS-POST SECTION.                                                    
015800*                                                                         
015900*                                                                         
016000     READ W23265 INTO I01282-AREA                                         
016100     AT END                                                               
016200            MOVE JA TO EOF-W23265                                         
016300     END-READ                                                             
016400*                                                                         
016500     IF EOF-W23265 = NEJ                                                  
016600       MOVE I01282-IDPTYP TO POSTSUM-TRANSTYP                             
016700       CALL POSTSUM USING POSTSUM-PARM                                    
016800     END-IF                                                               
016900     CONTINUE.                                                            
