000100*                  * CONVERTED BY VILMAII *                               
000200*                  * TO PURE COBOLCODE    *                               
000300 ID  DIVISION.                                                            
000400 PROGRAM-ID.       W2365000.                                              
000800*AUTHOR.           JANNE MELANDER.                                        
000900*INSTALLATION.                                                            
001000*DATE-WRITTEN.     MAJ 1987.                                              
001100*REMARKS.                                                                 
001200*    FUNKTION.                                                            
001300*        PROGRAMMET LÄSER FILEN W23648 SOM INNEHÅLLER INLEVERANSEW        
001400*        STANDARDPRIS SAMT ANSKAFFARNR HÄMTAS FRÅN WDK6.                  
001500*        NY FIL W23651 SKRIVS UT OM RÄNTAN PÅ VÄRDET AV INLEVERANS        
001600*        ÖVERSTIGER 500 SVKR OCH OM                                       
001700*        INLEVERANSEN ÄR INLEVERERAD MER ÄN 1 VECKA FÖR TIDIGT.           
001710*                                                                         
001800*    INDATA.                                                              
001900*                                                                         
002000*        FILE W23648;                                                     
002100*    UTDATA.                                                              
002200*                                                                         
002300*        FILE W23651;                                                     
002400                                                                          
002500     EJECT                                                                
002600 ENVIRONMENT DIVISION.                                                    
002700 INPUT-OUTPUT SECTION.                                                    
002800 FILE-CONTROL.                                                            
002900*                                                                         
003000     SELECT  W23648     ASSIGN UT-S-W23650D1.                             
003100*            *** INPUT-FILE ***                                           
003200     SELECT  W23651     ASSIGN UT-S-W23650D2.                             
003300*            *** OUTPUT-FILE ***                                          
003400*                                                                         
003500     EJECT                                                                
003600 DATA DIVISION.                                                           
003700 FILE SECTION.                                                            
003800     SKIP3                                                                
003900 FD  W23648                                                               
004000     RECORDING      F                                                     
004100     BLOCK CONTAINS 0.                                                    
004200                                                                          
004300*01  IN-POST   -COPY W236RY7    -L.                                       
004500                                                                          
004600     EJECT                                                                
004700 FD  W23651                                                               
004800     RECORDING      F                                                     
004900     BLOCK CONTAINS 0.                                                    
005000                                                                          
005100*01  UT-POST   -COPY W23650     -L.                                       
005300                                                                          
005400     EJECT                                                                
005500 WORKING-STORAGE SECTION.                                                 
005510*    -COPY WY2000W3                                                       
005600     SKIP3                                                                
005700 77  INDENT-I PIC X(40) VALUE                                             
005800     'W2365000 91/05/25 TIME 13.16 VILMAII'.                              
005900***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
006000*                                                                         
006100                                                                          
006200 77  EOF-W23648          PIC X       VALUE 'N'.                           
006300 77  JA                  PIC X       VALUE 'J'.                           
006400 77  NEJ                 PIC X       VALUE 'N'.                           
006500 77  SAKNAS              PIC X       VALUE 'S'.                           
006600 77  ABEND-CODE          PIC S9(4)   COMP SYNC  VALUE +0.                 
006700     SKIP2                                                                
006800 01  SPAR-FAELT.                                                          
006900   03  SPAR-IDARTNR            PIC S9(9)   COMP-3.                        
007000   03  SPAR-IDLEVNR            PIC X(05).                                 
007100   03  SPAR-IDANSK             PIC 9(03).                                 
007200   03  SPAR-VAERDE             PIC 9(7)V9(2).                             
007300   03  SPAR-RAENTE-VAERDE      PIC 9(7)V9(2).                             
007400   03  SPAR-KVAVROP            PIC 9(7).                                  
007500   03  SPAR-TIAVROP-INL        PIC 9(5).                                  
007600   03  SPAR-TIANKDAG           PIC 9(5).                                  
007610   03  SPAR-KDEFFMAN           PIC X(1).                                  
007700                                                                          
007800 01  ARBETSFAELT.                                                         
007900   03  TOT-VAERDE              PIC 9(7)V9(2).                             
008000   03  RAENTE-VAERDE           PIC 9(7)V9(2).                             
008100                                                                          
008300   03  W-ANTAL-VV              PIC S9(3)  COMP-3.                         
008400   03  W-TIAVROP-INL.                                                     
008500     05  W-TIAVROP-INL-AA      PIC 9(3).                                  
008600     05  W-TIAVROP-INL-VV      PIC 9(2).                                  
008700   03  W-TIANKDAG.                                                        
008800     05  W-TIANKDAG-AA         PIC 9(3).                                  
008900     05  W-TIANKDAG-VV         PIC 9(2).                                  
009200     SKIP2                                                                
009300 01  SUBPROGRAM.                                                          
009400                                                                          
009500     03  GENERELLA.                                                       
009600         05  ABEND       PIC X(8)    VALUE 'ABEND'.                       
009700         05  DATKORT     PIC X(8)    VALUE 'DATKORT'.                     
009800         05  POSTSUM     PIC X(7)    VALUE 'POSTSUM'.                     
009900         05  CBLTDLI     PIC X(8)    VALUE 'CBLTDLI '.                    
010000         05  FELLOG      PIC X(8)    VALUE 'FELLOG  '.                    
010200     EJECT                                                                
010300*                                                                         
010400*03  IN-AREA       -COPY W236RY7    -PRE IN-                              
010600     EJECT                                                                
010700*                                                                         
010800*01  UT-AREA       -COPY W23650     -PRE UT-                              
011000     EJECT                                                                
011100                                                                          
011200*    PARAMETAR TILL POSTSUM.                                              
011300     SKIP3                                                                
011400 01  PROGRAM-NAMN        PIC X(6)   VALUE 'W23650'.                       
011500*                                                                         
011600*            -COPY W0005   -PRE POSTSUM-                                  
011800     EJECT                                                                
011900*----------------------------- NYCKLAR                                    
012000*                                                                         
012100 01  W-IDARTNR-X.                                                         
012200   03  W-IDARTNR          PIC S9(9)  COMP-3.                              
012300*                                                                         
012400*--------------------------ARBETSAREOR TILL IMS-SECTIONERNA               
012500*                                                                         
012600 01  FILLER               PIC X(8)  VALUE 'IMS-WS  '.                     
012700*                                                                         
012800 01  IMS-WS.                                                              
012900*                                                                         
013000     03  STATUS-WS        PIC X(2).                                       
013100        88 SEGMENT-FINNS            VALUE '  '.                           
013200        88 SEGMENT-SAKNAS           VALUE 'GE'.                           
013300        88 SEGMENT-SLUT             VALUE 'GB'.                           
013400*                                                                         
013500     03  GODK-STATUSKODER.                                                
013600         05 GODK-STATUS OCCURS 5 INDEXED BY STATUS-IX PIC X(2).           
013700*                                                                         
013800     03  SSA1                   PIC X(64).                                
013900     03  SSA2                   PIC X(64).                                
014000*                                                                         
014100*01  -COPY W0003                                                          
014300*                                                                         
014400 01   DLI-IO-AREA.                                                        
014500*                                                                         
014600      03 IO-AREA            PIC X(900).                                   
014700*                                                                         
014800*   03 WDK611   -COPY WDK611 -RED IO-AREA                                 
015300*                                                                         
015400 LINKAGE SECTION.                                                         
015500*    -COPY W0008  -PRE WLARTC-                                            
015700         05  FILLER      PIC X(10).                                       
015800     EJECT                                                                
015900 PROCEDURE DIVISION USING WLARTC-PCB.                                     
016000     ENTRY 'DLITCBL' USING WLARTC-PCB.                                    
016100     SKIP2                                                                
016200     PERFORM A-INIT                                                       
016300     PERFORM S01-LAES-W23648                                              
016500     PERFORM UNTIL  EOF-W23648 = JA                                       
016501       MOVE SPAR-TIAVROP-INL   TO TMP1-YYWW                               
016502       MOVE SPAR-TIANKDAG      TO TMP2-YYWW                               
016503       PERFORM WY2000P3                                                   
016600       IF TMP1-YYWW > TMP2-YYWW                                           
016610                                                                          
016700         PERFORM B-BEHANDLA-DATUM                                         
017200         IF W-ANTAL-VV > 1                                                
017300           MOVE IN-RY7-IDARTNR TO W-IDARTNR                               
017400           PERFORM IMS-GET-WLARTC01                                       
017500           PERFORM IMS-GET-WLARTC11                                       
017600           MOVE CLAG-IDANSK TO SPAR-IDANSK                                
017700           MOVE CLAG-KDEFFMAN TO SPAR-KDEFFMAN                            
017900           COMPUTE TOT-VAERDE = CLAG-PRARTSTD *                           
018000                                IN-RY7-KVAVIS                             
018200           COMPUTE RAENTE-VAERDE =                                        
018300           TOT-VAERDE * W-ANTAL-VV * 0.15 / 52                            
018400           IF RAENTE-VAERDE > 500                                         
018500             MOVE TOT-VAERDE TO SPAR-VAERDE                               
018600             MOVE RAENTE-VAERDE TO SPAR-RAENTE-VAERDE                     
018700             PERFORM S02-SKRIV-W23651                                     
018800           END-IF                                                         
018900         END-IF                                                           
019000       END-IF                                                             
019100       MOVE ZERO  TO SPAR-VAERDE                                          
019200       MOVE ZERO  TO SPAR-RAENTE-VAERDE                                   
019300       MOVE ZERO  TO SPAR-IDARTNR                                         
019400       MOVE ZERO  TO SPAR-IDANSK                                          
019500       MOVE SPACE TO SPAR-IDLEVNR                                         
019600       MOVE ZERO  TO SPAR-KVAVROP                                         
019700       MOVE ZERO  TO SPAR-TIAVROP-INL                                     
019800       MOVE ZERO  TO SPAR-TIANKDAG                                        
019810       MOVE SPACE TO SPAR-KDEFFMAN                                        
019900       PERFORM S01-LAES-W23648                                            
020000     END-PERFORM                                                          
020100     PERFORM Z-FINIT                                                      
020200     MOVE ZERO TO RETURN-CODE                                             
020300     GOBACK                                                               
020400     .                                                                    
020500     EJECT                                                                
020600 A-INIT SECTION.                                                          
020700     SKIP2                                                                
020800     OPEN INPUT  W23648                                                   
020900     OPEN OUTPUT W23651                                                   
021000                                                                          
021100     MOVE ZERO  TO SPAR-VAERDE                                            
021200     MOVE ZERO  TO SPAR-IDARTNR                                           
021300     MOVE ZERO  TO SPAR-IDANSK                                            
021400     MOVE SPACE TO SPAR-IDLEVNR                                           
021500     MOVE ZERO  TO SPAR-KVAVROP                                           
021600     MOVE ZERO  TO SPAR-TIAVROP-INL                                       
021700     MOVE ZERO  TO SPAR-TIANKDAG                                          
021710     MOVE SPACE TO SPAR-KDEFFMAN                                          
021800                                                                          
021900     MOVE PROGRAM-NAMN TO POSTSUM-PROGNAMN                                
022000     .                                                                    
022100                                                                          
022200 B-BEHANDLA-DATUM SECTION.                                                
022300     MOVE SPAR-TIAVROP-INL     TO W-TIAVROP-INL                           
022400     MOVE SPAR-TIANKDAG        TO W-TIANKDAG                              
022410                                                                          
022430     COMPUTE W-ANTAL-VV = W-TIAVROP-INL-VV  -                             
022440                          W-TIANKDAG-VV                                   
022500     IF W-ANTAL-VV < 0                                                    
022600       ADD 52                  TO W-ANTAL-VV                              
022620     END-IF                                                               
023300     .                                                                    
023400                                                                          
023500 S02-SKRIV-W23651  SECTION.                                               
023600     MOVE IN-RY7-IDARTNR       TO UT-IDARTNR                              
023700     MOVE SPAR-VAERDE          TO UT-VAERDE                               
023800     MOVE SPAR-RAENTE-VAERDE   TO UT-RAENTE-VAERDE                        
023900     MOVE SPAR-TIAVROP-INL     TO UT-TIAVROP-INL                          
024000     MOVE SPAR-TIANKDAG        TO UT-TIAVROP-DISP                         
024100     MOVE SPAR-IDLEVNR         TO UT-IDLEVNR                              
024200     MOVE SPAR-IDANSK          TO UT-IDANSK                               
024300     MOVE SPAR-KVAVROP         TO UT-KVAVROP                              
024310     MOVE SPAR-KDEFFMAN        TO UT-KDEFFMAN                             
024400                                                                          
024500     WRITE UT-POST FROM UT-UT-AREA                                        
024600                                                                          
024700     MOVE 'W23651 '         TO POSTSUM-FDNAMN                             
024800     MOVE 'W23650D2'        TO POSTSUM-DDNAMN2                            
024900     MOVE SPACE             TO POSTSUM-TRANSTYP                           
025000     CALL POSTSUM USING POSTSUM-PARM                                      
025100     .                                                                    
025200     EJECT                                                                
025300 S01-LAES-W23648   SECTION.                                               
025400     READ W23648 INTO IN-IN-AREA                                          
025500     AT END MOVE JA TO EOF-W23648                                         
025600     END-READ                                                             
025700     IF EOF-W23648 = NEJ                                                  
025800                                                                          
025900       MOVE IN-RY7-IDARTNR      TO SPAR-IDARTNR                           
026000       MOVE IN-RY7-IDLEVNR      TO SPAR-IDLEVNR                           
026100       MOVE IN-RY7-KVAVIS       TO SPAR-KVAVROP                           
026200       MOVE IN-RY7-TIAVROP-INL  TO SPAR-TIAVROP-INL                       
026300       MOVE IN-RY7-TIANKDAG     TO SPAR-TIANKDAG                          
026400                                                                          
026500       MOVE 'INFIL'    TO POSTSUM-FDNAMN                                  
026600       MOVE 'W23650D1' TO POSTSUM-DDNAMN2                                 
026700       MOVE SPACE      TO POSTSUM-TRANSTYP                                
026800       CALL POSTSUM USING POSTSUM-PARM                                    
026900     END-IF                                                               
027000     .                                                                    
027100     EJECT                                                                
027200 Z-FINIT SECTION.                                                         
027300     SKIP2                                                                
027400     MOVE 'S' TO POSTSUM-OPKOD                                            
027500     CALL POSTSUM USING POSTSUM-PARM                                      
027600                                                                          
027700     CLOSE W23648 W23651                                                  
027800     .                                                                    
027900     EJECT                                                                
028000**                                                                        
028100******* I M S   S E C T I O N  ***                                        
028200**                                                                        
028300 IMS-GET-WLARTC01 SECTION.                                                
028400*                                                                         
028500     STRING 'WLARTC01(IDARTNR  =' W-IDARTNR-X ')'                         
028600     DELIMITED BY SIZE INTO SSA1                                          
028700     MOVE '  ' TO GODK-STATUSKODER                                        
028800     CALL CBLTDLI USING GU WLARTC-PCB DLI-IO-AREA SSA1                    
028900     MOVE WLARTC-STATUS-CODE TO STATUS-WS                                 
029000     PERFORM IMS-STATUSKONTROLL                                           
029100     .                                                                    
029200     SKIP3                                                                
029300 IMS-GET-WLARTC11 SECTION.                                                
029400*                                                                         
029500     MOVE 'WLARTC11 ' TO SSA1                                             
029600     MOVE '  ' TO GODK-STATUSKODER                                        
029700     CALL CBLTDLI USING GNP WLARTC-PCB DLI-IO-AREA SSA1                   
029800     MOVE WLARTC-STATUS-CODE TO STATUS-WS                                 
029900     PERFORM IMS-STATUSKONTROLL                                           
030000     .                                                                    
030100     SKIP3                                                                
031100 IMS-STATUSKONTROLL SECTION.                                              
031200     SET STATUS-IX TO 1                                                   
031300     SEARCH GODK-STATUS                                                   
031400     AT END                                                               
031500       CALL FELLOG                                                        
031600     WHEN GODK-STATUS (STATUS-IX) = STATUS-WS                             
031700       CONTINUE                                                           
031800     END-SEARCH                                                           
031900     .                                                                    
032010     EJECT                                                                
032100*    -COPY WY2000P3                                                       
