000100*                  * CONVERTED BY VILMAII *                               
000200*                  * TO PURE COBOLCODE    *                               
000300     SKIP2                                                                
000400 ID  DIVISION.                                                            
000500     SKIP2                                                                
000600 PROGRAM-ID.    W4300400.                                                 
000700*              PROGRAM CONVERTED BY                                       
000800*              COBOL CONVERSION AID PO 5785-ABJ                           
000900*              CONVERSION DATE 05/25/91 17:28:20.                         
001000*AUTHOR.        LENA JOHANSSON.                                           
001100*DATE-WRITTEN.  MARS 1983.                                                
001200                                                                          
001300*REMARKS.                                                                 
001400                                                                          
001500*    FUNKTION:                                                            
001600*             HOPSAMLING AV FILER TILL PLOCKFREKVENSSTATISTIK.            
001700*             FILER FRÅN ORDESYSTEMEN (W491 OCH W402) OCH                 
001800*             FYSISKA AVVIKELSER FRÅN PACKNINGSSYSTEMET (W473).           
001900     EJECT                                                                
002000 ENVIRONMENT DIVISION.                                                    
002100     SKIP2                                                                
002200 INPUT-OUTPUT SECTION.                                                    
002300*                                                                         
002400 FILE-CONTROL.                                                            
002500     SKIP2                                                                
002600     SELECT W430XX-INFIL                 ASSIGN TO UT-S-W43004D1.         
002700     SELECT W43051-UTFIL                 ASSIGN TO UT-S-W43004D2.         
002800     SELECT W43053-UTFIL                 ASSIGN TO UT-S-W43004D3.         
002900     SELECT SORTFIL                      ASSIGN TO UT-S-W43004DS.         
003000     EJECT                                                                
003100 DATA DIVISION.                                                           
003200     SKIP2                                                                
003300 FILE SECTION.                                                            
003400     SKIP3                                                                
003500 FD  W430XX-INFIL                                                         
003600     RECORDING      F                                                     
003700     BLOCK CONTAINS 0.                                                    
003800     SKIP2                                                                
003900*    -COPY W430432      -L.                                               
004100     SKIP3                                                                
004200 FD  W43051-UTFIL                                                         
004300     RECORDING      F                                                     
004400     BLOCK CONTAINS 0.                                                    
004500     SKIP2                                                                
004600*01  POST -COPY W430432     -PRE UT51-  -L.                     CL        
004800     EJECT                                                                
004900 FD  W43053-UTFIL                                                         
005000     RECORDING       F                                                    
005100     BLOCK CONTAINS 0.                                                    
005200*01  POST -COPY W430453     -PRE UT53-  -L.                     CL        
005400     EJECT                                                                
005500 SD  SORTFIL                                                              
005600                      .                                                   
005700*    POST -COPY W430432     -PRE SORT-                                    
005900     EJECT                                                                
006000 WORKING-STORAGE SECTION.                                                 
006010                                                                          
006100*    -- CHECKED BY WY2000                                                 
006200 77  INDENT-I PIC X(40) VALUE                                             
006300     'W4300400 91/05/25 TIME 12.55 VILMAII'.                              
006400***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
006500*                                                                         
006600*                                                                         
006700 77  PROGRAM-NAMN                REDEFINES INDENT-I                       
006800                                 PIC X(6).                                
006900*                                      GENERERAT PROGRAM-NAMN.            
007000 77  ABENDKOD                    PIC S9(4) COMP SYNC.                     
007100     SKIP2                                                                
007200 01  GENERELLA-KONSTANTER.                                                
007300*                                                                         
007400     03  JA                      PIC X(1)    VALUE 'J'.                   
007500     03  NEJ                     PIC X(1)    VALUE 'N'.                   
007600     SKIP3                                                                
007700 01  SPAR-ELEMENT.                                                        
007800*                                                                         
007900     03  SPAR-IDPTYP      PIC X(3)           VALUE ZERO.                  
008000     03  SPAR-IDDC        PIC  X(2)          VALUE SPACE.                 
008100     03  SPAR-IDDISTR     PIC S9(5)   COMP-3 VALUE ZERO.                  
008200     03  SPAR-IDARTNR     PIC S9(9)   COMP-3 VALUE ZERO.                  
008300     03  SPAR-KDORDKL     PIC S9(1)   COMP-3 VALUE ZERO.                  
008400                                                                          
008500 01  FILLER.                                                              
008600*                                                                         
008700     03  KVLEVART         PIC S9(9)   COMP-3 VALUE ZERO.                  
008800     03  KVPLOCK          PIC S9(9)   COMP-3 VALUE ZERO.                  
008900*                                                                         
009000     EJECT                                                                
009100 01  DYNAMISKA-SUBPROGRAM.                                                
009200*                                                                         
009300     03  ABEND                   PIC X(8)    VALUE 'ABEND'.               
009400     03  POSTSUM                 PIC X(8)    VALUE 'POSTSUM'.             
009500     SKIP3                                                                
009600 01  SWITCHAR.                                                            
009700*                                                                         
009800     03  SORTFIL-EOF             PIC X(1)    VALUE 'N'.                   
009900     03  FOERSTA-POST            PIC X(1)    VALUE 'J'.                   
010000     EJECT                                                                
010100*- - - - - - - - - - - - - - - - PARAMETRAR TILL POSTSUM                  
010200*                                                                         
010300*01  -COPY W0005      -PRE  POSTSUM-                                      
010500     EJECT                                                                
010600 01  INAREA                 PIC X(24)   VALUE                             
010700                                            'IN-AREA IN-AREA '.           
010800     SKIP3                                                                
010900*01  AREA  -PRE IN-  -COPY W430432                                        
011100     EJECT                                                                
011200 01  UT1AREA                 PIC X(24)  VALUE                             
011300                                            'UT-AREA UT1-AREA'.           
011400*01  AREA  -PRE UT51-    -COPY W430432                                    
011600     EJECT                                                                
011700 01  UT2AREA                 PIC X(24)  VALUE                             
011800                                            'UT2-AREA UT2-AREA'.          
011900*01  AREA  -PRE UT53-    -COPY W430453                                    
012100     EJECT                                                                
012200 PROCEDURE DIVISION.                                                      
012300     SKIP2                                                                
012400     PERFORM A-INIT                                                       
012410     DISPLAY 'POS2'                                                       
012500     SORT SORTFIL ASCENDING KEY                                           
012600                  SORT-IDDC                                               
012700                  SORT-IDDISTR                                            
012800                  SORT-IDARTNR                                            
012900                  SORT-KDORDKL                                            
013000     USING W430XX-INFIL                                                   
013100     OUTPUT PROCEDURE B-BEARBETA                                          
013200     IF SORT-RETURN > 0                                                   
013300       DISPLAY 'SORTFEL'                                                  
013400       MOVE +20 TO ABENDKOD                                               
013500       CALL ABEND USING ABENDKOD                                          
013600     ELSE                                                                 
013700       PERFORM Z-AVSLUTA                                                  
013800       MOVE ZERO TO RETURN-CODE                                           
013900       GOBACK                                                             
014000     END-IF                                                               
014100     CONTINUE.                                                            
014110     SKIP2                                                                
014300 A-INIT SECTION.                                                          
014400     SKIP2                                                                
014410     DISPLAY 'POS1-A-INIT'                                                
014500     OPEN OUTPUT W43051-UTFIL                                             
014600                 W43053-UTFIL                                             
014700                                                                          
014800     MOVE PROGRAM-NAMN TO POSTSUM-PROGNAMN                                
014900     CONTINUE.                                                            
015000     EJECT                                                                
015100 B-BEARBETA SECTION.                                                      
015110     DISPLAY 'POSB-BEARB'                                                 
015111                                                                          
015120     PERFORM BA-LAS-SORT                                                  
015200     IF SORTFIL-EOF = JA                                                  
015210       CONTINUE                                                           
015220     ELSE                                                                 
015400       PERFORM BB-FLYTTA-INFELT                                           
015500       PERFORM UNTIL                                                      
015600        NOT ( SORTFIL-EOF = NEJ )                                         
015700         IF IN-IDPTYP = 433                                               
015800           PERFORM BC-SKRIV-W43051                                        
015900         ELSE                                                             
016000           PERFORM BC-SKRIV-W43051                                        
016100           PERFORM BD-ACK-PLOCK                                           
016200         END-IF                                                           
016300         PERFORM BA-LAS-SORT                                              
016400       END-PERFORM                                                        
016410     END-IF                                                               
016500     .                                                                    
016600     EJECT                                                                
016700 BA-LAS-SORT  SECTION.                                                    
016800     SKIP2                                                                
016900     RETURN SORTFIL INTO IN-AREA                                          
017000     AT END                                                               
017100        MOVE JA TO SORTFIL-EOF                                            
017200     END-RETURN                                                           
017300*                                                                         
017400     IF SORTFIL-EOF = NEJ                                                 
017500       MOVE 'INPOST' TO POSTSUM-FDNAMN                                    
017600       MOVE 'W43004D1' TO POSTSUM-DDNAMN2                                 
017700       MOVE IN-IDPTYP TO POSTSUM-TRANSTYP                                 
017800       CALL POSTSUM USING POSTSUM-PARM                                    
017900     END-IF                                                               
018000     CONTINUE.                                                            
018100     EJECT                                                                
018200 BB-FLYTTA-INFELT SECTION.                                                
018300     SKIP2                                                                
018400     MOVE IN-IDPTYP TO SPAR-IDPTYP                                        
018500     MOVE IN-IDDC    TO SPAR-IDDC                                         
018600     MOVE IN-IDDISTR TO SPAR-IDDISTR                                      
018700     MOVE IN-IDARTNR TO SPAR-IDARTNR                                      
018800     MOVE IN-KDORDKL TO SPAR-KDORDKL                                      
018900     MOVE IN-KVBEART TO KVLEVART                                          
019000     MOVE 1 TO KVPLOCK                                                    
019100     CONTINUE.                                                            
019200     EJECT                                                                
019300 BC-SKRIV-W43051 SECTION.                                                 
019400     SKIP2                                                                
019500     WRITE UT51-POST FROM IN-AREA                                         
019600*                                                                         
019700     MOVE UT51-IDPTYP TO POSTSUM-TRANSTYP                                 
019800     MOVE 'UTFIL ' TO POSTSUM-FDNAMN                                      
019900     MOVE 'W43004D2' TO POSTSUM-DDNAMN2                                   
020000     CALL POSTSUM USING POSTSUM-PARM                                      
020100     CONTINUE.                                                            
020200     EJECT                                                                
020300 BD-ACK-PLOCK SECTION.                                                    
020400     SKIP2                                                                
020500     IF IN-IDDC     = SPAR-IDDC                                           
020600     AND IN-IDDISTR = SPAR-IDDISTR                                        
020700     AND IN-IDARTNR = SPAR-IDARTNR                                        
020800     AND IN-KDORDKL = SPAR-KDORDKL                                        
020900       COMPUTE KVLEVART = KVLEVART + IN-KVBEART                           
021000       ADD 1 TO KVPLOCK                                                   
021100     ELSE                                                                 
021200       PERFORM BDA-SKRIV-W43053                                           
021300       PERFORM BB-FLYTTA-INFELT                                           
021400     END-IF                                                               
021500     CONTINUE.                                                            
021600     EJECT                                                                
021700 BDA-SKRIV-W43053 SECTION.                                                
021800     SKIP2                                                                
021900     IF SPAR-IDPTYP = 432                                                 
022000       MOVE SPAR-IDPTYP TO UT53-IDPTYP                                    
022100       MOVE SPAR-IDDC     TO UT53-IDDC                                    
022200       MOVE SPAR-IDDISTR TO UT53-IDDISTR                                  
022300       MOVE SPAR-IDARTNR TO UT53-IDARTNR                                  
022400       MOVE SPAR-KDORDKL TO UT53-KDORDKL                                  
022500       MOVE KVLEVART   TO UT53-KVLEVART                                   
022600       MOVE KVPLOCK    TO UT53-KVPLOCK                                    
022700       WRITE UT53-POST FROM UT53-AREA                                     
022800*                                                                         
022900       MOVE UT53-IDPTYP TO POSTSUM-TRANSTYP                               
023000       MOVE 'UTFIL2' TO POSTSUM-FDNAMN                                    
023100       MOVE 'W43004D3' TO POSTSUM-DDNAMN2                                 
023200       CALL POSTSUM USING POSTSUM-PARM                                    
023300     END-IF                                                               
023400     CONTINUE.                                                            
023500     EJECT                                                                
023600 Z-AVSLUTA SECTION.                                                       
023700     SKIP2                                                                
023800     CLOSE W43051-UTFIL                                                   
023900           W43053-UTFIL                                                   
024000                                                                          
024100     MOVE 'S' TO POSTSUM-OPKOD                                            
024200     CALL POSTSUM USING POSTSUM-PARM                                      
024300     CONTINUE.                                                            
