000400 ID DIVISION.                                                             
000500                                                                          
000600 PROGRAM-ID. W8100400.                                                    
001000 AUTHOR. THOMAS FALLENIUS.                                                
001200 DATE-WRITTEN. JULI 1979.                                                 
001400     REMARKS.                                                             
001500*        DETTA ÄR ETT PROGRAM SOM LÄSER WDF5                              
001700     SKIP3                                                                
001800 ENVIRONMENT DIVISION.                                                    
001900 INPUT-OUTPUT SECTION.                                                    
002000 FILE-CONTROL.                                                            
002100                                                                          
002200     SELECT ARTIKELFILE-UT ASSIGN TO UT-S-W81004D1.                       
002300     EJECT                                                                
002400 DATA DIVISION.                                                           
002500 FILE SECTION.                                                            
002600 FD      ARTIKELFILE-UT                                                   
002700         RECORDING MODE F                                                 
002800         BLOCK CONTAINS 0 RECORDS.                                        
002900     SKIP2                                                                
003000*01  FILE    -COPY W81004L1      -PRE UT-    -L.                          
003200     EJECT                                                                
003300 WORKING-STORAGE SECTION.                                                 
003310                                                                          
003400*    -- CHECKED BY WY2000                                                 
003500 77  INDENT-I PIC X(40) VALUE                                             
003600     'W8100400 91/05/25 TIME 13.51 VILMAII'.                              
003700***  STATEMENT ABOVE GENERATED BY VILMAII CONVERTER                       
003800*                                                                         
003900     SKIP3                                                                
004000 77      IDARTNR-WS      PIC S9(9)   VALUE ZERO    COMP-3.                
004100 77      JA              PIC X       VALUE 'J'.                           
004200 77      NEJ             PIC X       VALUE 'N'.                           
004300     SKIP3                                                                
004310 01  DYNAMISKA-SUBPROGRAM.                                                
004311     03  CBLTDLI         PIC X(8) VALUE 'CBLTDLI'.                        
004320     SKIP3                                                                
004330 01  STATUS-WS           PIC XX.                                          
004340     88  SEGMENT-FINNS   VALUE '  '.                                      
004341     88  SEGMENT-SAKNAS  VALUE 'GE'.                                      
004342     88  SEGMENT-SLUT    VALUE 'GB'.                                      
004350     SKIP3                                                                
004360 01  GODK-STATUSKODER.                                                    
004370     05  GODK-STATUS     PIC XX   OCCURS 5 INDEXED BY STATUS-IX.          
004380     SKIP3                                                                
004390*01  -COPY W0003                                                          
004391     EJECT                                                                
004400*01  POST    -COPY W81004L1      -PRE UT-                                 
004600     EJECT                                                                
004610 01      DLI-IO-AREA     PIC X(200).                                      
004620     SKIP3                                                                
004630*01  WDF501      -COPY WDF501  -RED DLI-IO-AREA.                          
004640     EJECT                                                                
004650*01  WDF502      -COPY WDF502  -RED DLI-IO-AREA.                          
004660     EJECT                                                                
004700 LINKAGE SECTION.                                                         
005900*01              -COPY W0008  -PRE WDF5-                                  
006000     05  FILLER               PIC X.                                      
006100     EJECT                                                                
006200 PROCEDURE DIVISION USING WDF5-PCB.                                       
006300     ENTRY 'DLITCBL' USING WDF5-PCB.                                      
006500     OPEN OUTPUT ARTIKELFILE-UT                                           
006600     SKIP2                                                                
006610     PERFORM IMS-GN-SEGMENT                                               
006620     PERFORM UNTIL SEGMENT-SLUT                                           
007000         EVALUATE WDF5-SEG-NAME-FB                                        
007100         WHEN 'WDF501  '                                                  
007200                            PERFORM A-FLYTTA-VARDEN-FRAN-WDF501           
007300         WHEN 'WDF502  '                                                  
007400                            PERFORM B-FLYTTA-VARDEN-FRAN-WDF502           
007500                            WRITE UT-FILE FROM UT-POST                    
007800         END-EVALUATE                                                     
007801         PERFORM IMS-GN-SEGMENT                                           
007810     END-PERFORM                                                          
007820     CLOSE ARTIKELFILE-UT                                                 
007900     MOVE ZERO TO RETURN-CODE                                             
008000     GOBACK.                                                              
008200     EJECT                                                                
008300 A-FLYTTA-VARDEN-FRAN-WDF501 SECTION.                                     
008400     SKIP3                                                                
008500     MOVE XART-IDARTNR      TO UT-IDARTNR                                 
008600     MOVE XART-REKSIFFR     TO UT-REKSIFFR                                
008700     MOVE XART-KDFTAG       TO UT-KDFTAG                                  
008800     MOVE XART-TIV-UPPDAT   TO UT-TIV-UPPDAT                              
008900     CONTINUE.                                                            
009000     SKIP3                                                                
009100 B-FLYTTA-VARDEN-FRAN-WDF502 SECTION.                                     
009200     SKIP3                                                                
009300     MOVE XLEV-IDLEVNR      TO UT-IDLEVNR                                 
009400     MOVE XLEV-IDBENR       TO UT-IDBENR                                  
009500     MOVE XLEV-FLTLVM       TO UT-FLTLVM                                  
009600     MOVE XLEV-BELEVART     TO UT-BELEV                                   
009700     CONTINUE.                                                            
009800 IMS-GN-SEGMENT    SECTION.                                               
009810     MOVE '  GAGKGB' TO GODK-STATUSKODER                                  
009820     CALL CBLTDLI USING GN WDF5-PCB DLI-IO-AREA                           
009830     MOVE WDF5-STATUS-CODE TO STATUS-WS                                   
009840     PERFORM IMS-STATUSKONTROLL                                           
009850     .                                                                    
010000     SKIP3                                                                
010100 IMS-STATUSKONTROLL SECTION.                                              
010200     SET STATUS-IX TO 1                                                   
010300     SEARCH GODK-STATUS                                                   
010400         WHEN GODK-STATUS (STATUS-IX) = STATUS-WS                         
010500             CONTINUE                                                     
010510     END-SEARCH                                                           
010600     .                                                                    
